### PR TITLE
Add exiv2 to the pinnings

### PR DESCRIPTION
**Pull request by hmaarrfk**
Fixes: https://github.com/conda-forge/exiv2-feedstock/issues/2
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
should I update the version? or do  you leave that to an other PR? I always forget

**Comment by CJ-Wright** [comment]
The version auto updates

**Comment by hmaarrfk** [comment]
got it, thanks.

A run export PR has been added to the repo as well.

https://github.com/conda-forge/exiv2-feedstock/pull/3

**Comment by hmaarrfk** [comment]
Kind ping.

**Pull request merged**
