### PR TITLE
add arrow pin

### PR DESCRIPTION
**Pull request by CJ-Wright**
This is a novel pin: [ABI lab](https://abi-laboratory.pro/index.php?view=timeline&l=apache-arrow)

The recipe has a `run_exports` set to `x.x`.

Attn:
@conda-forge/arrow-cpp
@jakirkham

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/conda-forge-pinning

**Comment by jakirkham** [comment]
Thanks for doing this. Sorry for dropping the ball here.

**Comment by isuruf** [comment]
As with the FFTW PR, this doesn't need a migration, but need a patch to repodata.

**Comment by jakirkham** [comment]
Could you expand on that @isuruf? I think I’m missing context.

**Comment by isuruf** [comment]
When adding a new pin, you don't need to rebuild, because they've already been built. We need a migrator only when you update a pin.

You need to patch repodata to add the upper bound though.

**Comment by CJ-Wright** [comment]
Are you certain, what if some packages were built with an older version of `arrow`? Wouldn't they expect the wrong symbols?

**Comment by isuruf** [comment]
If they were, they are already broken when 0.15 was released.

**Comment by CJ-Wright** [comment]
Yes, and we should fix them by rebuilding them.

**Comment by isuruf** [comment]
I take my last comment back. Since `arrow-cpp` had `run_exports` none of them would have broken pinning.

**Comment by CJ-Wright** [comment]
@jakirkham btw this is why I asked if we had more than one version for the other pin that went in recently, if we did then we'd need to make certain that all downstream packages were built with the pinned version.

**Comment by CJ-Wright** [comment]
> Since arrow-cpp had run_exports none of them would have broken pinning.

Is that true for packages built before the `run_exports` was installed?

**Comment by isuruf** [comment]
Nope. Can somebody figure out the packages without an upper bound? We should mark them as broken.

**Comment by CJ-Wright** [comment]
Do we also need to rebuild them? Otherwise we may not have a modern version of those packages.

**Comment by isuruf** [comment]
Yes, they need to be rebuilt, but first let's first figure out if there are any.

**Comment by CJ-Wright** [comment]
Sure, I'm thinking of solidifying this into some policy/workflow around adding `run_exports` and when migrations are needed.

**Comment by isuruf** [comment]
Thanks @CJ-Wright. I agree that they need to be rebuilt, but rebuilding without fixing the repodata (or marking them broken) is asking for trouble.

**Comment by CJ-Wright** [comment]
Ah, but even with `run_exports` pinning their version to `x.x` that doesn't mean that a `0.15` linked package is available, right? If the package was build right after the `run_exports` went in then it would still be linked against `0.11.1`. This would result in solve failures, since we can't link against `0.15` and `0.11.1` at the same time, right?

**Comment by isuruf** [comment]
Yes, but you can look at the metadata and figure out which arrow-cpp version that package was built with and add the correct upper bound.

**Comment by CJ-Wright** [comment]
That isn't my point, I understand that in the time before `run_exports` the metadata is wrong. 

Maybe this is a more philosophical question about what the pinnings mean. My understanding is that when we pin a package, or move a pin we are saying that "This is the version that we will support. All packages that link against this package will be made available with a build that links against this version". That way users can be certain that so long as they use `arrow 0.15` they can install against that and their software will work.

For instance a package built against `arrow 0.14` with `run_exports` will be known not to be compatible with things built against `arrow 0.15` since the bounds say so. But that doesn't mean that we will have a `arrow 0.15` build automatically. We may have a build if the feedstock was rerendered as part of a version bump or by a request, but we can't say for certain if it will exist. That means that if any package that links to `arrow` and `package that links to arrow` wants to build against `arrow 0.15` (which is the sanctioned arrow version) will first need to rebuild `package that links to arrow` to get a compatible solve.

**Comment by isuruf** [comment]
Makes sense.

**Comment by CJ-Wright** [comment]
@jakirkham don't worry about not putting this in. I really wanted to have the discussion about what pins mean and this seemed like a good venue.

**Comment by CJ-Wright** [comment]
@beckermr for viz. I think this discussion also goes to your backpinning question/issue.

**Comment by jakirkham** [comment]
> I really wanted to have the discussion about what pins mean and this seemed like a good venue.

@CJ-Wright, thanks for doing that. 🙂

**Pull request merged**
