### PR TITLE
FFTW

### PR DESCRIPTION
**Pull request by isuruf**
This doesn't need a migration. What it needs is a PR to https://github.com/conda-forge/conda-forge-repodata-patches-feedstock to add an upper bound of version 4.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/core this needs to be merged before 3:05 to prevent a migration from starting.

**Comment by isuruf** [comment]
There was no version number bump in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/304 right?

**Comment by CJ-Wright** [comment]
Correct, why?

**Comment by isuruf** [comment]
If there's no new release, the bot will not pick it up right?

**Comment by CJ-Wright** [comment]
No CFEP9 was built so that the bot does the migration before the changes go into the global pins. The bot now looks at the migrations directory to find the migrations it needs to run.

**Comment by isuruf** [comment]
Ah, I thought the bot would look at the migrations in the built package and not the migrations folder in master of this github repo.

**Comment by beckermr** [comment]
We got 10 minutes! Go go go!

**Comment by beckermr** [comment]
(j/k clearly)

**Comment by CJ-Wright** [comment]
FYI, the bot goes slow for the first two hours (2 PRs then 5 PRs) after that it goes much faster.

**Comment by isuruf** [comment]
Since @beckermr (original author) is fine with it, I'm merging this.

**Comment by isuruf** [comment]
@beckermr, can you send a PR to conda-forge-repodata-patches-feedstock to add an upper bound of 4.0.0.a0 for any unpinned FFTW deps?

**Comment by beckermr** [comment]
I can but not today. Let's make an issue and tag me on it. I'll finish it later since this is my thing.

**Pull request merged**
