### PR TITLE
Add ntl migration

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge/bot Is there a reason we did not issue this one automagically?

**Comment by CJ-Wright** [comment]
It doesn't have a `max_pin` https://github.com/conda-forge/ntl-feedstock/blob/master/recipe/meta.yaml#L17

**Comment by beckermr** [comment]
Ahhhh. We should handle this case maybe?

**Comment by CJ-Wright** [comment]
How? We don't know what level of pinning it has.

**Pull request merged**
