### PR TITLE
Request Linux aarch64 migration for `openmp`

### PR DESCRIPTION
**Pull request by martin-g**
Needed by Bioconda/spades (https://github.com/bioconda/bioconda-recipes/pull/46731)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
This is wrong. `openmp` has been living in `llvm-openmp` for a long time, which is available for all platforms - the bioconda recipe needs to move on. If you want GCC's implementation, use `libgomp`.

**Comment by martin-g** [comment]
Thanks for the explanation, @h-vetinari !
I will send a new PR to revert this change!

**Comment by martin-g** [comment]
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5687

**Comment by h-vetinari** [comment]
It's not wrong to the point of needing a revert, just wrong in the sense that it won't do what you expect. The openmp feedstock (which produces the `llvm-openmp` output) is already producing aarch builds.

**Comment by martin-g** [comment]
Bioconda indeed uses `libgomp` for Linux and `llvm-openmp` for Mac. So, I don't really need `openmp` for `linux-aarch64` anymore.
To avoid more confusion I'd suggest to revert the change (#5687) but if you think there is no need to revert then please close the PR!

**Pull request merged**
