### PR TITLE
use datetime for version as current when built

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by msarahan** [comment]
this won't work without CB3.  Failures are expected until that's rolled out.

**Comment by isuruf** [comment]
Does the new linter work with this? If not, we should fix that. Not in a hurry though

**Comment by msarahan** [comment]
looks like no:

```
conda-smithy recipe-lint recipe
Traceback (most recent call last):
  File "/Users/msarahan/miniconda3/bin/conda-smithy", line 11, in <module>
    load_entry_point('conda-smithy', 'console_scripts', 'conda-smithy')()
  File "/Users/msarahan/code/conda-smithy/conda_smithy/cli.py", line 251, in main
    args.subcommand_func(args)
  File "/Users/msarahan/code/conda-smithy/conda_smithy/cli.py", line 209, in __call__
    lint = lint_recipe.main(os.path.join(recipe), conda_forge=args.conda_forge)
  File "/Users/msarahan/code/conda-smithy/conda_smithy/lint_recipe.py", line 389, in main
    content = env.from_string(''.join(fh)).render(os=os)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'today'
```

This one should be easy to fix - just need to use datetime in the stubbed jinja2 env, which should not be a problem since it is a built-in.

**Comment by jakirkham** [comment]
To recap my understanding of a discussion @msarahan and I had offline, our thinking is we don't always want to do a release of this package following a pinning change. Reason being we want some control of when pinning changes are rolled out to feedstocks that is independent of accepting such changes here.

**Comment by msarahan** [comment]
Yes, this PR should be closed.  We want to make it a requirement that version number changes be their own PR as part of the release cycle.  Other PRs will trigger builds, but these will be ignored for upload since the build string will not change and the files will already exist.

Closing this PR.

**Pull request closed without merging**
