### PR TITLE
Add migration to loosen proj pin to 'x.x'

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

See https://github.com/conda-forge/proj.4-feedstock/pull/145

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge/proj-4, this PR is to loosen the pin for proj, following https://github.com/conda-forge/proj.4-feedstock/pull/145.  Please comment if you have concerns.

I think it's necessary to close the current 9.4.0 migration (mostly stuck on vtk, which isn't getting much love lately, see https://conda-forge.org/status/migration/proj940).  I expect that the new migration will cover any packages that haven't already migrated.

**Comment by xylar** [comment]
Thanks @hmaarrfk!!

**Comment by hmaarrfk** [comment]
we could have also repo-data patched, but i hate patching, but you can ask chatgpt help you write patches in the future.

**Comment by xylar** [comment]
Oh, good point.  We could still do the patch, I suppose.  I'm happy to write one if it turns out to be necessary.  I think the migration should be easy enough.

**Comment by hmaarrfk** [comment]
the `proj` migrations have always been slow.... lets see how far this goes. but i'm happy to close one for the other!

**Pull request merged**
