### PR TITLE
Pin glog globally

### PR DESCRIPTION
**Pull request by xhochy**
As the `glog` ABI is not stable and we are running into problems like https://github.com/conda-forge/pyarrow-feedstock/issues/74, we should introduce a global pinning of `glog`.

cc @jakirkham 

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Added a `run_exports` at https://github.com/conda-forge/glog-feedstock/pull/17

**Comment by xhochy** [comment]
Opened a migrator PR: https://github.com/regro/cf-scripts/pull/506

**Comment by jakirkham** [comment]
Thanks @xhochy. I think we need an `x.x` line for `glog`’s `max_pin` as well. Also linking [the ABI/API report]( https://abi-laboratory.pro/index.php?view=timeline&l=glog ) for details.

**Comment by xhochy** [comment]
@jakirkham Do we really need this as I have added a `run_exports` to `glog`?

**Comment by jakirkham** [comment]
I may have missed that. In that case it shouldn't be needed.

**Pull request merged**
