### PR TITLE
Bump graphviz pin to 2.46 on win and osx-arm64

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nehaljwani** [comment]
cc @conda-forge/graphviz

**Comment by CJ-Wright** [comment]
Are those still  compatible with the existing ABI pin or do we need a migration?

**Comment by nehaljwani** [comment]
@CJ-Wright I'm not entirely sure, my primary purpose for this is updates of packages which use the graphviz libs.

Hasn't been updated here yet: https://abi-laboratory.pro/index.php?view=timeline&l=graphviz

**Comment by jakirkham** [comment]
Also Nehal opened issue ( https://github.com/lvc/upstream-tracker/issues/90 ) to request an update

**Comment by jakirkham** [comment]
> @CJ-Wright I'm not entirely sure, my primary purpose for this is updates of packages which use the graphviz libs on Windows.
> 
> Hasn't been updated here yet: https://abi-laboratory.pro/index.php?view=timeline&l=graphviz

This has since been updated. Not too many issues, but there were a couple symbol removals. We did miss a few version updates as well though. WDYT? 🙂

The main thing would want to do is ensure that packages that were avoiding `graphviz` on Windows or not building on Windows because of it now get built

**Comment by nehaljwani** [comment]
I've updated the PR to restrict the bump to win and osx-arm64.

**Pull request merged**
