### PR TITLE
add argon2-cffi to arch rebuild

### PR DESCRIPTION
**Pull request by jjhelmus**
argon2-cffi is a new dependency of notebook.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Is this the package name, or the feedstock name? It looks like the feedstock is underscored:
```
argon2_cffi
      ^
```

**Comment by beckermr** [comment]
feedstock I bet - probs need fixing if not

**Comment by bollwyvl** [comment]
better? 
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/719

**Comment by jjhelmus** [comment]
Thanks for the fix @bollwyvl and @beckermr

**Comment by bollwyvl** [comment]
Hooray!

Might be a good thing to lint, if possible... This repo is dark magic to me
though, wouldn't know where to start...

**Pull request merged**
