### PR TITLE
add pins needed for the linux-armv7l platform

### PR DESCRIPTION
**Pull request by jjhelmus**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scopatz** [comment]
This seems reasonable to me.  Is there any reason not to merge it?

**Comment by xhochy** [comment]
Also looks fine to me. I think the only open item will be how the migrator shall look but that is something to be discussed in https://github.com/regro/cf-scripts

**Comment by CJ-Wright** [comment]
@xhochy can you open an issue on cf-scripts? I think we can reuse the existing arch migration things, and maybe bump the object number? This would cause a restart of the entire arch rebuild, which I presume would then catch the new arch @mariusvniekerk what do you think?

**Comment by jjhelmus** [comment]
> I think we can reuse the existing arch migration things, and maybe bump the object number?

Why not create a new migrator for `armv7l`?  The aarch64 + ppc64le migration is nearly complete and it seems wasteful to rebuild everything just to add `armv7l`

**Comment by scopatz** [comment]
I think this is probably also a separate migrator. It is a separate platform. In any event, that discussion  shouldn't block this.

**Pull request merged**
