### PR TITLE
[WIP] relax glib pinning

### PR DESCRIPTION
**Pull request by hmaarrfk**
closes https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/1026
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by xhochy — CHANGES_REQUESTED** [review]
I think we should have 2.66 in here.

**Comment by xhochy** [comment]
@isuruf Waiting for your opinion here but I would prefer to have 2.66 in the migrator as this already has the glib/libglib split.

I'm fine though to have 2 as the pinning once the migrator has passed.

**Comment by hmaarrfk** [comment]
I was going to add a greater than constraint.  Would that be ok?

**Comment by hmaarrfk** [comment]
@xhochy pinning changed.

**Comment by hmaarrfk** [comment]
I think this might need more work too.

**Review by isuruf — APPROVED** [review]

**Review by xhochy — APPROVED** [review]

**Pull request merged**
