### PR TITLE
Add pinning for libsecret

### LINKED ISSUE #88: Pinning libsecret
Would be good to pin `libsecret`. Looks like 0.18 up is ok, but things break on minor versions.

cc @nehaljwani

ref: https://abi-laboratory.pro/?view=timeline&l=libsecret

### PR DESCRIPTION
**Pull request by nehaljwani**
Fixes #88

xref: https://github.com/conda-forge/staged-recipes/pull/4858

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [?] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
I force-pushed away your version bump; the date is now outdated, which is why we generally prefer not to include version bumps here and instead do occasional releases separately.

Seems reasonable to me, though note that we don't actually have `libsecret` yet (it's in the mentioned https://github.com/conda-forge/staged-recipes/pull/4858).

**Comment by jakirkham** [comment]
Can you please add a line in `pin_run_as_build` with the appropriate `max_pin`?

**Comment by nehaljwani** [comment]
Added

**Comment by isuruf** [comment]
For new packages, `pin_run_as_build` should not be added and `run_exports` should be added to the package.

**Comment by nehaljwani** [comment]
Oh man, please form a consensus! I keep going back and forth :crying_cat_face: 
https://github.com/conda-forge/staged-recipes/pull/4858#discussion_r204076032

**Comment by dougalsutherland** [comment]
I just merged https://github.com/conda-forge/staged-recipes/pull/4858, with `run_exports`. Do we want a duplicate `pin_run_as_build` or just stick to `run_exports`?

**Comment by nehaljwani** [comment]
I dropped the `pin_run_as_build` section for libsecret.

**Pull request merged**
