### PR TITLE
Add openai to osx-arm64

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Bastian! 😄

Do you want to add this to the arch migration as well? 🙂

**Comment by BastianZim** [comment]
Thanks @jakirkham! 😄

Sure, will do that just now! Any other place I should add this?

Short question though, the bot opened multiple PRs, can I merge all of them at the same time or will there be some sort of conflict (Some of them have the same build number)?

**Comment by jakirkham** [comment]
Yep, that's the right place

The bot will close and resubmit any PRs with conflicts. Though maybe that is already clear now

**Comment by BastianZim** [comment]
Has been added, thanks for the heads-up @jakirkham! 

> The bot will close and resubmit any PRs with conflicts. Though maybe that is already clear now

Yes, has all worked out, fortunately 😄 

The package is pretty much noarch except for two small problems (https://github.com/conda-forge/staged-recipes/pull/13837#issuecomment-775475258) so let me know if I should add this anywhere else to get as close as possible to it being noarch.

**Comment by jakirkham** [comment]
Thanks merged that

Yeah no worries. `noarch` is great when it works, but is a little too narrow to catch some cases unfortunately.

Nope I think that should be it. Thanks for these PRs and adding this package 😄

**Comment by BastianZim** [comment]
Perfect, thank you! 

Yeah at least some sort of middle ground where a version is built for each python3.6 to 3.9, but not for each OS would be great since I've had cases where packages needed to have extra dependencies for lower python versions and were otherwise noarch. Any place to file a feature request for that? 😄 

Awesome, no worries always happy to help!

**Comment by jakirkham** [comment]
Yeah unfortunately Python 3.6 has been dropped. So not too much we can do there.

We are working on getting Python 3.9 rolled out through a migrator. So should see a PR eventually (though that relies on dependencies being migrated first).

**Comment by BastianZim** [comment]
Ahh, yeah that does make it a bit difficult... 😄

I think I’ve had some of them target my feedstocks already, great stuff! Makes it really easy!

**Comment by jakirkham** [comment]
That said, some people have started exploring other ways to do `noarch`. Here's an example [on Unix]( https://github.com/conda-forge/bpytop-feedstock/blob/18b5df21bdc3fb3cf2af6f2cca2365f7e746d590/recipe/meta.yaml#L28-L29 ). So this might be something worth exploring for your use case. If that works, it would be great to include this in the conda-forge docs

**Comment by BastianZim** [comment]
Hmm that seems interesting! 🤔 I’ll have a look at it later and see if I can somehow incorporate that. Thanks!

**Pull request merged**
