### PR TITLE
Always use cos7 based docker image by default on linux-64

### PR DESCRIPTION
**Pull request by chrisburr**
Implements the proposed solution in https://github.com/conda-forge/conda-forge.github.io/issues/1436#issuecomment-980075683

This allows all recipes to be built in a CentOS 7 container (minimising the solver issues for dependencies requiring CentOS 7's glibc) while still allowing recipes to link against the CentOS 6 based sysroot (maximsing compatibility). See the linked thread for details.

### CODE REVIEW

**Review by mbargull — APPROVED** [review]
+1 from my side.
I think the comments in https://github.com/conda-forge/conda-forge.github.io/issues/1436 addressed the consequences/advantages well, but let's give this a quick discussion in tomorrow's core meeting to get everyone in the loop.

**Comment by beckermr** [comment]
We should remove the cos6 build on stages recipes too maybe.

**Review by isuruf — APPROVED** [review]

**Comment by beckermr** [comment]
Let's make an announcement for this one. I can compose it tomorrow or maybe later tonight.

**Comment by beckermr** [comment]
announcement done: https://github.com/conda-forge/conda-forge.github.io/pull/1571

**Comment by beckermr** [comment]
merging!

**Pull request merged**
