### PR TITLE
restart py39, note that this will rerun entire migration

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by isuruf** [comment]
Please wait until https://github.com/conda-forge/python-feedstock/pull/397 is in

**Comment by mariusvniekerk** [comment]
Additionally https://github.com/conda-forge/python_abi-feedstock has to have a successful build for osx.

**Comment by jakirkham** [comment]
Maybe we should take some notes so that our future selves can revisit this next year.

**Comment by mariusvniekerk** [comment]
Yeah python is quite special indeed.....

**Comment by ocefpaf** [comment]
Yeah, so far we had ~9 people struggling to remember bits and pieces for this build.

**Review by mbargull — APPROVED** [review]
New `python` and `python_abi` builds are up.

**Comment by beckermr** [comment]
The bot is down anyways.

**Pull request merged**
