### PR TITLE
move openssl pin

### PR DESCRIPTION
**Pull request by CJ-Wright**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/core I'm not certain what to do with the version number. Also this needs to be coordinated with the openssl rebuild migration.

**Comment by scopatz** [comment]
> I'm not certain what to do with the version number

bump the build number

**Comment by CJ-Wright** [comment]
That's so sensible, why didn't I think of that :sheep:

**Comment by CJ-Wright** [comment]
@conda-forge/core

**Comment by CJ-Wright** [comment]
I guess this means the openssl migration can begin

**Comment by jjhelmus** [comment]
Was the specific version number, `1.1.1a` intentional?  Pinning to the looser `1.1.1` would allow for builds against newer versions of OpenSSL (e.g. 1.1.1b) which are compatible with 1.1.1a

**Comment by isuruf** [comment]
For that to work you need `min_pin` defined

**Pull request merged**
