### PR TITLE
Add cuda_compiler_version_min convenience variable

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
This makes it easier to skip other cuda versions when we don't need to build for various cuda versions.

**Comment by jakirkham** [comment]
Thanks Isuru! 😄

This seems like a useful addition.

So is the idea maintainers would use this in their recipes or is there other tooling that would use this as well?

**Comment by isuruf** [comment]
They'll use this in the recipes.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
cc @kkraus14 @leofang (for awareness)

**Review by kkraus14 — APPROVED** [review]

**Comment by isuruf** [comment]
Thanks for the reviews

**Pull request merged**
