### PR TITLE
remove r-base 3.6 for osx-arm64

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by beckermr — COMMENTED** [review]
This probably needs an announcement.

**Comment by isuruf** [comment]
Why?

**Comment by beckermr** [comment]
We're removing a major version of a significant piece of software. People should be aware.

**Comment by isuruf** [comment]
we are not removing anything. Just not adding 3.6 support to the new platform `osx-arm64`

**Review by mbargull — APPROVED** [review]
LGTM
(I slightly adjusted the title to hopefully clear up any confusion).

**Comment by beckermr** [comment]
Ohhhhh! Sorry! I misunderstood the PR.  LGTM!

**Comment by isuruf** [comment]
Ah, I didn't realize the title was confusing. Thanks @mbargull and @beckermr for review

**Pull request merged**
