### PR TITLE
Add migration to zstd 1.4.3

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Adding the file is enough, I don't need to bump the build version?

**Comment by CJ-Wright** [comment]
This looks great! Thank you very much!

**Comment by CJ-Wright** [comment]
@conda-forge/core ready for review. This migration will impact 8 packages.

**Comment by CJ-Wright** [comment]
Thank you very much!

**Pull request merged**
