### PR TITLE
migrate to geos 3.8.0

### PR DESCRIPTION
**Pull request by ocefpaf**
Let's give this one a shot.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks!

**Comment by xylar** [comment]
For some reason `libgdal` wasn't flagged by the bot in this migrator, see: https://conda-forge.org/status/ 

Anyone know why not?  I'll try to take care of it manually.

**Comment by xylar** [comment]
Sorry, I see now.  It has been archived.

**Comment by xylar** [comment]
So it still seems like there's a slight problem with the bot.  https://github.com/conda-forge/postgis-feedstock/pull/35 was triggered even though libgdal hasn't yet been rebuild by https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/meta.yaml#L70

In other words, the bot seems to be unaware of or otherwise to be mishandling subpackages.

**Comment by ocefpaf** [comment]
We had some issues with multiple outputs before. I thought it was resolved but maybe we need t re-visit this issue. I'll investigate a little bit.

**Pull request merged**
