### PR TITLE
Pin p11-kit at 0.23.21

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
This stuff always hurts my head. Because now you need to babysit every build to ensure that it picked up the right build number.

I'm not sure if we should mark the older builds as broken.

**Comment by leofang** [comment]
I am not sure I follow, Mark. My understanding is once this migrator is merged, the bot will rebuilt all packages that depend on `p11-kit`, and then once the rebuild is done we're good. Why do we need to mark all old packages broken? I haven't seen such things done in the past.

**Comment by hmaarrfk** [comment]
you added the run_exports to the latest build. There is no guarantee the solver will find it. It may take a few hours for it to propagate. 

So you might get build `3` which doesn't have the run exports, and sometimes you will get build `4` which does.

**Comment by leofang** [comment]
We can't be always "past compatible" right? This is to ensure we fix things properly to the future and do not look back unless there are serious issues.

I am doing this PR mainly with the same concern in mind. The bot may issue p11 0.24.0 PR anytime, and I want to get the pinning done before the new version is merged. Otherwise, once the new version is out and we still don't have the right pinning, things get worse (than they are now, as 0.23 has been around for years.

**Comment by hmaarrfk** [comment]
ok. lets rebuild. but you might also want to add a repo-data patch to add the max pin to 0.23 for previous builds.

**Comment by leofang** [comment]
Will do, thanks Mark, though I'd likely need your help for the repodata patch 😉

**Pull request merged**
