### PR TITLE
Pause Python 3.11 migration

### PR DESCRIPTION
**Pull request by mbargull**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

~~Queue length is lower than 100 now.
Let's increase PR limit to 10 for now and if needed increase to max. 20 later.~~
Queue length is over 700 now. Let's pause for now.

### CODE REVIEW

**Comment by jakirkham** [comment]
It seems things are moving through CI at a decent clip. This PR ( https://github.com/conda-forge/pycosat-feedstock/pull/29 ) was opened ~1hr ago and was merged ~10mins ago. So ~50mins in total. Think we can let a few PRs through

**Comment by h-vetinari** [comment]
I may not have access to the same tools/dashboards you do, but I'd still wait a bit. As an indicative example, https://github.com/conda-forge/libprotobuf-feedstock/pull/137 had to wait ~35min for CI resources.

**Comment by mbargull** [comment]
Half an hour ago we still had queue times of above 1hr for some jobs. Now it's about 20min. Unpausing in gh-3592.

**Comment by jakirkham** [comment]
The queue length has continued to shrink. Looks like one feedstock with a several jobs queued (it has a couple running too). Think keeping a low number of migration PRs for the moment is probably sufficient for now.

After we get a few more packages built we may want to increase it slightly as there will be a bunch of packages with a small amount of compiled code (Cython, pybind11, etc.) that build relatively quickly. So we will be waiting on the bot to generate more as opposed to waiting for CI time.

**Pull request merged**
