### PR TITLE
Drop pypy3.6 because it has reached EOL

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@mattip, thoughts?

**Comment by mattip** [comment]
I am in favor. The PyPy team does not intend on making another pypy3.6 release, in fact we already dropped it from the recent 7.3.4 release and 7.3.5 bugfix release. Do we need to do anything with the [pypy-meta-feedstock](https://github.com/conda-forge/pypy-meta-feedstock)? 

Tangentially related: would it be possible to rename the [pypy3.6-feedstock](https://github.com/conda-forge/pypy3.6-feedstock) to pypy-feedstock? I think github makes the old name redirect to the new one for a while.

**Comment by isuruf** [comment]
> Do we need to do anything with the pypy-meta-feedstock?

Nope.

**Comment by isuruf** [comment]
> Tangentially related: would it be possible to rename the pypy3.6-feedstock to pypy-feedstock? I think github makes the old name redirect to the new one for a while.

We can't rename feedstocks because it would break a lot of automation stuff. We can create a new feedstock.

**Review by xhochy — APPROVED** [review]
Should we also close all open PRs?

**Review by chrisburr — APPROVED** [review]
Yeah closing the existing PRs after this is merged seems like a good idea to me. Looks like there are currently 454: https://github.com/search?p=1&q=org%3Aconda-forge+%22Rebuild+for+pypy%22+in%3Atitle+author%3Aregro-cf-autotick-bot+state%3Aopen+type%3Apr&type=Issues

Is there already a bulk way of doing this? Or should I write a quick script that uses the API?

**Comment by beckermr** [comment]
> Is there already a bulk way of doing this? Or should I write a quick script that uses the API?

You could add the code you need to the admin-migrations repo and it would do it for you, but there is not a pre-canned close all the PRs button. OTOH if you write one into the admin-migrations repo then we can use it later too.

**Pull request merged**
