### PR TITLE
Add more to the CUDA arch migration

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Are you adding all cuda feedstocks to the aarch64/ppc64le migrator?
Consensus in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2436 was that we should add only feedstocks that you need.

**Comment by jakirkham** [comment]
What I've noticed with the CUDA arch migrator (and maybe we should discuss this in a new issue), is it seems to be migrating all CUDA packages regardless of whether they are in this list. For example ( https://github.com/conda-forge/cudadecon-feedstock/pull/11 ). The result is it adds the files necessary to build CUDA packages on other archs, but doesn't actually enable the builds. Even though we have [`wait_for_migrators`]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/308eeffd25c69866b5883a5fd8e920b57f8001eb/recipe/migrations/cuda_112_ppc64le_aarch64.yaml#L15-L16 ), it isn't really waiting. 

Now admittedly I'm not sure the right way to solve it and this may not be it. Admittedly one answer might be do nothing since adding the additional migration files doesn't break anything and if we do intend to do arch migration the functionality is there. Though if that is the case, maybe we should consolidate this migrator with other the CUDA migrator and drop `wait_for_migrators`. Another option is to add the packages to the arch migrator ahead of time so we don't get these CUDA arch migrator PRs that are not really doing anything, but as you note this is opting more packages into arch migration than we may really want to add. Perhaps a different approach is we do some debugging in `cf-scripts` to figure out why this is happening and fix it and/or move some of the CUDA arch migrator logic into the arch migrator there.

Personally don't have any strong feelings on any of these options and am ok cutting this list down to a subset, but I think it would be good to come up with some solution since the current behavior is a bit confusing.

**Comment by isuruf** [comment]
>  Perhaps a different approach is we do some debugging in cf-scripts to figure out why this is happening and fix it and/or move some of the CUDA arch migrator logic into the arch migrator there.

This seems like the best option.

**Comment by jakirkham** [comment]
Agree though I don't really know that codebase well enough to do that.

Am ok trimming back this list in the interim though.

**Comment by isuruf** [comment]
https://github.com/conda-forge/cudadecon-feedstock/pull/11 was sent before I fixed the issue in https://github.com/regro/cf-scripts/pull/1517

**Comment by jakirkham** [comment]
Ah ok. Thanks for point that out.

Though it is worth noting the packages here came from the "Awaiting Parents" list under the CUDA arch migrator. So not sure why those are showing up then (unless they are coming from things already in the list or we still have another issue)

**Comment by isuruf** [comment]
That's a labeling issue and you can ignore that. (Awaiting Parents include awaiting the normal arch migrator)

**Comment by isuruf** [comment]
If you agree, can you remove any feedstocks you don't need that you added here?

**Comment by jakirkham** [comment]
Ok if glad to hear that is a non-issue. Sorry for the confusion.

Yeah I've been working on that background. Should have a PR in a moment.

**Comment by jakirkham** [comment]
What should we do about the one's marked "Done" that did not go through regular arch migration, but did go through CUDA migration?

**Comment by isuruf** [comment]
Either delete https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/cudadecon.json#L117-L135 and similar
or restart the migration.

**Comment by jakirkham** [comment]
Ok starting with trimming the list. Submitted PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2700 ).

Will take a look at node removal as that seems less disruptive. Though may not get to that tonight.

**Comment by jakirkham** [comment]
Went through and deleted the CUDA arch migration from the nodes that were marked done, but did not undergo the arch migration first. Have submitted these changes in PR ( https://github.com/regro/cf-graph-countyfair/pull/41 ).

**Pull request merged**
