### PR TITLE
Drop PyPy 3.8

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc @conda-forge/pypy3-6

### CODE REVIEW

**Review by beckermr — APPROVED** [review]

**Comment by mattip** [comment]
Is conda-forge planning on dropping 3.8 across the board soon? I seen to remember dropping PyPy3.7 before CPython3.7 caused some friction somewhere.

**Comment by mattip** [comment]
Maybe the problem was in mambaforge-pypy3, but I see that uses pypy3.9 now.

**Comment by jakirkham** [comment]
Interesting would have proposed dropping Python 3.8 in early October when Python 3.12 comes out. There's already a bunch of projects that dropped Python 3.8

**Comment by h-vetinari** [comment]
The thing is that upstream PyPy already dropped 3.8 with its latest release, so we'll get fixes applied inconsistently (e.g. 3.9 will have them, 3.8 won't), and that'll likely cause some extra friction. That said, I'm also fin to wait until October 🤷

**Review by h-vetinari — APPROVED** [review]

**Comment by isuruf** [comment]
@mattip, are you okay with merging?

Let's move the discussion about CPython to somewhere else. The difference is that CPython 3.8 is still supported, but PyPy3.8 has reached EOL already.

**Comment by jakirkham** [comment]
Sure we can drop it. Didn't realize it was EOL

**Comment by mattip** [comment]
Seems reasonable.

**Pull request merged**
