### PR TITLE
update to occt 7.4

### PR DESCRIPTION
**Pull request by looooo**
It would be nice to have a migration for this one. @CJ-Wright 

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@CJ-Wright thanks for your help. After crossing cfep9 I remembered this PR. Not sure if I have understood all, but I guess this one should replace occt7.3 with occt7.4. Maybe you can have a look at it.

**Comment by CJ-Wright** [comment]
This looks great! Please give us some time to get this in. The python 3.8 migration is all consuming at the moment (and some fixes need to make their way to the bot to run other migrations).

**Comment by looooo** [comment]
No rush. Merge whenever it makes the most sense.

**Comment by looooo** [comment]
This migration is stopped by smesh-feedstock which needs a version update and this won't happen soon. So somehow I would like to stick with occt7.3 until this is possible. Can we somehow postpone this migration and do it once smesh works with occt7.4?

**Comment by CJ-Wright** [comment]
We can just leave it open. The migration doesn't change the global pins until we explicitly close out the migration.

**Comment by looooo** [comment]
Good to know! I hope more people will try to get smesh ready for occt7.4. But currently, the situation doesn't look very promising. So I guess we need several months to get this job done.

**Pull request merged**
