### PR TITLE
Migrate `astroid`

### PR DESCRIPTION
**Pull request by jakirkham**
Guess we were missing this one even though it is a `pylint` dependency 🤷‍♂

cc @nerohmot

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Yeah we need to fix the graph a little bit.

**Comment by jakirkham** [comment]
I'm guessing this is because we are not looking at dependencies of `noarch` packages. Is that right or is this a different issue?

**Comment by CJ-Wright** [comment]
Not certain, we pluck `noarch` pacakges, which removes them from the graph but should preserve their edges. We may not be doing that properly. There also could be other errors in the filtering logic.

Relevant bits: 
https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/auto_tick.py#L295
https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/arch.py#L39

Update:
I think I found some of the issues
1. I think we can remove https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/auto_tick.py#L306 since this might be handled by the init
2. https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/arch.py#L65 most likely should be pluck and should include the noarch condition.

@mariusvniekerk what do you think?

**Comment by CJ-Wright** [comment]
This is in there it's awaiting wrapt

**Comment by jakirkham** [comment]
Good catch! Thanks CJ 😄

I must have looked into that before as I asked the bot to re-run the migration on PR ( https://github.com/conda-forge/wrapt-feedstock/pull/14 ), but it hasn't happened yet. Guessing this is due to the same known issue; more motivation for this work ( https://github.com/conda-forge/conda-forge-webservices/issues/289 ) it seems 🙂

**Comment by scopatz** [comment]
This has conflicts now

**Comment by CJ-Wright** [comment]
I think this can be closed?

**Comment by jakirkham** [comment]
IIUC @CJ-Wright we can just close this. Is that right?

**Comment by jakirkham** [comment]
Actually completely missed PR ( https://github.com/conda-forge/astroid-feedstock/pull/36 ) is already here to migrate `astroid`. Closing this out. Thanks all! 😄

**Pull request closed without merging**
