### PR TITLE
Disable python 2.7 for ppc64le and aarch64

### PR DESCRIPTION
**Pull request by hmaarrfk**
We didn't build scipy for python 2.7
It seems that we are running the clock on 2019 anyway. 
Marius would have called this back in 2018 when we started this project ;)

cc: @mariusvniekerk 
@conda-forge/arm-arch 

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Yeah we are finding ourselves more often than not needing to drop Python 2.7 for these architectures manually anyways.

Thoughts @conda-forge/core?

**Comment by jjhelmus** [comment]
Is it worth dropping Python 2.7 from these platforms when in two months Python 2 is going to be dropped for all platforms?  I do not have a strong opinion either way but think it is worth consideration.

**Comment by jakirkham** [comment]
> Is it worth dropping Python 2.7 from these platforms when in two months Python 2 is going to be dropped for all platforms?

I think the challenge is people are having to go through and manually fix arch migrators to drop Python 2 and then wait for feedback from maintainers about whether this is ok. This would generally let people know we are ok with dropping Python 2.7 on the migrators.

> I think it is probably OK to stop building Python 2.7 for all platforms by default now. Folks can manually re-enable it if they need to.

Personally I wouldn't go quite that far. Though I definitely think we should drop it the day the Python core group does.

**Comment by CJ-Wright** [comment]
RE: the migrators
We could update the migration code to drop py2.7 going forward. Then maintainers can ask for a bot-rerun and they should get the py2.7 drop in the new PR.

**Comment by hmaarrfk** [comment]
> We could update the migration code to drop py2.7 going forward. Then maintainers can ask for a bot-rerun and they should get the py2.7 drop in the new PR.

This is what this PR proposes right?

**Comment by CJ-Wright** [comment]
Yes, sorry I didn't read the source 🐑

**Comment by hmaarrfk** [comment]
To address jjhelmus question, I'm not too interested in making policy decisions at this stage, but. Aarch64 only built newer packages that mostly already dropped python 2.7. As such. There are real holes in the build matrix. This PR just avoids tedious fixes and back and forth.

**Comment by jakirkham** [comment]
> There are real holes in the build matrix. This PR just avoids tedious fixes and back and forth.

That was my understanding as well.

**Comment by mariusvniekerk** [comment]
yeah building py27 things for these arches is way more trouble than it is worth

**Pull request merged**
