### PR TITLE
Add qutip to osx arm64 migration list.

### PR DESCRIPTION
**Pull request by hodgestar**

### CODE REVIEW

**Comment by hodgestar** [comment]
@hmaarrfk Thank you for the superfast review and merge! :D

**Comment by hmaarrfk** [comment]
In the future, try to add it in some random place so that if any delays happen, a conflict isn't guaranteed

**Comment by hodgestar** [comment]
Will try to remember!

**Comment by hmaarrfk** [comment]
thanks!

**Pull request merged**
