### PR TITLE
Mark gcc 9.3.0 as done

### PR DESCRIPTION
**Pull request by isuruf**
My plan is to merge this in a week.

This migration was started on Oct 8 with an announcement and I hope those who wanted gcc 7.5 have added the gcc 7.5 requirement to their feedstocks by now.

cc @conda-forge/core

### CODE REVIEW

**Comment by beckermr** [comment]
Sounds good to me. Why not simply delete the gcc930 migration file?

**Comment by isuruf** [comment]
Wouldn't that delete the migration info from status page?

**Comment by beckermr** [comment]
Ah you wanted to leave it on that page. Sure! I figured since so little was left we could just remove it all together but am happy to leave it on the page for now too.

**Comment by mbargull** [comment]
> Wouldn't that delete the migration info from status page?

+1 on that question. I'd be nice if we can have it there for a few more weeks to get an overview of the status of the remaining PRs.

**Comment by beckermr** [comment]
Right. So even if we delete, I added a new feature to help with this. From now on any migration that is closed will remain on the status page for two weeks in the closed migrations section: https://conda-forge.org/status/#closed_migrations

**Comment by mbargull** [comment]
So many new features, hard to keep track of :D.

**Comment by beckermr** [comment]
One other feature you all might want to know about. The bot will now automatically issue a PR to close a migration after all PRs in that migration have been issued for at least a month. Note this is not merged, but just issued.

**Comment by isuruf** [comment]
This is ready and it has been a week

**Review by beckermr — CHANGES_REQUESTED** [review]
We need to check the windows cuda migration now too.

**Comment by isuruf** [comment]
I checked and there's no need

**Comment by beckermr** [comment]
Great! Thanks! LGTM!

**Review by beckermr — APPROVED** [review]

**Pull request merged**
