### PR TITLE
Add perl to osx-arm64 migration

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mbargull** [comment]
Perl has already been migrated (probably with Git or some other package that depends on it).
However, there is https://github.com/conda-forge/perl-feedstock/pull/49 which is still to be commented on/reviewed.

**Comment by xhochy** [comment]
> Perl has already been migrated (probably with Git or some other package that depends on it).
> However, there is [conda-forge/perl-feedstock#49](https://github.com/conda-forge/perl-feedstock/pull/49) which is still to be commented on/reviewed.

Ah, then I need to change the pinning for it on `osx-arm64`!

**Comment by mbargull** [comment]
If possible, we get https://github.com/conda-forge/perl-feedstock/pull/49 in and have a universal pinning then (ref. https://github.com/conda-forge/perl-feedstock/issues/48 https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/936#issuecomment-725351898 ). But AFAICT, no one has reviewed the proposed changes yet.

Out of interest, for which packages do you need it?

**Comment by xhochy** [comment]
> If possible, we get [conda-forge/perl-feedstock#49](https://github.com/conda-forge/perl-feedstock/pull/49) in and have a universal pinning then (ref. [conda-forge/perl-feedstock#48](https://github.com/conda-forge/perl-feedstock/issues/48) [#936 (comment)](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/936#issuecomment-725351898) ). But AFAICT, no one has reviewed the proposed changes yet.
> 
> Out of interest, for which packages do you need it?

I came across for it in `rsync`'s build requirements. I don't use it anywhere in my environments but it pops up quite often in build.

**Comment by mbargull** [comment]
Ah, if it's just build requirements, then you should just be able to just use `perl *` (or `perl >=appropriate_version`) to avoid pulling in unnecessary restrictions from the pinning (@isuruf did this already in a couple of places, ref https://github.com/conda-forge/perl-feedstock/issues/48#issuecomment-732159738).

**Pull request merged**
