### PR TITLE
Pin cudnn via run_export at 7.6.4

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

context:
- https://github.com/AnacondaRecipes/aggregate/issues/173#issuecomment-550072394
- https://github.com/conda-forge/cupy-feedstock/pull/18#discussion_r354670446

cc: @jakirkham

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by scopatz** [comment]
CC @jakirkham

**Comment by leofang** [comment]
@jakirkham Pinging you again in case the ball is dropped.

**Comment by jakirkham** [comment]
Thanks @leofang! 😄 Sorry for the delay 😞

**Comment by jakirkham** [comment]
Should add we need to bump the version for this to take effect. Though am hoping we can roll this into some other CUDA 10.2 related work to simplify things.

**Comment by leofang** [comment]
> Should add we need to bump the version for this to take effect.

@jakirkham Ah, so this has not become effective? Which line should I bump, for future reference?

**Pull request merged**
