### PR TITLE
Add VTK variants

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

In https://github.com/conda-forge/vtk-feedstock/pull/225 I added osmesa and egl variants of VTK.

I am not 100% this accomplishes what I want, but I would like to have packages that have `vtk` as a dependency and build variants themselves (https://github.com/conda-forge/occt-feedstock/pull/79/files) to automatically receive migration PRs.

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
Do we need a migration here instead of just adding them?

**Comment by isuruf** [comment]
Why? Downstream packages don't care about how VTK was compiled right?

**Comment by isuruf** [comment]
I was asking @basnijholt

**Comment by basnijholt** [comment]
> Downstream packages don't care about how VTK was compiled right?

That would be great, if that is true, then I can close
* https://github.com/conda-forge/pcl-feedstock/pull/40
* https://github.com/conda-forge/occt-feedstock/pull/79

@isuruf, are you sure? And how can I find out?

**Comment by isuruf** [comment]
> @isuruf, are you sure? And how can I find out?

Test the current builds of occt with the three vtk variants. Do they work?

**Comment by beckermr** [comment]
> I was asking @basnijholt

woops sorry!

**Comment by isuruf** [comment]
After chatting with @basnijholt, this is another XY problem. Closing

**Pull request closed without merging**
