### PR TITLE
Use root*-6.18.04

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This is the first (and currently only) version that provides the `root_base` and `root-binaries` outputs. 

cc @chrisburr

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@conda-forge/conda-forge-pinning, can someone please merge this?

**Comment by CJ-Wright** [comment]
Does this need rebuilds?

**Comment by duncanmmacleod** [comment]
@CJ-Wright, I don't think so, or at least if rebuilds are needed, they can be executed manually. @chrisburr can probably comment with more authority.

**Comment by chrisburr** [comment]
No, these pins were only added recently and should always have been for `6.18.04` version.

**Comment by duncanmmacleod** [comment]
Ping @conda-forge/conda-forge-pinning, can this be merged please?

**Pull request merged**
