### PR TITLE
Prepared OpenVINO 2024.5.0 migration

### PR DESCRIPTION
**Pull request by artanokhov**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by artanokhov** [comment]
@hmaarrfk could you please review?

**Comment by hmaarrfk** [comment]
Is the bot having trouble making these prs?  I would rather merge the bots tbh

**Comment by artanokhov** [comment]
> Is the bot having trouble making these prs? I would rather merge the bots tbh

I've created last ~3 PRs with the update, not sure how often the bot do the scans but seems like there is still no new PR for new openvino release pin

**Comment by hmaarrfk** [comment]
hmmmm. i wonder if there exists a log.

**Pull request merged**
