### PR TITLE
Bump to clang 16

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Split from https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4890

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]
Thanks Isuru! 🙏

**Review by xhochy — APPROVED** [review]
This is the simpler of the two compiler updates.

**Comment by jakirkham** [comment]
Yeah and that is why we chose just to do Clang 16 and defer on GCC 13 for a bit

**Review by h-vetinari — APPROVED** [review]
I'm fine with this either way. My impression is that clang 16 will be more disruptive than GCC 13 (partially explained in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4890), but in any case, I'm in favour of keeping our compilers up to date.

One more argument in favour of doing only clang is that GCC 12 still receives bugfixes, while clang 15 is dead (actually clang 16 has topped out at 16.0.6 as well, but at least that means it has "converged" to its final state).

**Comment by isuruf** [comment]
Thanks @h-vetinari for the PR and building clang-16

**Pull request merged**
