### PR TITLE
Update openturns pin

### PR DESCRIPTION
**Pull request by jschueller**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge/conda-forge-pinning good to merge ?

**Comment by jschueller** [comment]
thanks

**Comment by croth1** [comment]
Does this need a [migrator](http://conda-forge.org/docs/maintainer/pinning_deps.html#propagate-pin-changes-with-a-migrator)?

**Comment by jschueller** [comment]
no

**Pull request merged**
