### PR TITLE
Update gdk-pixbuf max pin

### PR DESCRIPTION
**Pull request by hmaarrfk**
Precursor to https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/627
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ryanvolz** [comment]
@conda-forge/core Would love to get this and/or #627 merged so that `gtk3` can use `gdk-pixbuf=2.42`, which does the proper thing by moving `gobject-introspection` to a build dependency.

**Comment by isuruf** [comment]
@ryanvolz, the correct thing to do is something like https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py#L569-L570 and then change the pinning to `x`

**Comment by ryanvolz** [comment]
Thanks for taking a look @isuruf. Let me see if I understand what you're proposing.
1) Patch the repodata to ensure that any existing packages depending on `gdk-pixbuf=2.36.12` (the current pin) have a loose dependency. Something like this?
```
if "gdk-pixbuf >=2.36.12,<2.36.13.0a0" in deps:
    _pin_looser(fn, record, "gdk-pixbuf", upper_bound="3.0a0")
```
2) Merge #627 should to update the pinning to `x` (2).

If I understand the repodata patching part correctly, then I don't think that will do anything since everything built against `gdk-pixbuf=2.36.12` will already have the `3.0a01` upper bound thanks to its `run_exports`. At least, that's what `gtk3`'s existing package metadata says.

Let me just summarize the current situation as I'm understanding it. `gdk-pixbuf` is pinned to `2.36.12` so that all builds use that version (unless locally overridden). Its `run_exports` has had a `max_pin` of `x` at least since `2.36.12`, which does not match conda-forge-pinning's `pin_run_as_build` which has a `max_pin` of `x.x.x`. At runtime, newer versions of `gdk-pixbuf` are installed because the `run_exports` is taking precedence in the package metadata, so any version up to 3.0 satisfies the dependency. Thus, I think it would be fine to just update the global pin to `2` and fix the `pin_run_as_build`, no migrator or repodata patching needed? That lets builds use the newest version and doesn't change any of the current runtime dependencies.

**Comment by isuruf** [comment]
Ah. I always thought `pin_run_as_build` took precedence. Apparently not. Thanks for letting me know.

**Comment by ryanvolz** [comment]
News to me as well!

**Pull request closed without merging**
