### PR TITLE
Drop R 3.3.2.

### PR DESCRIPTION
**Pull request by jdblischak**
This PR will need to be mreged in coordination with a PR to staged-recipes.

xref: https://github.com/conda-forge/r-base-feedstock/issues/36

### CODE REVIEW

**Comment by jdblischak** [comment]
Also, do I need to bump the build number and/or change the version?

**Comment by jdblischak** [comment]
@isuruf @jakirkham Do I need to make any changes before this can be merged? It would be nice if we could stop building R packages for R 3.3.2 immediately when we make the switch to conda-build 3.

**Comment by isuruf** [comment]
You need to bump the version

**Comment by jdblischak** [comment]
@isuruf I bumped the version and changed the build number back to 0.

**Comment by jdblischak** [comment]
@isuruf Is the version ok? I used the current date since that appears to be the convention.

**Comment by jdblischak** [comment]
@conda-forge/r-base Could one of the maintainers please delete the 3.3.2 branch? I don't have permission, and I couldn't find a way to submit a PR that deletes a branch.

**Pull request merged**
