### PR TITLE
ENH issue all PRs for python 39

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

We discussed this at the bot meeting. It is not strictly needed since only 21 PRs are blocked, but I think it makes sense.

### CODE REVIEW

**Comment by beckermr** [comment]
The idea is from @ocefpaf originaly. OK to merge?

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Review by ocefpaf — APPROVED** [review]

**Comment by mbargull** [comment]
How hard would it be to mirror the migration graph to the PR comments? Meaning, could we add a
> Prerequisites for this are the migration PR from the dependencies:
> - dep-1-feedstock/pull/123
> - dep-1-feedstock/pull/456

comment to avoid having all people from the outstanding >100 feedstocks check the CI logs to figure out what's up?

**Comment by beckermr** [comment]
PRs welcome @mbargull! One issue is that some migrations are done in separate PRs and then the one made by the bot is closed. However, this is probably not the majority of things.

**Comment by mbargull** [comment]
> PRs welcome @mbargull!

Yeah.. I don't know the regro code, hence it's likely not economical to have me work on that :sweat_smile:. Anyway, thanks for having it considered!

**Comment by beckermr** [comment]
We can open an issue but I'm not sure when we'll get to it.

**Pull request merged**
