### PR TITLE
Add r-devtools to osx-arm64

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
We need to fix the migrator for R before we send PRs for R packages.

**Comment by xhochy** [comment]
> We need to fix the migrator for R before we send PRs for R packages.

What's the issue with that? I've been migrating several R packages in the last days.

**Comment by isuruf** [comment]
Some R dependencies need to be on `build` when cross compiling.

**Comment by xhochy** [comment]
I've been adding them manually. Do you want the migrator to add all of them to `build`?

**Comment by isuruf** [comment]
Yes, I think it's okay to add all of them.

**Pull request merged**
