### PR TITLE
migrate to jasper 2

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
*  Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* Ensured the license file is being packaged.

@conda-forge-admin, please rerender

Attempting to resurrect #523 and get all packages depending on jasper to version 2

reference [API Laboratory](https://abi-laboratory.pro/index.php?view=timeline&l=jasper) which shows great stability for version 2 of the library.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@isuruf any comments before we try this one?

**Comment by isuruf** [comment]
We should pin jasper to 1 in the main config until the migration is finished.

**Comment by akrherz** [comment]
Thanks @isuruf, but there's no jasper 1 for windows, so I am unsure how to make this change?

**Comment by isuruf** [comment]
Ah, I didn't realize it was already pinned. Can you remove the last commit? Then we can merge.

**Comment by akrherz** [comment]
> Can you remove the last commit?

thanks @isuruf , hopefully done.

**Pull request merged**
