### PR TITLE
Add a few libignition ports to arch_rebuild.txt

### PR DESCRIPTION
**Pull request by traversaro**
fyi @wolfv

### CODE REVIEW

**Comment by traversaro** [comment]
I don't see any change in https://conda-forge.org/status/ after this PR, perhaps I should have used the feedstock names instead of the package names?

**Comment by jakirkham** [comment]
There may be upstream dependencies that need to be migrated first

**Comment by traversaro** [comment]
> 
> 
> There may be upstream dependencies that need to be migrated first

I was supposing that even if that was the case, the ports should at least pop out in https://conda-forge.org/status/#aarch64andppc64leaddition, but that was just a supposition.

**Comment by jakirkham** [comment]
Actually are you sure these are in conda-forge. I'm not seeing them. There are some similarly named things, but not these packages specifically

**Comment by traversaro** [comment]
> 
> 
> Actually are you sure these are in conda-forge? I'm not seeing them. There are some similarly named things, but not these packages specifically

Those packages are in conda-forge, but they are generated by feedstocks with a different name, see for example libignition-transport9 conda package ( https://anaconda.org/conda-forge/libignition-transport9/files ) that is generated by the libignition-transport4 feedstock ( https://github.com/conda-forge/libignition-transport4-feedstock ). This peculiar naming scheme is an artefact given by how the package recipe was originally added to staged-recipes, and for sure the best arrangement would be to have a versionless feedstock name, that generate versioned package names. This was exactly my doubt in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1115#issuecomment-761021558 : I added the line to the arch_rebuild.txt file specifying the package name, but perhaps I should have used the feedstock name.

**Comment by jakirkham** [comment]
cc @conda-forge/bot

**Comment by beckermr** [comment]
use the feedstock name

**Comment by traversaro** [comment]
> 
> 
> use the feedstock name

Done in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1122/files .

**Pull request merged**
