### PR TITLE
Roll back abseil migration

### PR DESCRIPTION
**Pull request by hmaarrfk**
Given the concerns @h-vetinari raised and the challenges in 
https://github.com/conda-forge/grpc-cpp-feedstock/pull/193

I think it is best to compile grpc first, then to start a migration when that package is ready.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
This seems to be th eonly feestock that got migrated: https://github.com/conda-forge/obake-feedstock/issues/28

**Comment by hmaarrfk** [comment]
I think we can add a custom `conda_build_config.yaml` to grpc to experiment and to build the "current" version, while also building the next version. 

It is just too much to ask at this moment to resolve the large abseil issues, while we resolve the grpc issues at the exact same time.

I can update the grpc pr to demonstrate how that would look like.

**Comment by hmaarrfk** [comment]
You can try to build grpc 1.46 with the new abseil. I don't think it will work entirely. but that seems to be a first step for me.

**Comment by hmaarrfk** [comment]
i am not sure what you mean by grpc 1.46 is "done". It is still on the older version of abseil:
https://github.com/conda-forge/grpc-cpp-feedstock/blob/1.46.x/recipe/meta.yaml#L38=

You asked to migrate one at a time. Therefore, we should upgrade abseil to latest by first updating the grpc recipe to the latest version.

**Comment by mariusvniekerk** [comment]
since abeil + grpc move in lockstep we should probably perform these using the keyadd feature that is used for the python migrations

**Comment by hmaarrfk** [comment]
Got it. Yeah. I'm still trying to find a version of grpc that will build with the latest abseil on windows.

**Comment by h-vetinari** [comment]
> Got it. Yeah. I'm still trying to find a version of grpc that will build with the latest abseil on windows.

I've tried to explain this a couple of times already, that it's not the abseil version that's the issue, but abseil's ABI-sensitivity to the C++ standard version.

To underscore that point, I have a working [PR](https://github.com/conda-forge/grpc-cpp-feedstock/pull/196) based on your grpc [PR](https://github.com/conda-forge/grpc-cpp-feedstock/pull/193) and the abseil builds I [propose](https://github.com/conda-forge/abseil-cpp-feedstock/pull/35) (pulled in through the `abseil_dev` label) - thanks again for helping me figure out the conda-build errors on that one. :)

**Comment by hmaarrfk** [comment]
I was summarizing the current status as a 1 liner.....

**Comment by h-vetinari** [comment]
> I was summarizing the current status as a 1 liner.....

Apologies if this came across poorly... I meant that the "still trying" did not take into account (or not noticeably at least) all that I was trying to say about this, so I decided to do it myself, in the hope that this'll move the discussion forward.

**Pull request merged**
