### PR TITLE
Use a newer perl on osx-arm64

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
Ping @xhochy, @conda-forge/core, it would be great to get this merged to release a few perl-dependent migrations.

**Comment by CJ-Wright** [comment]
We could also produce an API/ABI branch on perl and have that branch also get the arch migration, if we wanted the older pin.

**Comment by xhochy** [comment]
@mbargull and @isuruf are the experts here. There is somewhere a more detailed discussion about our Perl pins, moving this here doesn't solve the issues.

**Comment by CJ-Wright** [comment]
I've put up a PR here: https://github.com/conda-forge/perl-feedstock/pull/51 (don't feel pressured to accept it, I just thought I'd put it up in case it was a possible solution we wanted to explore)

**Comment by isuruf** [comment]
Let's go with this for now.

**Pull request merged**
