### PR TITLE
Sort remove dups

### PR DESCRIPTION
**Pull request by ocefpaf**
I'm not sure we want to add the pre-commit here, and/or enable pre-commit-ci. I'm on the fence on that one. However, these files needed some tidying up for a while.

(Edit by @jakirkham) Fixes https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3800

### CODE REVIEW

**Comment by beckermr** [comment]
Rerenders may nuke this custom ci file.

**Comment by ocefpaf** [comment]
> Rerenders may nuke this custom ci file.

It should not touch it b/c it is not a CI file per-se and it didn't on my local tests. However, with that said, maybe conda-smithy should remove a .pre-commit.yaml file, regardless, we activate pre-commit-ci on a per repo basis, so maybe it is not a big if folks add such files, they won't work anyway.

**Comment by beckermr** [comment]
Ahh great! I say we leave things as they are then.

**Comment by beckermr** [comment]
Thank you for this!

**Comment by jakirkham** [comment]
> Rerenders may nuke this custom ci file.

Easy to test

**Comment by jakirkham** [comment]
Resolved some conflicts. Hope that is ok

**Comment by h-vetinari** [comment]
+1 from me. This fixes #3800

**Comment by jakirkham** [comment]
> This fixes #3800

Thanks for pointing that out. Added to the OP

**Comment by h-vetinari** [comment]
I'm in favour of merging this one pretty quickly. The osx-arm file in particular is seeing a lot of traffic recently, and this will just constantly generate conflicts here.

**Comment by ocefpaf** [comment]
> I'm in favour of merging this one pretty quickly. The osx-arm file in particular is seeing a lot of traffic recently, and this will just constantly generate conflicts here.

I'll enable the pre-commit-ci and solve the conflicts today.

**Comment by ocefpaf** [comment]
OK. I think I got it. This is ready for another review/merge.

**Comment by ocefpaf** [comment]
BTW, for those not familiar with pre-commit, the options are

1. run it locally before commiting (I do that for more control)
2. add a git hook and let it run automatically at every commit
3. don't run, let the PR fail, and ask the bot to fix it with `pre-commit.ci autofix` (we will probably for that for most users)
4. let it fix automatically every PR (I don't recommend b/c of the merge conflicts in case the user wants to update the PR.)

Here, I think we will do pretty much 3 all the time.

**Review by h-vetinari — APPROVED** [review]
Didn't validate the sorting, but +1 for the approach.

**Review by beckermr — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Filipe! 🙏

**Pull request merged**
