### PR TITLE
Add libcap to global pinnings

### PR DESCRIPTION
**Pull request by hmaarrfk**
xref: https://github.com/conda-forge/libcap-feedstock/pull/48?notification_referrer_id=NT_kwDOAAFfmLExMzY0OTgyNjA3OTo5MDAwOA#issuecomment-2525686759 Thank you @ehfd This is the kind of PR you can do to start the migrations ^_^

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ehfd** [comment]
OK, I will reference this format in the future.

**Comment by hmaarrfk** [comment]
there is an example file in the same directory that i copy over all the time.

**Comment by ryanvolz** [comment]
@hmaarrfk @ehfd Hey folks, sorry to dig up a closed PR, but I just saw over in https://github.com/conda-forge/systemd-feedstock/pull/35 that this migration has apparently been closed but nothing was ever added to the global pinnings file, and so now `systemd` is just building against the latest `libcap`. I don't see anywhere where the migration was actually completed, so I'm wondering if anyone here knows what happened? I'm going to hold off on merging https://github.com/conda-forge/systemd-feedstock/pull/35 until the `libcap` pin can be sorted.

**Comment by h-vetinari** [comment]
This is a deficiency in the bot, who will not add new pins for migrations being closed. Can you please open a PR to add the pin?

**Comment by ehfd** [comment]
Related: https://github.com/conda-forge/pulseaudio-feedstock/pull/40

@ryanvolz

**Comment by ehfd** [comment]
https://conda-forge.org/status/migration/?name=libcap271

Migrations are still ongoing and if I open new PRs, the migration disappears just like how @ryanvolz experienced.

**Comment by hmaarrfk** [comment]
Our bot is a little eager to close. it used to lag alot to close. we may have swing too far.

But i'm going to merge 2.71 as the global pin and start a 2.75 migration
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/7144

**Pull request merged**
