### PR TITLE
pause pypy migrations

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
I don't care at all if we pause this. I am curious what the plan is here and what the issues are when pypy is going?

**Comment by jakirkham** [comment]
Sounds like [too many CI jobs are being created]( https://gitter.im/conda-forge/conda-forge.github.io?at=5ffb7e7403529b296be0ad17 ). Perhaps instead of turning it on/off we should consider doing a smaller number of PRs. Also are we able to fold the existing PyPy migration in with 3.7. Maybe we don't need 2 PyPy migrations at once.

**Comment by isuruf** [comment]
Issue is the number of PRs. We have to find a balance between too much PRs per hour and too few. We are mostly constrained by Drone CI and sometimes Azure too.

**Comment by isuruf** [comment]
> Also are we able to fold the existing PyPy migration in with 3.7? Maybe we don't need 2 PyPy migrations at once.

We discussed this in the core meeting and the conclusion was that we need conda-smithy changes to do it and nobody wanted to do it.

**Pull request merged**
