### PR TITLE
Add selector to `cdt_name` field

### PR DESCRIPTION
**Pull request by jakirkham**
cc @isuruf @beckermr

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Not sure if this is exactly right. So please let me know. Noticed we didn't have this here, but we do have it for `docker_image`.

**Review by beckermr — APPROVED** [review]

**Comment by tkelman** [comment]
Will this fix the `zip fields in zip_key group ('cdt_name', 'docker_image') are not all the same length` error I'm getting here? https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=228016&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by isuruf** [comment]
I don't think it will. Let's see

**Comment by jakirkham** [comment]
Yeah I'm not sure either. Have gone ahead and submitted PR ( https://github.com/conda-forge/admin-requests/pull/148 ) to mark the last two packages broken. Can throw this one in there as well if it has the same issue.

**Comment by jakirkham** [comment]
Do we need to wait for it to be copied to CDN or does it work immediately?

**Pull request merged**
