### PR TITLE
Update osx_arm64.txt

### PR DESCRIPTION
**Pull request by storopoli**
Removed some stuff that I know that was definitely builded and available for arm64 (that I use) and added pandoc

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

I've removed some stuff that I use and I know that it's available and properly working for arm64. And I added `pandoc`.

### CODE REVIEW

**Review by xhochy — CHANGES_REQUESTED** [review]
Please don't remove things from the migration.

**Comment by xhochy** [comment]
Also be aware that we only do a binary repack of `pandoc` and that there is no binary yet available for it: https://github.com/jgm/pandoc/issues/6960

**Comment by storopoli** [comment]
Ok, I will keep checking on  jgm/pandoc#6960

**Comment by xhochy** [comment]
Once it's landed, feel free to reopen a PR, then we can build/package it here 👍

**Comment by mlund** [comment]
> Also be aware that we only do a binary repack of `pandoc` and that there is no binary yet available for it: [jgm/pandoc#6960](https://github.com/jgm/pandoc/issues/6960)

Currently rosetta emulation seems to be the *only* way of running pandoc on M1 macs. Pandoc installs a single x86 executable in `bin` that runs fine and invisibly using rosetta on arm-based macs. Would it be a hack to simply install the same binary as on x86?

**Pull request closed without merging**
