### PR TITLE
Bump perl version to ensure compatibilit with OSX-arm64

### PR DESCRIPTION
**Pull request by hmaarrfk**
Alternative to: https://github.com/conda-forge/perl-feedstock/pull/51

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Any thoughts on this?

**Comment by hmaarrfk** [comment]
@conda-forge/perl @conda-forge/core any thoughts on getting this through?

**Comment by hmaarrfk** [comment]
@conda-forge/core @conda-forge/perl is there anything holding this up?

**Comment by mbargull** [comment]
This is a dupe of https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/936 .
If you are able to, a review of https://github.com/conda-forge/perl-feedstock/pull/49 would be appreciated.
I'll have this mentioned in today's conda-forge/core meeting and will then merge https://github.com/conda-forge/perl-feedstock/pull/49 reviewed or not. We can then go with `5.32.1` (ref https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/936#issuecomment-852087930 ).

**Comment by hmaarrfk** [comment]
thx

**Pull request closed without merging**
