### PR TITLE
Request Linux aarch64 migration for `ldc`

### PR DESCRIPTION
**Pull request by martin-g**
Needed by Bioconda/samtools
(https://github.com/bioconda/bioconda-recipes/pull/46735)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@martin-g Thanks for the PRs! Can you please combine these requests into a single PR to reduce traffic here?

**Comment by beckermr** [comment]
I mean the number of PRs to review. If you are submitting several in rapid succession, maybe submit one?

**Comment by martin-g** [comment]
Any idea why there is no `Arch migrator` PR at https://github.com/conda-forge/ldc-feedstock/pulls ?
Should I just wait some more ? Usually the bot opens a PR soon after merging a PR like this one.

**Comment by xhochy** [comment]
Check out the status in https://conda-forge.org/status/migration/aarch64andppc64leaddition This will tell you whether it is waiting for something else.

**Pull request merged**
