### PR TITLE
add python-infomap to osx-arm64 migration

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge/conda-forge-pinning ready for review

**Comment by hmaarrfk** [comment]
I'm going to merge https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4056

and we can deal with the consequences maybe.

**Comment by bollwyvl** [comment]
> deal with the consequences maybe.

thanks for the merge: did i do something wrong? Last guidance i got was "put it some-old-place-other-than-the-end".

Of course sorting is great!

**Comment by hmaarrfk** [comment]
sorry, you did everything right, i'm just really hesitant on sorting for the sake of sorting. I don't think it is a good view of the current status anyway. 

I'm working on pointing users to https://conda-forge.org/status/#aarch64andppc64leaddition

**Comment by bollwyvl** [comment]
> sorting for the sake of sorting

Sure, that's a fine concern... then maybe it just needs a linter the ensures uniqueness? Either way, a note at the top (and bottom!) that suggests how to use it would be ideal.

**Comment by hmaarrfk** [comment]
I just suggested this in https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3800#issuecomment-1418283925

See https://github.com/conda-forge/conda-forge.github.io/pull/1895 if you want to comment on the language.

**Pull request merged**
