### PR TITLE
Add migrator for snappy=1.1.8

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
This looks ABI compatible? https://abi-laboratory.pro/index.php?view=timeline&l=snappy

**Comment by xhochy** [comment]
Yes but all binaries are currently built with a fixed `run_exports` on `1.1.7` and from history I doubt that `1.1.9` will be ABI compatible.

**Comment by isuruf** [comment]
I think we should pin for `x` instead of `x.x.x`. 1.1.5 was clearly a mistake and 1.1.6 was released to fix it. See https://github.com/google/snappy/releases/tag/1.1.6

**Comment by xhochy** [comment]
Would this be a suitable plan?

1. Change https://github.com/conda-forge/snappy-feedstock/blob/master/recipe/meta.yaml#L29 to `x`
2. Still run this migration but set snappy to `1.*`

**Comment by isuruf** [comment]
Yes, but with
1.b. Remove old build numbers

(You can also hotfix the pinning so that you don't have to rebuild the packages)

**Comment by xhochy** [comment]
> Yes, but with
> 1.b. Remove old build numbers
> 
> (You can also hotfix the pinning so that you don't have to rebuild the packages)

What would this mean? Mark old snappy builds as broken?  Mark builds of current users of snappy with the wrong export as broken?

**Comment by isuruf** [comment]
>  Mark builds of current users of snappy with the wrong export as broken?

Nope. We can patch the metadata of snappy downstream packages from `snappy >=1.1.7,<1.1.8.a0` to  `snappy >=1.1.7,<2.0.0.a0`.

**Comment by xhochy** [comment]
PR for this in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/26

**Comment by isuruf** [comment]
Why do you need a migrator after  conda-forge/conda-forge-repodata-patches-feedstock#26 is merged?

**Comment by xhochy** [comment]
I'm not sure how to correctly handle this. We should definitely build with `1.1.8+` in future but this can also be done without a migration. Should I set snappy to `1` in the main pinnings file instead?

**Comment by isuruf** [comment]
> Should I set snappy to 1 in the main pinnings file instead?

Yes, I think that's enough.

**Comment by xhochy** [comment]
Also removed the `pin_run_as_build` as we have a `run_exports`.

**Pull request merged**
