### PR TITLE
Change nccl version pin to '2'

### PR DESCRIPTION
**Pull request by kkraus14**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Talked internally with the NCCL team and they confirmed they follow semantic versioning and guarantee no ABI / API breaking changes within a major version so this should be safe.

### CODE REVIEW

**Comment by kkraus14** [comment]
@conda-forge-admin, please rerender

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
cc @beckermr @leofang @CJ-Wright ( from issue https://github.com/conda-forge/nccl-feedstock/issues/36 )

cc @mike-wendt (for vis)

**Comment by isuruf** [comment]
What changed from https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/309/files#r337769526 ?

**Comment by jakirkham** [comment]
Please see the discussion in the issue linked above

**Comment by isuruf** [comment]
In the issue linked above, @kkraus14 said that they found out that "NCCL does follow semantic versioning". This is not news. We already knew this from looking at the first commit, https://github.com/conda-forge/nccl-feedstock/commit/23c16545d87a5f4a7942d9ce1c01ed1ee81dea01 and the fact that `run_exports` was `max_pin=x` from the start of the feedstock.

Your argument when I made the exact same suggestion that @kkraus14 is proposing here was that,

> Our goal here is to ensure we build against the oldest version of nccl we care to have supported by all packages using it for maximum compatibility.

> If we wanted to bump this later, we can always do a migrator, which would be explicit and preferable to letting this creep forward implicitly due to when we happened to rebuild downstream dependencies.

I just want to know what changed from above?

**Review by leofang — APPROVED** [review]

**Comment by jakirkham** [comment]
I think when we started out (and admittedly this is a couple year back now ;) there was not a `run_exports` pin for `nccl` in `defaults` (so we needed a tighter pin to even get the `nccl` package with `run_exports`), there were new features in NCCL that projects like RAPIDS and XGBoost were really reliant on, RAPIDS itself was doing tighter pinning of NCCL (we carefully checked each patch release before upgrading). None of these things are issues any more. Anaconda has forked and started building off our recipe, which has `run_exports` and has been kept up-to-date. What libraries like RAPIDS and XGBoost consider a "new" NCCL is now 2 yrs old :) . RAPIDS has relaxed the pinning in such a way that this would no longer cause issues.

**Comment by kkraus14** [comment]
@isuruf please take a look when you get a chance based on @jakirkham's comment above

**Comment by isuruf** [comment]
Well, @jakirkham's answer confuses me. I don't see how conda-forge's pinning would in any way conflict with an outside library like RAPIDS. It still doesn't answer the original objection,

> Our goal here is to ensure we build against the oldest version of nccl we care to have supported by all packages using it for maximum compatibility.
> If we wanted to bump this later, we can always do a migrator, which would be explicit and preferable to letting this creep forward implicitly due to when we happened to rebuild downstream dependencies.

Why is it that now, changing the version pin to '2' doesn't in @jakirkham's own words doesn't "creep forward implicitly"?

**Comment by jakirkham** [comment]
It does creep forward. It just doesn’t have the downsides it did for downstream libraries previously

**Comment by isuruf** [comment]
> It just doesn’t have the downsides it did for downstream libraries previously

So, how do we justify waiting for downstream libraries given the fact that upstream library is explicitly saying that they are not breaking anything within a major pin and a downstream library disagrees incorrectly? How do we generalize this?
If there's a downstream package of say `zlib` that says that it has downsides, do we just keep the pinning to 1.2.11 or 1.2?

**Comment by jakirkham** [comment]
Please see my original comment. I don’t follow why we want to generalize this given the particular issues in this case

**Comment by isuruf** [comment]
> I don’t follow why we want to generalize this given the particular issues in this case

You said that we wanted to keep the pin to `2.7.8.1` because there were downsides to downstream libraries (which was incorrectly stated by the downstream library at the time despite the upstream library saying there are no downsides) and when it was discovered that there were no downsides for the downstream library, we changed the pin to `2`. How do we handle the situation where some other downstream library says that there are downsides? Do we change this back to `2.7.8.1` or do we ignore them?

**Comment by jakirkham** [comment]
I think we are agreeing to ignore them.

Maybe I should ask do you have technical concerns with this proposal?

**Comment by isuruf** [comment]
> I think we are agreeing to ignore them.

Thank you.

> Maybe I should ask do you have technical concerns with this proposal?

No, I've always wanted to do this for nccl and other pins, but you kept blocking those PRs.

**Pull request merged**
