### PR TITLE
Decrease pr_limit for Python 3.11 migration

### PR DESCRIPTION
**Pull request by mbargull**
We currently have queue lengths of 200-300 for new builds at https://dev.azure.com/conda-forge/feedstock-builds/_build .
Let's tone it down a bit (note that Python migration causes quite a bit larger job matrices than R migration).

### CODE REVIEW

**Comment by isuruf** [comment]
Right now it's 200 jobs running with 287 jobs queued. Shall we do `20` now and increase later?

**Comment by mbargull** [comment]
Amended to 20. (Initially I had 20 but saw a slight decline and thus did 30 -- but maybe increasing later is alright too.)

NB: It'll take a bit to get this PR through due to the queue :D.

**Comment by jakirkham** [comment]
Wonder if we should just give it some time? We passed through some pretty large builds recently `boost`, `opencv`, etc. Think things should get better with those completed (especially given a bunch of folks are going to check out for the day)

**Comment by mbargull** [comment]
> We passed through some pretty large builds recently `boost`, `opencv`, etc.

`scipy` just got queued ;P

**Comment by isuruf** [comment]
It's 363 jobs now. IMHO, we should give more priority to developer experience than getting the migration through a few days faster.

**Comment by isuruf** [comment]
@mbargull, we can move to travis-ci and we can merge quickly.

**Comment by jakirkham** [comment]
Ok

**Comment by mbargull** [comment]
> @mbargull, we can move to travis-ci and we can merge quickly.

Like so?

**Review by isuruf — APPROVED** [review]

**Comment by jakirkham** [comment]
From [CI]( https://app.travis-ci.com/github/conda-forge/conda-forge-pinning-feedstock/builds/257128310 ):

```python
RuntimeError: Travis CI cannot be used on x86_64 in conda-forge!
```

**Comment by mbargull** [comment]
We got too many checks in place to prevent tinkering...
```
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/build_utils.py", line 107, in fail_if_travis_not_allowed_for_arch

    raise RuntimeError("Travis CI cannot be used on x86_64 in conda-forge!")
```

**Comment by mbargull** [comment]
Now seeing queue length of nearly 600...
20 was a good call :D

**Comment by jakirkham** [comment]
Yeah was noticing my notifications get blown up after suggesting we give things time (famous last words) 😅

**Pull request merged**
