### PR TITLE
Try to port packages used by the pangeo project

### PR DESCRIPTION
**Pull request by yuvipanda**
We are trying to build arm64 packages for the pangeo project, and these
are the missing packages: https://github.com/pangeo-data/pangeo-docker-images/issues/396#issuecomment-1283388904

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks a lot, @ocefpaf!

**Comment by ocefpaf** [comment]
Note that some are low hanging fruit and the PRs got merged already. Others are quite challenging, esmpy b/c it depends on esmf.

**Comment by ocefpaf** [comment]
Oops. I should've have caught that. Do you mind sending a PR fixing it?

**Comment by yuvipanda** [comment]
whoops, sorry about that :(

**Comment by yuvipanda** [comment]
@ocefpaf I appreciate all the hard work y'all do in porting these! \o/ Will definitely get used :D

**Comment by yuvipanda** [comment]
@ocefpaf @ngam I didn't add a bunch that we use - tensorflow, pytorch, jaxlib, etc as I'd imagine those are more complex.

**Pull request merged**
