### PR TITLE
Add migration for r_base 4.4 and UCRT mingw toolchain for win

### PR DESCRIPTION
**Pull request by mfansler**
This is a proposal for R 4.4 migration. It features the following aspects:

- migrates 4.4 at initial rate of 4 PRs; [following last year](#4579), we can eventually raise to 40 after initial round of quality checks
- drops 4.2 support - we have traditionally only kept two versions, which keeps parity with CRAN
- drops 4.1 support - this was kept for Windows as a stopgap until we could...
- migrate Windows to UCRT mingw toolchain - this was enable by https://github.com/conda-forge/r-base-feedstock/pull/278 and supports Windows builds for newer R versions

Closes #6083

## Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by isuruf — CHANGES_REQUESTED** [review]
Let's wait for the windows build. It's not too far away.

**Review by jdblischak — COMMENTED** [review]
I think it would be a shame to completely drop Windows, since I think a big strength of conda/conda-forge is being as cross-platform as is feasible. That being said, I don't have the expertise to fix the R build for Windows, so I understand if that tough decision has to be made

**Comment by jakirkham** [comment]
Do we want to address issue ( https://github.com/conda-forge/r-base-feedstock/issues/98 ) before starting this migration?

**Comment by mbargull** [comment]
FYI, @isuruf is proposing in https://github.com/conda-forge/r-base-feedstock/pull/312 to fix https://github.com/conda-forge/r-base-feedstock/issues/98 such that we use the default `.so` extensions on macOS again for better compatibility for R 4.4 onward.
Please take a look an review that PR/issue.

**Comment by h-vetinari** [comment]
Looking at the r-base feedstock, a lot of fixes (& backports to 4.3) have landed - is anything still missing? Exciting!

**Comment by isuruf** [comment]
Waiting for https://github.com/regro/cf-scripts/pull/2806

**Pull request merged**
