### PR TITLE
pin llvm-openmp to clang version

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/core, this is ready for review.

**Comment by xhochy** [comment]
What's the reason for this? Is there any ABI breakage? (i.e. should we do a migration?)

**Comment by isuruf** [comment]
There's no ABI breakage AFAIK, but it's good to have the correct requirement. If we are building with clang 11, the dependency should be `llvm-openmp >=11`, but right now it is `llvm-openmp >=12` because `llvm-openmp=12` is pulled in at build time and run_exports gives `>=12`

**Review by xhochy — APPROVED** [review]

**Comment by beckermr** [comment]
@isuruf Do we need to insert a run constrained section in the recipe?

**Comment by isuruf** [comment]
What do you mean?

**Comment by beckermr** [comment]
We could add a run constraint on clangdev to the llvm openmp package or something like that?

**Comment by isuruf** [comment]
We could, but that's not desirable for conda environments outside of conda-build where it's common to have the compiler installed with other dependencies whereas in conda-build, compilers are installed in an isolated env `build` and deps are installed in `host`.

**Pull request merged**
