### PR TITLE
Complete GEOS 3.9 migration

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
First time doing this, so not sure if this is correct, but followed the docs at https://conda-forge.org/docs/maintainer/pinning_deps.html#updating-package-pins

The geos390 and geos391 migrations are complete (the only remaining packages are "not solvable"): https://conda-forge.org/status/#geos391

cc @ocefpaf

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
> the only remaining packages are "not solvable"

Have you looked into why they're not solvable?

**Comment by jorisvandenbossche** [comment]
@ocefpaf mentioned here (https://github.com/conda-forge/pygeos-feedstock/issues/31#issuecomment-789263689) that the migration could be closed.

But taking a look at those packages:
- postgis is in general a bit lagging behind for several version updates of dependencies (see open PRs at https://github.com/conda-forge/postgis-feedstock/pulls). Although I am not understanding the specific reason here why it is not solvable (*"Problem: package libgdal-3.1.4-h0a4f56a_5 requires libspatialite >=5.0.1,<5.1.0a0, but none of the providers can be installed"*), as the latest libspatialite should already be built with GEOS 3.9.1.
- rgislib: doesn't seem very active (last update in august 2020, https://github.com/conda-forge/rsgislib-feedstock), and none of the recent migrations were merged there

**Comment by jorisvandenbossche** [comment]
Thanks!

**Comment by ocefpaf** [comment]
Thanks @jorisvandenbossche! And sorry for being so slow lately. (I'm working only part time now and it is hard to keep up with the "normal" load of PRs/issues :-/)

**Comment by jorisvandenbossche** [comment]
No problem ;)

**Pull request merged**
