### PR TITLE
Add gflags 2.2 migration script

### PR DESCRIPTION
**Pull request by sodre**
Per [review discussion][discussion] with @xhochy, adding migration script for flags.

xref: conda-forge/staged-recipes#11302

[discussion]: https://github.com/conda-forge/staged-recipes/pull/11302#discussion_r409661016

### CODE REVIEW

**Comment by sodre** [comment]
@CJ-Wright, will the scripts automatically add `gflags` to `conda_build_config.yaml`?

**Comment by xhochy** [comment]
> @CJ-Wright, will the scripts automatically add `gflags` to `conda_build_config.yaml`?

To get this going, I added it manually. Would still be nice to get an answer from @CJ-Wright later about this.

**Comment by CJ-Wright** [comment]
Most likely not since it is a new pin, also that should have been added after the migration is done since any package that is rerendered will get the new pin even if it's deps haven't been rebuilt yet.

**Comment by xhochy** [comment]
> Most likely not since it is a new pin, also that should have been added after the migration is done since any package that is rerendered will get the new pin even if it's deps haven't been rebuilt yet.

:+1: will take care the next time. Good thing is that I'm the maintainer of over half of the packages in the migration so I'll just shoot myself in the foot if I merge anything inbetween.

**Pull request merged**
