### PR TITLE
pin jasper

### PR DESCRIPTION
**Pull request by ocefpaf**
@msarahan what is the approach you are using on defaults for jasper?
We are not upgrading our version just yet...

### CODE REVIEW

**Comment by dougalsutherland** [comment]
It seems like it's very stable: https://abi-laboratory.pro/?view=timeline&l=jasper. Why is the super-tight pin needed?

**Comment by msarahan** [comment]
We don't currently pin it in conda_build_config.yaml.  It hasn't been updated since last September, why the attention now?  http://www.ece.uvic.ca/~frodo/jasper/#download

**Comment by msarahan** [comment]
ah, I see.  You still use the old version.

**Comment by ocefpaf** [comment]
> ah, I see. You still use the old version.

Yep. The new version has new dependencies that we are not packaging yet.

@dougalsutherland can you take a second look?

**Comment by ocefpaf** [comment]
> Assuming we're not doing any further 1.x releases, this is definitely fine. 

Nope. I'm working on 2.x

> Presumably fine even if not but idk.

Probably.

**Pull request merged**
