### PR TITLE
pin mumps 5.2

### PR DESCRIPTION
**Pull request by minrk**
I accidentally pinned 5.1 before

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@minrk may I push to this branch the cfep9 version of this migration?

**Comment by minrk** [comment]
@CJ-Wright sure, no problem

**Comment by minrk** [comment]
I can't approve this since I opened it, but 👍 from me.

**Comment by CJ-Wright** [comment]
@mariusvniekerk does this look ok to you?

**Comment by CJ-Wright** [comment]
This has a graph of 4 things

**Comment by minrk** [comment]
Will this open a new PR to replace https://github.com/conda-forge/petsc-feedstock/pull/63 ?

**Comment by CJ-Wright** [comment]
Most likely not, since these were considered to be separate migrations. But you can request a bot rerun once the mumps migration goes in, which will respect the new pins.

**Comment by CJ-Wright** [comment]
The migration did not operate properly, I'm not certain why. It seems to think that all the migrations are already finished.

**Comment by CJ-Wright** [comment]
relevant logs: https://circleci.com/gh/regro/circle_worker/10756

**Comment by CJ-Wright** [comment]
This is an error in smithy see: https://github.com/conda-forge/conda-smithy/pull/1152

**Comment by minrk** [comment]
Well, they kind of have. The reason I opened this PR is that the *current* version of mumps is 5.2.1, but I accidentally pinned 5.1 in #270. Most packages I'm aware of (maybe all, not sure), were already built with 5.2.

**Pull request merged**
