### PR TITLE
update proj4 pin

### PR DESCRIPTION
**Pull request by ocefpaf**
We'll need a migrator for this later. Ping @snowman2, @dopplershift, and @jorisvandenbossche who may be interested in the development of this pin update.

### CODE REVIEW

**Comment by dopplershift** [comment]
Oooh, fun.

**Comment by ocefpaf** [comment]
> Oooh, fun.

Is that a :+1: or a :-1:?

**Comment by CJ-Wright** [comment]
@ocefpaf you might borrow the code changes from https://github.com/regro/cf-scripts/pull/492/files#diff-472ed2dc43092c4448b858f6225bcd91R307 and use them for a proj4 migrator. The new code should reduce the burden for issuing new simple migration

**Comment by ocefpaf** [comment]
> @ocefpaf you might borrow the code changes from [regro/cf-scripts/pull/492/files#diff-472ed2dc43092c4448b858f6225bcd91R307](https://github.com/regro/cf-scripts/pull/492/files#diff-472ed2dc43092c4448b858f6225bcd91R307) and use them for a proj4 migrator. The new code should reduce the burden for issuing new simple migrations

Awesome! Thanks!! PRing soon...

**Comment by dopplershift** [comment]
@ocefpaf It was a "well this should be interesting." In theory, cartopy and friends should be pinned, and then when cartopy cuts a 6.x-compatible release everything will just work. But that's been theoretically true for so many things that have gone horribly wrong in the past, so...:man_shrugging:

**Pull request merged**
