### PR TITLE
Downgrade JPEG to v8

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
It might be safest to have a build number bump.

**Comment by isuruf** [comment]
Can you explain why you need to build both versions?

**Comment by hmaarrfk** [comment]
In the migration file or in here?

They are not abi compatible, and jpeg turbo is only compatible with version 8.
@ocefpaf was worried that some packages are not compatible with both.

This should help us find those incompatible packages.

**Comment by ocefpaf** [comment]
> @ocefpaf was worried that some packages are not compatible with both.

To be honest I don't believe it is a compatibility issue. Someone mentioned they needed features from jpeg 9 in their software and that is why we upgraded. I believe it could be compiled with jpeg 8 too.

**Comment by hmaarrfk** [comment]
So just downgrade to v8 only?

**Comment by jschueller** [comment]
that is what libjpeg-turbo argues to stick with v8 api: https://libjpeg-turbo.org/About/Jpeg-9

**Comment by hmaarrfk** [comment]
I guess @CJ-Wright 's approval should be considered invalid at this stage unless they chime in again

**Comment by isuruf** [comment]
Don't merge this yet, until we figure out how to switch

**Comment by CJ-Wright** [comment]
My approval was mostly that the migrator is formatted correctly.

**Comment by jschueller** [comment]
So, what is the plan now ?

**Comment by hmaarrfk** [comment]
I don't see why we can't merge this yet. 

We've identified this as a low risk, but necessary step, so why not go through with it?

It would allow us to test the switch in individual feedstocks.

**Comment by isuruf** [comment]
Because, there's no point in building with v8 if you can't switch. If the current-version and compatibility-version is different in OSX or the SONAME is different in Linux, you can't switch.

**Comment by jschueller** [comment]
right, https://github.com/conda-forge/libjpeg-turbo-feedstock/pull/15 is not finished yet, I might need some help there

**Comment by hmaarrfk** [comment]
I kinda disagree with the "there is no point since we can't switch yet".

We know there are some slight differences between 8 and 9. 

This should help us iron those out in anticipation of the switch.

If it turns out to be easy busywork, then all the better. But I see this as a necessary step in the right directory while we iron out other stuff.

**Comment by isuruf** [comment]
What's the benefit of switching to JPEG 8?

**Comment by hmaarrfk** [comment]
one step closer to migrating to `jpeg-turbo`, which has been validated as faster `jpeg` library by many.

I would like to simply do a full switch, and forget about jpeg8 alltogether honestly.

**Comment by isuruf** [comment]
Sure, let's say we rebuilt all of the packages with jpeg8.
If for some reason we can't switch from jpeg 8 to libjpeg-turbo 8 automatically, do you want to build against libjpeg-turbo 8 a second time?
Why can't you do the work to make sure libjpeg-turbo can be hot swapped?

**Comment by hmaarrfk** [comment]
Recent conversation have revealed that a host swap isn't as straightforward as we previously thought.

According to an upstream library maintainer:
https://github.com/conda-forge/staged-recipes/pull/10331#issuecomment-635639418

> Compared to libjpeg v8, libjpeg_turbo supports some additional colorspaces, including alpha channel, which I would like to keep if possible. The Cython DEF macro works, but there seems to be no way to pass a value as an argument to setuptools.Extension().

For his library, we had to rebuild the c modules.

**Comment by isuruf** [comment]
So, then why do you want to rebuild with jpeg 8 here? (not libjpeg-turbo)

**Comment by hmaarrfk** [comment]
I guess I see it as a two step process:

1. Establish the validity of the claim that jpeg9 doesn't provide critical for any packages.
2. If it doesn't, do a full switch to turbo, which is a superset of jpeg 8

I don't want to have the middle step of maintaining both. I think it will just be problematic.

**Comment by hmaarrfk** [comment]
2. Would require an other migrator, which hopefully will be smoother than the 9->8 migration

**Comment by isuruf** [comment]
Why not do the following,

1. Switch to jpeg 8 with hot-swapping
2. For packages that do need libjpeg-turbo, use turbo variant explicitly. (This is what we do for blas where some packages need MKL or OpenBLAS explicitly)

This way, you don't need two migrations.

**Comment by hmaarrfk** [comment]
I just don't see the value in maintaining the hot swapping functionality if we don't need to.

**Comment by isuruf** [comment]
We can remove it later if we want to. I just don't want to do two migrations. Either the hot swapping one or go full libjpeg-turbo. (I'm okay with either, but others may disagree). I don't want the worst of both worlds which is the two step migration.

**Comment by hmaarrfk** [comment]
I'm good with attempting a full turbo migration

**Comment by isuruf** [comment]
Then please present a plan at https://github.com/conda-forge/conda-forge.github.io/issues/673 on how to do this without breaking existing packages.

**Comment by hmaarrfk** [comment]
alright.

**Pull request closed without merging**
