### PR TITLE
Use non CDN for arm64

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/core, this is ready.

cc @mbargull, @chenghlee

**Comment by jjhelmus** [comment]
Can this wait until the end of the day so I can try to enable osx-arm64 on the CDN?

**Comment by beckermr** [comment]
I agree with @jjhelmus. There just isn't a rush on this.

**Comment by jakirkham** [comment]
Thanks for looking into this Jonathan! 😄

**Comment by isuruf** [comment]
Sure.

**Comment by jjhelmus** [comment]
Getting the subdir behind the CDN is going to require a release of conda-build that includes conda/conda-build/pull/4004.  This should happen soon (within 2 weeks) but not in the next day or two. 

Using conda-web until then to move the migration along is reasonable to me.

**Comment by jakirkham** [comment]
Should we reopen then?

**Comment by isuruf** [comment]
Thanks for looking into this @jjhelmus

**Comment by isuruf** [comment]
Merging this now to try it out. Trying this now will give us the opportunity to iron out conda-build bugs in cross compiling before the new release comes out.

**Pull request merged**
