### PR TITLE
Use latest rust

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/core, this is ready

**Review by mbargull — APPROVED** [review]
(cc @pkgw: 1.55 with its macOS SDK 10.9 compat is out and @isuruf also already updated the compiler activation packages :tada:.)

LGTM! (even with the remark/question below.)

@isuruf, do we need to take care of cases in which `>1.49,<1.55` *could* get picked up for macOS builds (albeit with a small probability, I'd presume)? AFAIK we don't have a good way via cbc.yaml to do this apart from pinning `rust`'s version. Do you think it's worthwhile to do something to ensure we don't hit these corner cases?

**Comment by isuruf** [comment]
> @isuruf, do we need to take care of cases in which >1.49,<1.55 could get picked up for macOS builds (albeit with a small probability, I'd presume)? AFAIK we don't have a good way via cbc.yaml to do this apart from pinning rust's version. Do you think it's worthwhile to do something to ensure we don't hit these corner cases?

I don't think we need to. If for some reason >1.49,<1.55 is chosen by conda/conda-build, then the build will fail loudly.

**Comment by mbargull** [comment]
> I don't think we need to.

Okay, good enough for me :).

> If for some reason >1.49,<1.55 is chosen by conda/conda-build, then the build will fail loudly.

What part would fail loudly?

**Comment by isuruf** [comment]
> What part would fail loudly?

Linking

**Comment by mbargull** [comment]
> > What part would fail loudly?
> 
> Linking

Ah right, thanks.

**Pull request merged**
