### PR TITLE
Migrate a few more package to multiarch

### PR DESCRIPTION
**Pull request by jakirkham**
cc @nerohmot

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
For context @nerohmot, anything we add to this list the bot will migrate for us on `aarch64` and `ppc64le`. It also does topological traversal so will pick up dependencies too. May be a bit faster than manually making PRs. Please feel free to add to this list as needed 😉

**Comment by nerohmot** [comment]
GREAT thanx !

**Comment by jakirkham** [comment]
Of course. Please reach out if there are other ways we can help 🙂

**Comment by nerohmot** [comment]
@jakirkham 
My situation is that I need in the end [spyder-kernels](https://github.com/spyder-ide/spyder-kernels) to run on an aarch64 machine.
The [feedstock](https://github.com/conda-forge/spyder-kernels-feedstock) has aarch64 support through `noarch`.

As noted, spyder-kernels itself depends on 
- wurlitzer : aarch64 support available on my aarch64 box (although only the latest version, but that will do)
- cloudpickle : aarch64 support available on my aarch64 box (basically all versions available)
- ipykernel : aarch64 support is only limited available on my aarch box ... only the old 5.0.0 and 5.1.0 pop up 😒 

spyder-kernels however is pinned to >=5.1.3 ...

Do I understand correctly that by adding 
```
pin_run_as_build:
  wurlitzer:
    max_pin: x.x.x
  ipykernel:
    max_pin: x.x.x
  spyder-kernels:
    max_pin: x.x.x
```
to [conda_build_config.yaml](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml) will fix my problems ?!?




```
(py37) C:\Users\hoeren>conda search ipykernel
Loading channels: done
# Name                       Version           Build  Channel
ipykernel                      4.6.1  py27h30cef79_0  pkgs/main
ipykernel                      4.6.1  py35hab2028a_0  pkgs/main
ipykernel                      4.6.1  py36hbb77b34_0  pkgs/main
ipykernel                      4.7.0  py27h5233db4_0  pkgs/main
ipykernel                      4.7.0  py35h2f9c1c0_0  pkgs/main
ipykernel                      4.7.0  py36h2f9c1c0_0  pkgs/main
ipykernel                      4.8.0          py27_0  pkgs/main
ipykernel                      4.8.0          py35_0  pkgs/main
ipykernel                      4.8.0          py36_0  pkgs/main
ipykernel                      4.8.2          py27_0  pkgs/main
ipykernel                      4.8.2          py35_0  pkgs/main
ipykernel                      4.8.2          py36_0  pkgs/main
ipykernel                      4.8.2          py37_0  pkgs/main
ipykernel                      4.9.0          py27_0  pkgs/main
ipykernel                      4.9.0          py27_1  pkgs/main
ipykernel                      4.9.0          py35_0  pkgs/main
ipykernel                      4.9.0          py35_1  pkgs/main
ipykernel                      4.9.0          py36_0  pkgs/main
ipykernel                      4.9.0          py36_1  pkgs/main
ipykernel                      4.9.0          py37_0  pkgs/main
ipykernel                      4.9.0          py37_1  pkgs/main
ipykernel                     4.10.0          py27_0  pkgs/main
ipykernel                     4.10.0          py35_0  pkgs/main
ipykernel                     4.10.0          py36_0  pkgs/main
ipykernel                     4.10.0          py37_0  pkgs/main
ipykernel                      5.0.0  py36h39e3cac_0  pkgs/main
ipykernel                      5.0.0  py37h39e3cac_0  pkgs/main
ipykernel                      5.1.0  py36h39e3cac_0  pkgs/main
ipykernel                      5.1.0  py37h39e3cac_0  pkgs/main
ipykernel                      5.1.1  py36h39e3cac_0  pkgs/main
ipykernel                      5.1.1  py37h39e3cac_0  pkgs/main
ipykernel                      5.1.2  py36h39e3cac_0  pkgs/main
ipykernel                      5.1.2  py37h39e3cac_0  pkgs/main
ipykernel                      5.1.3  py36h39e3cac_0  pkgs/main
ipykernel                      5.1.3  py36h39e3cac_1  pkgs/main
ipykernel                      5.1.3  py37h39e3cac_0  pkgs/main
ipykernel                      5.1.3  py37h39e3cac_1  pkgs/main
ipykernel                      5.1.3  py38h39e3cac_0  pkgs/main
ipykernel                      5.1.3  py38h39e3cac_1  pkgs/main
```

**Comment by jakirkham** [comment]
@CJ-Wright, do you have thoughts on this? 🙂

**Comment by CJ-Wright** [comment]
I don't think that will fix your problem, since that only constrains the ABI compatibility.

I don't know if I understand the question properly.

If you need an older version of wurlitzer built with the other arches then you need to make a branch on the feedstock, put the version as the prior version and build. You will then need to pin it in the recipe.

**Comment by nerohmot** [comment]
well, just the most recent version will do for me I think. so would :

```
pin_run_as_build:
  spyder-kernels:
    max_pin: x.x.x
  wurlitzer:
    max_pin: x.x.x
  ipykernel:
    max_pin: x.x.x
```
do the trick for me the ?

**Comment by CJ-Wright** [comment]
I don't think you need to pin their ABIs with max pins, I think you can just pin them in the recipe itself if they need to be pinned.

Again I don't understand the problem you are having, so I can't really offer any solutions.

**Comment by nerohmot** [comment]
for your reference : [ipykernel-feedstock/issues/53](https://github.com/conda-forge/ipykernel-feedstock/issues/53)

for my and @bollwyvl reference:

what is the correct way ? edit `recipe/migrations/arch_rebuild.txt` directly or edit `recipe/conda_build_config.yaml` ?

**Comment by CJ-Wright** [comment]
the `arch_rebuild.txt` document manages the scope of the arch rebuilds, all the packages in that file and their dependencies will be rebuilt with arm/power support.

**Pull request merged**
