### PR TITLE
Add McStas and McXtrace suites for migration to aarch64 and ppc64le

### PR DESCRIPTION
**Pull request by willend**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by willend** [comment]
@conda-forge-admin, please rerender

**Review by xhochy — APPROVED** [review]

**Comment by willend** [comment]
Hi @xhochy - thanks for merging!

Is there any place to follow up on the (automated?) progress? I was wondering if anything is blocking the process since PRs to the feedstocks and packages did not yet appear...? 

(FYI I updated the feedstock meta.yaml's yesterday before requesting this PR to circumvent the otherwise blocking dependencies of mcpl / ncrystal.)

**Comment by xhochy** [comment]
You should be able to follow the progress here: https://conda-forge.org/status/migration/aarch64andppc64leaddition

**Comment by willend** [comment]
@xhochy thanks - and so I thought, but in fact I find neither of the feedstocks under any of the "labels" (i.e. not DONE, not In PR, not Awaiting Parents, and the remaining categories contain 0 packages...?)

**Comment by xhochy** [comment]
You may need to submit the feedstock name here instead of the package name. 🤔

**Pull request merged**
