### PR TITLE
unpause win-pypy migration

### PR DESCRIPTION
**Pull request by h-vetinari**
Follows #1668 & #1670, now that numpy has been built, see [here](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1668#issuecomment-884125276).

CC @isuruf @beckermr @mattip

### CODE REVIEW

**Comment by mattip** [comment]
Do you understand why the [migration status](https://conda-forge.org/status/#pypy37-windows) shows matplotlib as a child of pyqt (in the In-PR section)? The [recipe](https://github.com/conda-forge/matplotlib-feedstock/blob/1fb8f9baf8b74041daf9a84a115d00653c9e1cab/recipe/meta.yaml#L83) only requires pyqt for CPython

**Comment by h-vetinari** [comment]
I think that's a simple case of the migrator not taking into account selectors. In such cases (barring changes to the migrator, cf. https://github.com/regro/cf-scripts/issues/1331 / https://github.com/regro/cf-scripts/issues/1332), you can simply do a manual migration like https://github.com/conda-forge/numpy-feedstock/pull/238

**Comment by mattip** [comment]
xref conda-forge/matplotlib-feedstock#298. Once (if?) that goes in, will the migrator then notice and continue from there?

**Comment by h-vetinari** [comment]
> Once (if?) that goes in, will the migrator then notice and continue from there?

No, the migrator only knows its own PRs. But one could then close the pyqt one, and would then continue, I believe.

**Pull request merged**
