### PR TITLE
Update pins for Azure Storage September 2024 release

### PR DESCRIPTION
**Pull request by jdblischak**
Closes #6253
Closes #6469

cc: @teo-tsirpanis @h-vetinari @jjerphan @conda-forge/azure-storage-common-cpp

To minimize the number of migrations, in this PR I have combined the latest azure-identity-cpp migration (#6253) along with the latest azure-storage-*-cpp versions from the Azure Storage September Release (https://github.com/Azure/azure-sdk-for-cpp/pull/5967).

xref:
  * Previous discussions of this plan: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6208
  * Previous implementation of this plan: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6210
  * Related feedstock PRs: https://github.com/conda-forge/azure-storage-common-cpp-feedstock/pull/19, https://github.com/conda-forge/azure-storage-blobs-cpp-feedstock/pull/16, https://github.com/conda-forge/azure-storage-files-datalake-cpp-feedstock/pull/17, https://github.com/conda-forge/azure-storage-queues-cpp-feedstock/pull/10

### CODE REVIEW

**Review by jjerphan — APPROVED** [review]
Thank you for taking care of those releases, @jdblischak.

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
Can you also make a PR to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migration_support/packages_to_migrate_together.yaml so that the bot does open this PR correctly in the future?

**Comment by jdblischak** [comment]
> Can you also make a PR to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migration_support/packages_to_migrate_together.yaml so that the bot does open this PR correctly in the future?

@xhochy I don't think the packages_to_migrate_together mechanism would work for the azure storage packages for a few reasons.

First they don't all have the same version, which I understand is a requirement

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/cc01c417694adec39f6f220be7e9268fe68038d4/recipe/migration_support/packages_to_migrate_together.yaml#L1-L2

Second they aren't all available at the beginning of the migration. Because some of the new packages depend on the latest version of the other packages, we use `exclude_pinned_pkgs: false` so that they are migrated at the same time they are updated.

Third the release cadence. While all the storage packages are generally released at the same time, azure-core-cpp and azure-identity-cpp can be released at other times. It's a judgement call when to schedule a migration. We delayed azure-identity-cpp this time, and there happened to not be an azure-core-cpp release recently.

**Comment by xhochy** [comment]
Ah! I didn't notice the different versions in my last review. Then it sadly needs to be a manual process :(

**Comment by jdblischak** [comment]
Status update on the [migration](https://conda-forge.org/status/migration/?name=azure_storage_202409):

* The migration has completed through the main branches of all the feedstocks 🎉 
* Only remaining tasks are [backporting the migration](https://github.com/conda-forge/arrow-cpp-feedstock/pulls?q=is%3Apr+is%3Aopen+azure+storage+september) to arrow 14/15/16

**Pull request merged**
