### PR TITLE
I messed this up with a revert PR so here I am again trying to pause py39

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by jakirkham** [comment]
Is there anything any of us can help with, CJ? 🙂

**Comment by CJ-Wright** [comment]
I think this fixed it, but we'll find out when the CDN syncs (or the bot starts opening a bunch of PRs)

**Comment by CJ-Wright** [comment]
I guess we can put bot-reruns on all the PRs that we did issue

**Comment by jakirkham** [comment]
Sounds good :)

cc @conda-forge/core (for vis)

**Pull request merged**
