### PR TITLE
Add migration for icu=68

### PR DESCRIPTION
**Pull request by xhochy**
Needed at least for https://github.com/conda-forge/libv8-feedstock/pull/40

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge/bot Why did the bot not make this PR?

**Comment by beckermr** [comment]
The bot found the pin change but didn't make the PR

https://github.com/regro/autotick-bot/runs/1441697288?check_suite_focus=true#step:10:10608

**Comment by CJ-Wright** [comment]
It doesn't have a pin spec https://github.com/conda-forge/icu-feedstock/blob/master/recipe/meta.yaml#L27

**Comment by beckermr** [comment]
The bot generated the migrator, but a rerendering error caused this feedstock to be marked as bad before the PR could be issued.

**Comment by beckermr** [comment]
icu has a pin spec in the global pinnings iirc

**Comment by CJ-Wright** [comment]
Ahh ok

**Comment by beckermr** [comment]
The pin spec is 'x' if none is given

**Comment by beckermr** [comment]
Here is the failed rerender: https://github.com/regro/autotick-bot/runs/1441697288?check_suite_focus=true#step:10:10161

**Comment by beckermr** [comment]
I cannot reproduce locally. :/

**Pull request merged**
