### PR TITLE
Tighten freetype pin

### LINKED ISSUE #214: tighten pinning for freetype?
moving issue conda-forge/freetype-feedstock#28 over here at @ocefpaf 's suggestion.

A user is reporting an issue with VTK (conda-forge/vtk-feedstock#80) when freetype 2.10 is used. The issue seeems to be that freetype 2.10 can be installed with a VTK that was built against 2.9.1 and apparently these two are incompatible.

The following site seems to indicate changes in symbols between these versions of freetype:
https://abi-laboratory.pro/?view=timeline&l=freetype

It looks like freetype is only pinned based on the major version:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/9b8e67fcac4a4199dc7af7f120564aceab1cc7b8/recipe/conda_build_config.yaml#L177-L178

Should we tighten the pinning here? If not, then what is the recommended solution on the VTK end?

### PR DESCRIPTION
**Pull request by grlee77**
closes #214 

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### Migration

Yes, 2.10 seems to be ABI incompatible with 2.9.1

### CODE REVIEW

**Comment by grlee77** [comment]
@conda-forge-admin, please rerender

**Comment by grlee77** [comment]
ping @conda-forge/bot

**Comment by grlee77** [comment]
wasn't sure if I was supposed to also update "version" in meta.yaml here or if that is automated somehow? I didn't look like the other open PRs modified that

**Comment by CJ-Wright** [comment]
The bot is currently undergoing some revisions so I'll try to put up a migrator when that is finished.

**Comment by isuruf** [comment]
@grlee77, from the linked issue it was not clear to me whether downgrading to freetype 2.9.1 fixed the issue. Can you confirm?

**Comment by grlee77** [comment]
I did not get a response, but can try it now locally and see if I can replicate the issue

**Comment by grlee77** [comment]
> @grlee77, from the linked issue it was not clear to me whether downgrading to freetype 2.9.1 fixed the issue. Can you confirm?

I could not reproduce the issue from conda-forge/vtk-feedstock#80. I tried creating a new virtual env with `vtk 8.2` and `freetype 2.10.0` .  `import vtk` works fine and so does opening the `mayavi2` application. I also tried from a linux system and didn't find problems there either

There were a handful of symbol differences reported between 2.9.1 and 2.10.0. How does one typically judge whether this is likely to be a problem?  Sorry if this PR was a false alarm. 

Let me know if you want me to remove the change in pinning and still bump the pinned version. Otherwise feel free to close this PR if you do not think we should change the pinning at this time.

**Comment by isuruf** [comment]
> How does one typically judge whether this is likely to be a problem? 

If the removed symbols look like `FT_Outline_Done_Internal, FT_Outline_New_Internal` in a mature library then they are probably not of concern.

**Comment by ocefpaf** [comment]
@grlee77 and @isuruf should we merge this one or is it OK to keep the current pinning?

**Comment by isuruf** [comment]
I think the current pin is fine. If we can find a bug where the loose pinning is the culprit, we can merge this, but until then I'll leave this PR open.

**Comment by grlee77** [comment]
If you want to close this that is fine. I could not reproduce the issue on the VTK end, but this issue is linked there so we can reopen as needed.

**Pull request closed without merging**
