### PR TITLE
Use gcc 9 for CUDA 11

### LINKED ISSUE #1000: cxx_compiler_version incompatible with nvcc
On the faiss-feedstock, we're building per cuda-version, and with the recent compiler upgrades, this now hits the limit for what nvcc supports: 
```
/usr/local/cuda/bin/nvcc -I /usr/local/cuda/targets/x86_64-linux/include/ -Xcompiler -fPIC -Xcudafe --diag_suppress=unrecognized_attribute -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_75,code=compute_75 -lineinfo -ccbin /home/conda/feedstock_root/build_artifacts/faiss-split_1606947926843/_build_env/bin/x86_64-conda-linux-gnu-c++ -std=c++14 -DFAISS_USE_FLOAT16 -I. -g -O3 -c gpu/GpuDistance.cu -o gpu/GpuDistance.o
In file included from /usr/local/cuda/targets/x86_64-linux/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda/targets/x86_64-linux/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
```

I've been trying what feels like dozens of different ways (e.g. [here](https://github.com/conda-forge/faiss-split-feedstock/pull/18#issuecomment-737564530)) to work around this using a local `conda_build_config.yaml`, but it seems the pinning always overrides my values in `_combine_spec_dictionaries` and then I get zipkey-length-conflicts.

Rather than trying to figure out how to fix this on a per-feedstock basis, I'm  I'm now thinking that this should be fixed on the cfp-side directly (hence this issue), because presumably other recipes will also (eventually) be affected.

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Close #1000.

### CODE REVIEW

**Comment by leofang** [comment]
Not sure if this achieves what I think...

**Review by isuruf — CHANGES_REQUESTED** [review]
Have you tried a rerendering of a feedstock with this? Copy this into cupy-feedstock, remove the timestamp and rerender. You'll find that it wouldn't work.

**Comment by leofang** [comment]
Thanks, @isuruf. I was following @h-vetinari's suggestion (https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/1000#issuecomment-752278676). So what's the proper way to achieve the desired effect? I suppose you're saying zipping either in the global pinning (https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1051#issuecomment-751964387) or in the migrator (as done here) just wouldn't work, so I am lost...

**Comment by isuruf** [comment]
I'll let you know if I find one. :smile:

**Comment by h-vetinari** [comment]
So, there's a bunch of problems here I think:
* updating the zip_keys in the pinning feedstock while a migrator that's updating some of the keys is in progress will probably break it (but then, I have close to zero experience with migrators)
* the more keys in a zip, the more fragile it becomes, because _all_ the keys need to match in length under _all_ circumstances (i.e. arches / OSes / etc.)
* `cxx_compiler_version` needs to be in there as well
* Doesn't look like everything will always have the same length (does the CI here check this)?

I think that it should be feasible _after_ the migrator has run through to expand the zip_keys in the pinning feedstock... WDYT, @isuruf?

**Comment by kkraus14** [comment]
My understanding is that expanding `cxx_compiler_version` will also affect non-CUDA feedstocks in that they'll build for each version in which the selector matches.

**Comment by beckermr** [comment]
@isuruf Does the way we handle keys zipped with docker_image in the latest smithy help here?

**Comment by isuruf** [comment]
> @isuruf Does the way we handle keys zipped with docker_image in the latest smithy help here?

Nope

**Comment by h-vetinari** [comment]
So #1223 should make a dent here, but unfortunately still won't allow us to universally go to gcc 9+, because 10.2 is only compatible with gcc 8, see [here](https://github.com/conda-forge/nvcc-feedstock/issues/51).

**Comment by jakirkham** [comment]
What if we added `cxx_compiler_version` and `fortan_compiler_version` to the `zip_keys`?

**Comment by isuruf** [comment]
@jakirkham, please read @kkraus14's comment above

**Comment by jakirkham** [comment]
Right we can include one for the `cuda_compiler_version` with `None`

**Comment by isuruf** [comment]
I don't know whether you understood @kkraus14's comment or not. So, I'll say it again. Expanding `cxx_compiler_version` will produce matrix of builds for non-CUDA feedstocks which we do not want.

**Comment by jakirkham** [comment]
I don't think that is necessarily the case.

**Comment by isuruf** [comment]
Well, I've tried it multiple times before and I can tell you that it will be. Have you tried even once?

**Comment by leofang** [comment]
I think this PR is moot now that we have a proper mechanism to zip the C/C++ compiler version with the nvcc version 🙂

**Pull request closed without merging**
