### PR TITLE
Add pytorch migrator

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1739#issuecomment-889487172
Closes https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1347

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
This should have not been merged. Please see my comment in the linked issue.

**Comment by isuruf** [comment]
We also don't have 1.9.0 gpu builds yet. Can you revert this please?

**Comment by beckermr** [comment]
I can't do it this minute but will do it tonight. Sorry for the delay and the bad merge!

**Comment by hmaarrfk** [comment]
Gah. sorry i jumped the gun too @isuruf. i should have known better.

**Pull request merged**
