### PR TITLE
WIP: Update gdk-pixbuf pinning for windows.

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Does this need a rebuild?

**Comment by hmaarrfk** [comment]
i don't think so.

The package is quite recent, and I don't think anything was able to depend on it since the pinning was set to a version that never existed.

**Comment by ryanvolz** [comment]
> I don't think anything was able to depend on it since the pinning was set to a version that never existed.

This is right, the Windows package for `gdk-pixbuf` didn't exist until the current version, so nothing will need to be rebuilt. In fact, this pinning was done manually in order to enable downstream Windows builds, e.g. https://github.com/conda-forge/librsvg-feedstock/blob/master/recipe/conda_build_config.yaml.

**Comment by xhochy** [comment]
Why not move all OSs to the same version?

**Comment by hmaarrfk** [comment]
> Why not move all OSs to the same version? 

I guess i felt that there may be some integration changes i didn't think of in terms of updating the other OSs. I could migrate the pinning if somebody will champion that change with me.

**Comment by ocefpaf** [comment]
@hmaarrfk are you still interested in bumping both OSes to the same version so we can get this merged?

**Comment by hmaarrfk** [comment]
Should we release it to `'3'` instead of being so strict.

https://github.com/conda-forge/gdk-pixbuf-feedstock/blob/24b5e5575a6a6d2dea1aef23f669c24a38a77792/recipe/meta.yaml#L22

**Comment by ocefpaf** [comment]
Do you want to put a migrator for this or are you OK with just the pinning? I'm not sure how many packages would require a rerender.

**Comment by hmaarrfk** [comment]
does the run_export take precedence? or the pinning in this file?

I guess i can put a migrator in place to be safe.

These kinds of pinning issues are really problematic to track down.

**Comment by ocefpaf** [comment]
> does the run_export take precedence? or the pinning in this file?

I believe the pinning file.

> I guess i can put a migrator in place to be safe.
> 
> These kinds of pinning issues are really problematic to track down.

The migrator would come before this PR then.

**Comment by hmaarrfk** [comment]
thanks.

**Comment by isuruf** [comment]
No need of a migrator since this doesn't bump the version, but only loosens the version. See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/774#issuecomment-726272103

**Pull request merged**
