### PR TITLE
Add windows compatible jasper pin

### PR DESCRIPTION
**Pull request by hmaarrfk**
OpenCV currently builds with Jasper, and this is the first jasper build for windows on conda-forge.
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Ping @conda-forge/core 

It would be great if this could be merged. Once this PR is merged, I'd be happy to open a PR addressing https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/891 (pinning Jasper for aarch/ppc); however, seeing that this PR has been open for so long, it probably makes sense to merge this PR first and tackle aarch/ppc separately later.

**Comment by isuruf** [comment]
Can we start a migration for jasper-2 for x86_64 as well?

**Comment by Tobias-Fischer** [comment]
@hmaarrfk you might know better than I do. I am mostly interested to get opencv running on aarch, happy to go along with whatever it takes to get there, really ..

**Comment by hmaarrfk** [comment]
Since the run_exports only pins the major version, i think it is best to have unix at 1 and windows at 2.

**Comment by hmaarrfk** [comment]
> Can we start a migration for jasper-2 for x86_64 as well?

I think the migration might as well happen when the other unix platforms are a go.

**Comment by hmaarrfk** [comment]
Making a migrator to 2.0 all the way requires a few minor PRs to get merged.
https://github.com/conda-forge/jasper-feedstock/pull/28

**Comment by isuruf** [comment]
Thanks for the info

**Comment by hmaarrfk** [comment]
In all honesty, it seems that 2.X is backward compatible with 1.X. There might be no reason to pin to 1 at all
https://abi-laboratory.pro/index.php?view=timeline&l=jasper

**Comment by isuruf** [comment]
Looks like they are not. 1.X series is not even compatible with itself.

**Comment by hmaarrfk** [comment]
Due to the so name change?

**Pull request merged**
