### PR TITLE
GCC 13 & LLVM 17

### PR DESCRIPTION
**Pull request by h-vetinari**
We've had GCC 13 and Clang 17 live for a while, and Clang 18 was released in March, and GCC 14 is imminent. Should be good enough to start discussing the next update cycle.

To-Do list based on [docs](https://conda-forge.org/docs/maintainer/infrastructure/#compilers-and-runtimes) (was https://github.com/conda-forge/conda-forge.github.io/pull/1950)

* [x] Update all respective feedstocks (listing only those for activation; they wouldn't pass if the implementation wasn't complete)
  * [ ] GCC 13
    * [x] https://github.com/conda-forge/ctng-compilers-feedstock/pull/133
    * [x] https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/121
    * [ ] https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/pull/82
    * [x] https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/97
  * [x] Clang 17
    * [x] https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/113 (osx)
    * [x] https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/102 (linux; not part of global pinning)
    * [x] https://github.com/conda-forge/clang-win-activation-feedstock/pull/32 (win; no part of the global pinning)
* [x] Tested that compilers work
  * https://github.com/conda-forge/scipy-feedstock/pull/250 (includes fortran)
* [x] Checked nvcc-bounds (see [here](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#host-compiler-support-policy) & [here](https://gist.github.com/ax3l/9489132))
  * Cannot update because we're already at the limit for CUDA 11.2 & 11.8 (GCC 11) resp. CUDA 12.0 (GCC 12)
* [x] Checked release notes for ABI-relevant changes
  * [x] GCC [release notes](https://gcc.gnu.org/gcc-13/changes.html) & [porting guide](https://gcc.gnu.org/gcc-13/porting_to.html)
    * Nothing too scary looking. Some transitive header deps in libstdcxx were removed (solved by regular IWYU).
  * [x] Clang [potentially breaking changes](https://releases.llvm.org/17.0.1/tools/clang/docs/ReleaseNotes.html#potentially-breaking-changes)
    * Nothing relevant
  * [x] Clang [ABI changes](https://releases.llvm.org/17.0.1/tools/clang/docs/ReleaseNotes.html#abi-changes-in-this-version)
    * Minor changes (IMO) of the kind we had ignored in [16](https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html#abi-changes-in-this-version), [15](https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html#abi-changes-in-clang) & [14](https://releases.llvm.org/14.0.0/tools/clang/docs/ReleaseNotes.html#abi-changes-in-clang)

Previously: #4991 #4215 #3731 #3290 #3261 #2802 #2010

### CODE REVIEW

**Comment by isuruf** [comment]
See https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/96

**Comment by hmaarrfk** [comment]
A breaking change seems to have been introduced in 13.2 ....
https://github.com/conda-forge/ctng-compilers-feedstock/pull/113

**Review by hmaarrfk — APPROVED** [review]
shall we try?

**Comment by h-vetinari** [comment]
I'm fine with it obviously, but I'm not in a rush on this one. Wanted to bring it up in a core call perhaps, but those have had more high-urgency topics recently.

**Comment by h-vetinari** [comment]
Note: I'm mainly waiting for the release of GCC 14.1 (which is usually followed by a point release for the previous major version from all the bug fixes accumulated during release preparation); once that is in place I think we can run the migration.

**Comment by h-vetinari** [comment]
@conda-forge/core, I'd like to follow through on this compiler update. This has been a long time coming and was also discussed in the last core call.

The one issue is that we currently don't have gfortran 13.3 on OSX (see https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/pull/82 which has been stuck for 2 months), but we do have 13.2 (confirmed working e.g. in https://github.com/conda-forge/scipy-feedstock/pull/250), so that should be good enough IMO to move forward.

**Comment by h-vetinari** [comment]
In case this got lost over the weekend, PTAL @conda-forge/core. If there are no further comments, I'm planning to merge in 24h.

**Review by jaimergp — APPROVED** [review]

**Pull request merged**
