### PR TITLE
Add pypy3.7 migration

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Wait until the bot can handle not sending PRs for feedstocks without pypy3.6

cc @mattip

### CODE REVIEW

**Comment by CJ-Wright** [comment]
We could tack this onto the pypy36 migration and then introduce a new feature to the bot to check that if the rerender has produced **new** files, which we'd expect for a matrix expansion.

**Comment by jakirkham** [comment]
cc @mattip

**Comment by mattip** [comment]
Thanks. Let me know if there is anything I can do to move this forward.

**Comment by mattip** [comment]
Is there progress on this?

**Comment by h-vetinari** [comment]
Can we kick this one off? Without this, there won't be no pypy builds for packages that are deprecating python 3.6 (like [scipy 1.6](https://github.com/conda-forge/scipy-feedstock/pull/151), [numpy 1.20](https://github.com/numpy/numpy/releases))

**Comment by CJ-Wright** [comment]
My understanding is that there are still changes that need to go into the bot (www.github.com/regro/cf-scripts) for this to go forward. I'm happy to provide some pointers about where the changes should go and what I think they should be if anyone is interested in putting up the PR.

**Comment by mattip** [comment]
@CJ-Wright I would be willing to make a PR, what is the goal and how do I do it?

**Comment by CJ-Wright** [comment]
Wait a moment, @isuruf why does the bot need to not send PRs to things without pypy3.6? This migration will add pypy3.6 to those feedstocks that don't have it. I'm not certain what will happen during the variant algebra (I'm hoping it will remove duplicates) but the bot won't issue PRs to things that don't have pypy3.6 (except for the first round) since this will add pypy3.6. I'm not certain what the issue is.

**Comment by isuruf** [comment]
It's going to spam a lot of feedstocks with open PyPy3.6 PRs because upstream project doesn't support PyPy or tests fail.

**Comment by CJ-Wright** [comment]
Hmm, what is the likelihood that pypy3.7 would work where pypy3.6 wouldn't? I'm not certain that not merging the pypy3.6 PRs is strong enough metadata to imply that pypy3.7 isn't wanted. Would it be possible to get something stronger? (Eg something in the cf config itself?)

**Comment by isuruf** [comment]
> Hmm, what is the likelihood that pypy3.7 would work where pypy3.6 wouldn't?

Basically zero

**Comment by CJ-Wright** [comment]
@mattip you'll need to:
1. Add some configuration information that lists the files that must be in the feedstock for the migration to go forward.
2. Change the migrate method so that if that metadata is provided check for the file, if it doesn't exist don't perform the migration (if the migration method returns false it scraps the migration). The migration method has full access to the feedstock folder itself so the files should be there (or not).

The migration class is here https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/migration_yaml.py#L113
and is initialized here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/auto_tick.py#L529

**Comment by CJ-Wright** [comment]
@isuruf to your point, I'm worried about the impact for downstream users. A downstream user may come upstream to fix issues if those issues are blocking their own use of pypy3.7. Withholding those PRs might make that more difficult; I'm not certain if we want to tell maintainers that they need to fix pypy3.6 issues if they want pypy3.7, especially if they don't support 3.6 syntax (as some projects are starting to do)

**Comment by isuruf** [comment]
Ok

**Review by beckermr — CHANGES_REQUESTED** [review]
Am I reading the comments correctly that we need bot changes first?

**Comment by CJ-Wright** [comment]
Maybe, if we want to not issue PRs into feedstocks that don't currently support pypy3.6 then the bot will need some work.

**Comment by beckermr** [comment]
Right. And we still don't have a great story around feedstocks that will never support pypy

**Comment by CJ-Wright** [comment]
We do not, this issue also generalizes to the issue around opting out of migrations.

**Comment by beckermr** [comment]
Thanks for the explainer @CJ-Wright 

Some thoughts and observations:

- I am fine with the proposed bot changes but don't want to code them right now myself.
- This migration is redundant with the pypy36 one in that it would add both, as stated above by others.
- We only have ~284 outstanding pypy36 PRs that would be duplicated according to the status page.
- The pypy36 migration is pretty stalled right now as these large ones tend to get.

So my opinion is that we should end the pypy36 migration and start this one. This will burn through most of the pypy37 PRs pretty quickly I hope and get us back to where we are in the pypy36 one shortly. People can disable pypy36 using selectors as needed. 

Thoughts @isuruf @mattip @CJ-Wright?

**Comment by isuruf** [comment]
> This migration is redundant with the pypy36 one in that it would add both, as stated above by others.

No, this is incorrect. It would only add pypy3.7

**Comment by beckermr** [comment]
Ohhhh. I assumed from @CJ-Wright's comments that it would. Well, we can still do what I proposed, except that we would also need to modify this migration to add both pypy36 and pypy37. This should be a lot easier than making PRs on the bot.

**Comment by CJ-Wright** [comment]
Sorry I made the mistake confusing ordering for actual migration.

**Comment by beckermr** [comment]
no worries!

**Comment by isuruf** [comment]
@beckermr, how is that different from simply merging this?

**Comment by beckermr** [comment]
The original pypy36 migration would still be going so feedstocks would get two separate PRs. 

My proposal would make sure that feedstocks that never got pypy36 would not get pypy37 alone and it would save one PR. It is admittedly a small optimization, but easier than changing the bot.

**Comment by isuruf** [comment]
Finishing the pypy36 migration would add pypy to all feedstocks even the ones where the migrator didn't go and would be disruptive. I'd rather that we merge this as is or change the bot.

**Comment by beckermr** [comment]
I am saying end not finish. We simply turn the pypy36 migration off. 

Do feel free to make a pr on the bot though.

**Comment by beckermr** [comment]
We don't merge pypy36 into the global pinnings. This detail is important.

**Comment by isuruf** [comment]
> I am saying end not finish. We simply turn the pypy36 migration off.

Can you please give more details including how to change the migrators? I'm pretty sure what you are saying is impossible at the moment.

**Comment by beckermr** [comment]
Ohhh I am very sorry! I think if we set `paused: true` in the pypy36 migrator, it will keep it for current feedstocks but the bot won't make new PRs.

**Comment by mattip** [comment]
>  Add some configuration information that lists the files that must be in the feedstock for the migration to go forward.

I don't understand what files these would be. Is this a common migration requirement? Is there  another migration like this that I could use as an example?

It seems I should add a test for this, would [tests/test_migrators.py](https://github.com/regro/cf-scripts/blob/master/tests/test_migrators.py) be the right place?

**Comment by isuruf** [comment]
> Ohhh I am very sorry! I think if we set paused: true in the pypy36 migrator, it will keep it for current feedstocks but the bot won't make new PRs.

How do you propose that we add the two pypy versions to this migrator? If we do that without completing pypy36, we will have pypy36 repeated on feedstocks that were already migrated.

**Comment by beckermr** [comment]
I see. I assumed duplicate variants are removed by conda build. If not, then I propose we do nothing and merge this as is. 

If someone wants to change the bot then feel free ofc. I'm not personally too worried about ~300 prs out of 1600 or so total.

**Comment by isuruf** [comment]
Discussed at core meeting. Let's merge as is.

**Comment by mattip** [comment]
Thanks for getting this going. The [status page](https://conda-forge.org/status/#pypy37) shows "bot-error (16)" among them `setuptools`, which is probably going to slow things down. Is that normal?

**Comment by jakirkham** [comment]
I think `setuptools` needs `wincerstore` and `certifi`. The former has been migrated. I didn't see a PR for the latter.

**Comment by beckermr** [comment]
Things will get retried. I'd focus on the prs we have and ignore the bot errors right now.

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1075

**Comment by jakirkham** [comment]
Ah ok. Thank you both 🙂

**Comment by jakirkham** [comment]
> I think `setuptools` needs `wincerstore` and `certifi`. The former has been migrated. I didn't see a PR for the latter.

Looks like these are showing up now

https://github.com/conda-forge/certifi-feedstock/pull/69
https://github.com/conda-forge/setuptools-feedstock/pull/182 (bot may have got ahead of itself here, but we can just restart this when ready)

**Pull request merged**
