### PR TITLE
Add UCC to global pinning

### PR DESCRIPTION
**Pull request by leofang**
cc @conda-forge/ucc @conda-forge/openmpi

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Your run export is for the major version only.

can we just add a pin of "1" to the global pinning?
```
    - {{ pin_subpackage("ucc") }}
```

https://github.com/conda-forge/ucc-feedstock/blob/main/recipe/meta.yaml

**Comment by leofang** [comment]
good catch, done

**Comment by hmaarrfk** [comment]
The earliest version of the package was 1.2.

so any 1.2 build should be compatibile even with 1.X.

so you can just directly add it to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L888

```
ucc:
   - 1
```

**Comment by leofang** [comment]
Sure, if touching `conda_build_config.yaml` directly is better. Done.

**Comment by hmaarrfk** [comment]
> Sure, if touching conda_build_config.yaml directly is better. Done.

In these cases where you are being proactive, its just simpler and avoids rebuilds!

**Comment by leofang** [comment]
Thanks, Mark!

**Pull request merged**
