### PR TITLE
Rename `pypy38.yaml` to `pypy.yaml`

### PR DESCRIPTION
**Pull request by jakirkham**
This should make it clearer in the status page that this is the PyPy migrator (independent of what versions we were or are now supporting).

<hr>

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
For more clarity, this is how the PyPy migration shows up today. Note it says `pypy38` even though that version has been dropped from the migrator and this is for PyPy3.9 now

Screenshot 2023-10-16 at 5 03 40 PM

**Comment by jakirkham** [comment]
@conda-forge/core , would be interested to hear your thoughts on this change 🙂

**Comment by beckermr** [comment]
The bot may think this is a new migration?

**Comment by h-vetinari** [comment]
The way I understand the working of the migrator (certainly haven't got all the details), the migration files in `$FEEDSTOCK_ROOT/.ci_support/migrations` are matched _by file name_ with what's present in the global pinning. Renaming the file here without also renaming the file in the ~1300 feedstocks will mean they'll all drop pypy on the next rerender.

**Comment by beckermr** [comment]
Right. Let's add a display name field and we can change the bot to put that on the status page.

**Comment by jakirkham** [comment]
Could we just use the first line from the `commit_message` (like we do with PR titles)?

**Comment by beckermr** [comment]
Sure! I don't have strong preferences here. First person to implement the change will likely decide what happens.

**Comment by jakirkham** [comment]
Where would this change need to be made?

**Comment by beckermr** [comment]
Check the status page code in the bot here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/status_report.py#L403-L407C26

**Review by beckermr — CHANGES_REQUESTED** [review]
Will break things.

**Comment by jakirkham** [comment]
Converting to draft to avoid confusion

**Comment by jakirkham** [comment]
PyPy has been dropped in conda-forge: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6345

Closing as won't fix

**Pull request closed without merging**
