### PR TITLE
Bye bye c4aarch64

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
cc @scopatz

**Comment by scopatz** [comment]
Thanks!

**Comment by jjhelmus** [comment]
Glad to see that those initial packages are no longer needed!  I'll update my conda4aarch64 repository to indicate that the conda-forge migration is complete.

**Comment by jakirkham** [comment]
Thanks for helping bootstrap Jonathan! 😄

**Pull request merged**
