### PR TITLE
Merge slepc and petsc migrations

### PR DESCRIPTION
**Pull request by isuruf**
cc @dalcinl

### CODE REVIEW

**Comment by dalcinl** [comment]
:+1: Thanks!

**Comment by CJ-Wright** [comment]
This most likely needs an update of the migration number, since it needs to redo the petsc PRs that didn't have slepc.

**Comment by isuruf** [comment]
There's no need. Those PRs failed and a rerender of those PRs should fix them.

**Comment by CJ-Wright** [comment]
Ahh yes ok. This is because smithy is doing the actual migration provisioning.

**Comment by CJ-Wright** [comment]
What about packages that got the petsc version but not slepc? Will those be left in the cold?

**Comment by isuruf** [comment]
you can't have a slepc 3.12 and petsc 3.13 in the same environment. So, those petsc PRs probably failed. Just rerendering would fix them.

**Pull request merged**
