### PR TITLE
Add pins for console_bridge and urdfdom

### PR DESCRIPTION
**Pull request by traversaro**
`console_bridge` and `urdfdom` are used in many conda-forge packages, and they have a `run_export` in them. To avoid incompatibilities in packages, it is convenient to add a pin for them in conda-forge-pinning.

fyi @conda-forge/urdfdom @conda-forge/console_bridge

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @conda-forge/core we just had another problem caused by urdfdom not being tracked in the pinnings:
* https://github.com/conda-forge/tsid-feedstock/pull/8
* https://github.com/stack-of-tasks/pinocchio/issues/1471#issuecomment-1159521691

**Comment by jcarpent** [comment]
@traversaro Could you explain to me what pinning does?
Thanks in advance.

**Comment by traversaro** [comment]
> @traversaro Could you explain to me what pinning does? Thanks in advance.

In a nutsheell, when a package in conda-forge is built, is built by passing the file https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml to `conda-build`, ensuring that if any package that is a dependency of the package can be found in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml, the version (or versions, if multiple are found such as in the case of python) specified in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml is the one used, instead of the latest one.

Furthermore, once the version used in conda-forge-pinning for a given package is changed, a "migration" is triggered to ensure that all the packages that link against that package are rebuilt, ensuring that all mantained conda-forge packages can be installed against a consistent set of dependencies. For more on migrations, see https://conda-forge.org/blog/posts/2019-12-06-cfep09/ .

**Comment by jcarpent** [comment]
Thanks for the clear answer @traversaro.

**Comment by hmaarrfk** [comment]
This is one example: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2736/files

Then eventually, the bot will close it, but you will have to remember to ask to add the pinnigns to the global pinnigns file
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2742/files (ok I opened this one, the bot was likely have trouble that week)

**Comment by traversaro** [comment]
Great, thanks! Just a small question if you can: what is the semantics of `migrator_ts`/`migration_ts`, i.e. how should I select it? I searched a bit in the docs and in the repo but I could not find material on that.

**Comment by traversaro** [comment]
> Great, thanks! Just a small question if you can: what is the semantics of `migrator_ts`/`migration_ts`, i.e. how should I select it? I searched a bit in the docs and in the repo but I could not find material on that.

I found the answer myself in conda-build source code, i.e. from https://github.com/conda/conda-build/blob/f1c6550b000d2024a2a400f5e90293d5a1de66cd/conda_build/metadata.py#L1427 :
~~~
timestamp=int(time.time() * 1000)
~~~

So, based on https://docs.python.org/3/library/time.html#time.time the timestamp is the number of milliseconds from a platform dependent epoch, that I guess in all the platforms supported by conda is January 1, 1970, 00:00:00 (UTC) (without counting leap seconds).

**Comment by traversaro** [comment]
> > Great, thanks! Just a small question if you can: what is the semantics of `migrator_ts`/`migration_ts`, i.e. how should I select it? I searched a bit in the docs and in the repo but I could not find material on that.
> 
> I found the answer myself in conda-build source code, i.e. from https://github.com/conda/conda-build/blob/f1c6550b000d2024a2a400f5e90293d5a1de66cd/conda_build/metadata.py#L1427 :
> 
> ```
> timestamp=int(time.time() * 1000)
> ```
> 
> So, based on https://docs.python.org/3/library/time.html#time.time the timestamp is the number of milliseconds from a platform dependent epoch, that I guess in all the platforms supported by conda is January 1, 1970, 00:00:00 (UTC) (without counting leap seconds).

Actually, by looking at other migrators, it seems that the timestamp is actually in seconds, not in milliseconds.

**Comment by traversaro** [comment]
> Typically, I've created a migrator first, then when the migrator is done, ensured that the pinning is set. Do you want a migrator ? There seems to be a few old versions of these packages

Done in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3365 .

**Comment by hmaarrfk** [comment]
We'll have to catch the migrator closing. and then add these pins then.

**Comment by traversaro** [comment]
> We'll have to catch the migrator closing. and then add these pins then.

The console_bridge migration ended some time ago, while the urdfdom31 ended at 2022-10-25 20:07:29 UTC .

**Comment by hmaarrfk** [comment]
The console bridge pinning was added in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3372

We should have added the pinning in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3579 but ok.

**Comment by traversaro** [comment]
> The console bridge pinning was added in #3372
> 
> We should have added the pinning in #3579 but ok.

Thanks!

**Pull request merged**
