### PR TITLE
Vc9 take2

### PR DESCRIPTION
**Pull request by ocefpaf**
@isuruf looks like `vc<14` works but `vc==9` does not.

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM! feel free to merge

**Comment by ocefpaf** [comment]
Based on https://github.com/conda-forge/gdal-feedstock/pull/246/files#r238810106 this is still note right :-/ 

Does anyone know the right incantation to use a pre-selector with `vc`s? Both `win vc==9` and `win and vc<14` did not work.

**Comment by dopplershift** [comment]
This might explain why it's not working. (I was doing testing by modifying `~/miniconda3/conda_build_config.yaml` directly)
```
offending line:
  - 4.9.3  # [win and vc<'10']
exception:
'<' not supported between instances of 'bool' and 'str'
```

**Comment by dopplershift** [comment]
@ocefpaf So this *seems* to be doing things ok: `# [win and environ.get('VS_MAJOR', '') < '14']`

**Comment by scopatz** [comment]
That is kind of a dangerous comparison because `'9' > '14'`

**Comment by dopplershift** [comment]
Blah. You're right, I was just deceived. Making it `== '9'` goes back to doing nothing on a rerender.

**Comment by scopatz** [comment]
try: `# [win and int(environ.get('VS_MAJOR', '')) < int('14')]`

**Comment by dopplershift** [comment]
The problem here is that it looks like `conda build` only defines `VS_MAJOR` when running on windows, and `conda smithy` isn't faking it for the rerender.

**Comment by scopatz** [comment]
Ahh sounds like a conda-smithy bug then

**Comment by dopplershift** [comment]
Dunno, I'm a little out of my depth at this point. It seems like:
1. `vc`, at least in `conda_build_config.yaml` is only a bool rather than an int; it seems to be an int when doing selectors in `meta.yaml` though.
2. The `VS_MAJOR` (and I assume its friends) are not available when running `conda smithy` on non-windows

So I don't see a way to do what we want right now. And I'm not sure who's fault that is.

**Comment by isuruf** [comment]
Here's how it's supposed to look like
```
diff --git a/recipe/conda_build_config.yaml b/recipe/conda_build_config.yaml
index f5411a0..e326021 100644
--- a/recipe/conda_build_config.yaml
+++ b/recipe/conda_build_config.yaml
@@ -85,6 +85,8 @@ zip_keys:
     - vc                        # [win]
     - c_compiler                # [win]
     - cxx_compiler              # [win]
+    - gdal                      # [win]
+    - geos                      # [win]
 
   # Dual compiler zip
   -                             # [                                       (environ.get('CF_COMPILER_STACK') == 'comp7')]
@@ -316,11 +318,13 @@ gst_plugins_base:
   - 1.12  # [linux]
   - 1.14.0  # [osx]
 gdal:
-  - 2.3  # [not (win and vc<14)]
-  - 2.2.4  # [win and vc<14]
+  - 2.2.4  # [win]
+  - 2.2.4  # [win]
+  - 2.3    # [not win]
 geos:
-  - 3.7.0  # [not (win and vc<14)]
-  - 3.6.2  # [win and vc<14]
+  - 3.6.2  # [win]
+  - 3.6.2  # [win]
+  - 3.7.0  # [not win]
 giflib:
   - 5.1
 glew:
```

**Pull request merged**
