### PR TITLE
readline 8

### PR DESCRIPTION
**Pull request by CJ-Wright**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Attn: @conda-forge/core

**Comment by mariusvniekerk** [comment]
So.... this has the potential to break cli application for quite a while.  Are we sure we want to land this without a migrator?

**Comment by CJ-Wright** [comment]
do you want the migrator to land first?

**Comment by jjhelmus** [comment]
How would this break cli applications?  Current packages are build against `readline` 7.0 and should be pinned appropriately.  If they are not they are already broken by the existence of the `readline` 8.0 package.  

As downstream packages are built this will create islands of incompatible packages (those with readline 7 and those with readline 8) but the solver will prevent these from being installed into the same environment.

**Pull request merged**
