### PR TITLE
Remove bad pinning for libmatio

### PR DESCRIPTION
**Pull request by hmaarrfk**
https://github.com/conda-forge/libmatio-feedstock/blob/master/recipe/meta.yaml#L16

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by xhochy** [comment]
It's not bad, it just add redundancy with an additional loose 2nd pin? i.e. we don't need any repodata patching?

**Comment by hmaarrfk** [comment]
It actually might have been overwriting it:

image

So maybe we do need repodata patching.

**Comment by hmaarrfk** [comment]
Let me double check with a package i just built

**Comment by hmaarrfk** [comment]
Yes, it seems that hte package built (recently before this PR was merged)
image

https://github.com/conda-forge/libvips-feedstock/pull/31

Was pinned with `'x.x'` and not `'x.x.x'`

**Pull request merged**
