### PR TITLE
Drop CUDA 11.2

### PR DESCRIPTION
**Pull request by h-vetinari**
The 22nd of April has passed (where we [announced](https://conda-forge.org/news/2024/03/06/dropping-cuda-112/) we'd drop CUDA 11.2). This is a variant of #5613 that drops 11.2 and incorporates the various review requests there.

### CODE REVIEW

**Review by jakirkham — CHANGES_REQUESTED** [review]
Thanks Axel! 🙏

Let's stick to dropping CUDA 11.2 here

We can finish our discussion of how CUDA 12 is added in PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5613

**Comment by h-vetinari** [comment]
> We can finish our discussion of how CUDA 12 is added in PR: #5613

Sure we can discuss there.

> Let's stick to dropping CUDA 11.2 here

I'd prefer to do both at the same time.

**Comment by h-vetinari** [comment]
> I'd prefer to do both at the same time.

It's more than a preference actually. If we don't do it at once, we'll break feedstocks that override a GCC version on a CUDA-enabled feedstock. I've recently had to do that for arrow: https://github.com/conda-forge/arrow-cpp-feedstock/commit/af240dccfdf5df1daf4419f3e8ea2ebda1169b5e

(The arrow feedstock will still need fixing afterwards, but at least my approach wouldn't break the bot from opening upgrade PRs.)

**Comment by h-vetinari** [comment]
Friendly ping @jakirkham. I say we should avoid changing the lengths of the compiler-version zip without a migration, unless there is an urgent overriding cause. I don't see one here. Happy to discuss this in the core call if you prefer.

**Comment by jakirkham** [comment]
Thanks for the reminder! Have been a bit swamped recently

Interesting context. Yeah let's discuss in the core call. Added to the agenda

**Comment by jakirkham** [comment]
Based on discussion in the core call, it sounds like we are ok with dropping CUDA 11.2 on its own. Would it be alright if we update this PR to reflect that? Then think we can merge

**Comment by h-vetinari** [comment]
> Based on discussion in the core call, it sounds like we are ok with dropping CUDA 11.2 on its own.

That's not exactly what was discussed IMO, _but_ given that we've deferred the closing of the 12.0 migration for now, I'm fine to close 11.2 separately and deal with the fall-out in arrow.

**Comment by jakirkham** [comment]
Am happy to also look at Arrow if you need a hand

**Comment by h-vetinari** [comment]
> Am happy to also look at Arrow if you need a hand

It's fine, thanks. I know how to do it, I just didn't want the migration bots to stop issuing PRs due to this.

**Comment by jakirkham** [comment]
Completely understand

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Axel! 🙏

Have gone ahead and approved. Please feel free to merge when you are ready

**Pull request merged**
