### PR TITLE
Py38 migration

### PR DESCRIPTION
**Pull request by CJ-Wright**
This isn't ready yet (since we don't have a py38 yet) but we can start discussing this

### CODE REVIEW

**Comment by CJ-Wright** [comment]
This needs fixes to the bot since migrating `vc` et al doesn't make sense

**Comment by CJ-Wright** [comment]
The graph size for this is 1839 packages.

**Comment by isuruf** [comment]
Is that with or without `noarch: python`?

**Comment by CJ-Wright** [comment]
That is without `noarch:python`. My understanding was that noarch packages were not needed in the migration. With noarch its around 4800.

**Comment by CJ-Wright** [comment]
Pending: https://github.com/regro/cf-scripts/pull/626

**Comment by CJ-Wright** [comment]
@conda-forge/conda-forge-pinning for visibility. I know this isn't ready to go out yet. (I wish I could set a timer for when this is ready for review)

**Comment by CJ-Wright** [comment]
This I think can be merged provisionally. There are questions of if we need to tie 3.8 to vc2019 rather than 14. `psutil` was offered up as a potential bell weather for if the current approach will work. If it doesn't we can bump the migration number and fix the zip. @mariusvniekerk

**Comment by jakirkham** [comment]
Thanks CJ! Am looking forward to seeing how this improves the Python build out experience. 😄

**Comment by CJ-Wright** [comment]
It should be much faster! (since after the first two hours we're going to do about 50 an hour)

**Pull request merged**
