### PR TITLE
Drop defaults for all configs

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
LGTM! 

Do we think this one warrants an announcement?

**Review by ocefpaf — APPROVED** [review]

**Review by wolfv — APPROVED** [review]

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-forge.github.io/pull/1513

**Review by kkraus14 — APPROVED** [review]

**Comment by 183amir** [comment]
@conda-forge-admin, please rerender

**Review by jakirkham — APPROVED** [review]

**Comment by beckermr** [comment]
Here we go!

**Comment by beckermr** [comment]
BTW, this is a big deal. Being independent of defaults has been in the works for a long time.

**Comment by 183amir** [comment]
I think this change should also propogate to docker images. For example, when I run `conda info` in `quay.io/condaforge/linux-anvil-comp7`, this is what I get:
```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.12.final.0
       virtual packages : __linux=5.13.19=0
                          __glibc=2.12=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
```

**Comment by jakirkham** [comment]
Would suggest submitting a PR to drop [this]( https://github.com/conda-forge/docker-images/blob/83d1482b776cda162268fac0fe0afeee32b9c44d/scripts/run_commands#L5 )

**Comment by BastianZim** [comment]
Staged-recipes still has _defaults_ as well: https://github.com/conda-forge/staged-recipes/search?q=defaults
Should that get removed? Most files have the _Generated by conda-smithy_ disclaimer on top but not sure if that's actually correct?

**Comment by isuruf** [comment]
Yes, defaults should be removed from staged-recipes too. Can you send a PR?

**Comment by BastianZim** [comment]
Will do. Also for the files that were originally from smithy, correct?

**Comment by isuruf** [comment]
Yes

**Comment by BastianZim** [comment]
PR is in https://github.com/conda-forge/staged-recipes/pull/16340

**Pull request merged**
