### PR TITLE
Add max_pin for pytorch

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Comes from https://github.com/conda-forge/pytorch-cpu-feedstock/issues/40.

Is this how it is supposed to be done?

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
This is not quite right. You need to set a specific pin on a package and add a run export to pytorch itself.

**Comment by jaimergp** [comment]
Needs https://github.com/conda-forge/pytorch-cpu-feedstock/pull/43

**Comment by jaimergp** [comment]
Is this enough to fix https://github.com/conda-forge/pytorch-cpu-feedstock/issues/40 ?

**Comment by isuruf** [comment]
All packages I've seen on conda-forge only supports one version of pytorch. Is that correct? If so, I think we only need `pin_run_as_build`.

**Comment by jaimergp** [comment]
Maybe, but I am not sure. There are some parts of the pytorch world that depend on each other. 
For example, we have `pytorch_sparse`, which depends on `pytorch`. Right now, it is built for PyTorch 1.8.0. Then, PyTorch 1.9.0 is built and released. If a new package X is added to CF, which depends on both `pytorch_sparse` and `pytorch`, it would be built against PyTorch 1.9.0 and Sparse 0.6.3 (but this one didn't get updated and still links to PT 1.8.0). 

Since existing packages were not built with `pin_run_as_build`, will this cause errors? Do we need to rebuild all packages that depended on PyTorch ABI-wise so they carry the `pin_compatible` bit?

**Pull request closed without merging**
