### PR TITLE
add pin for tensorflow

### PR DESCRIPTION
**Pull request by njzjz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

ping @conda-forge/tensorflow 

TensorFlow has API compatibility but does not have ABI compatibility. This means the library linked to the TensorFlow C++ libraries needs to be rebuilt for every TensorFlow version. So in this PR, I added this pin to make things automatic.

### CODE REVIEW

**Review by xhochy — COMMENTED** [review]
Shouldn't we also pin `libtensorflow` and `libtensorflow_cc`?

**Comment by njzjz** [comment]
> Shouldn't we also pin `libtensorflow` and `libtensorflow_cc`?

Added. I am not sure whether they should be added to `zip_keys`.

**Comment by h-vetinari** [comment]
> I am not sure whether they should be added to `zip_keys`.

Zip keys don't really work well for single entries, so it's fine not to add.

**Comment by njzjz** [comment]
It seems @regro-cf-autotick-bot does not automatically update the pining...

**Comment by xhochy** [comment]
@conda-forge/bot Any ideas where to look?

**Comment by h-vetinari** [comment]
> Any ideas where to look?

I think the bot (in https://github.com/regro/cf-scripts) only looks at packages that have the same name as the feedstock, but I haven't delved into this. It's an issue for several multi-output recipes (especially where packages got renamed away from the original feedstockname).

**Pull request merged**
