### PR TITLE
ENH remove pytorch migration

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Should we pause instead of delete so that existing PRs can still run if they want?

**Comment by isuruf** [comment]
It seems that I was wrong that packages only supported one version and there are a few.
So, we just have to wait until the gpu packages are uploaded.

**Comment by h-vetinari** [comment]
I'm confused by the current status. Should PRs such as https://github.com/conda-forge/torchvision-feedstock/pull/28 be merged or not?

**Comment by hmaarrfk** [comment]
@h-vetinari honestly, it is kinda your choice. If you want to start pinning your builds against 1.9.0 then you should merge IMO. your users will have the old version.

I'm trying to build GPU packages as fast as I can.

You may track https://github.com/conda-forge/pytorch-cpu-feedstock/issues/52

**Comment by beckermr** [comment]
Sorry for the confusion here! I merged too fast. Feel free to close the prs if you don't want to deal with them but really it's up to you.

**Comment by hmaarrfk** [comment]
Why did we remove this migrator without adding it to the pinning file?

Was that a mistake? If so, I can make the PR to add pytorch 1.9 again to the pinning.

**Comment by beckermr** [comment]
I forget.

**Comment by hmaarrfk** [comment]
ohhhh i remember, we merge it too early, then this pulled htings.

**Pull request merged**
