### PR TITLE
move to vs2019/vc142

### PR DESCRIPTION
**Pull request by h-vetinari**
Action item from the core meeting just now.

Full discussion is in https://github.com/conda-forge/conda-forge.github.io/issues/1732. The important part is that this is ABI-compatible with all currently deployed windows artefacts (in fact, many feedstocks are using vs2019 already and happily mixing with vs2017 builds), so we do not need a migration.

Closes https://github.com/conda-forge/conda-forge.github.io/issues/1732

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/core 
Per the [announcement](https://github.com/conda-forge/conda-forge.github.io/pull/1810)  two weeks ago, we should merge this PR today (assuming no complaints arrived).

**Comment by isuruf** [comment]
Did you check that nvcc=10.2 works with vc142 toolchain?

**Comment by h-vetinari** [comment]
> Did you check that nvcc=10.2 works with vc142 toolchain?

Has been running without issue for at least 1.5 years (example from faiss: https://github.com/conda-forge/faiss-split-feedstock/commit/15fe1bf33ecc3ad2405bd452814a5c75f2b9885f)

**Comment by h-vetinari** [comment]
q

> > Did you check that nvcc=10.2 works with vc142 toolchain?
> 
> Has been running without issue for at least 1.5 years (example from faiss: [conda-forge/faiss-split-feedstock@15fe1bf](https://github.com/conda-forge/faiss-split-feedstock/commit/15fe1bf33ecc3ad2405bd452814a5c75f2b9885f))

aaaaaargh, sorry, spoke too soon. conda-forge only did cuda-on-win for nvcc=11.0+ 🤦

**Comment by leofang** [comment]
@h-vetinari vc2019 hates CUDA 11.2: https://github.com/conda-forge/cupy-feedstock/pull/179#issuecomment-1234791801

**Pull request merged**
