### PR TITLE
Update osx_arm64.txt

### PR DESCRIPTION
**Pull request by albertojulian**
Checklist

### CODE REVIEW

**Review by xhochy — CHANGES_REQUESTED** [review]
This package doesn't exist at all in conda-forge yet, please first add it via staged-recipes.

**Comment by jakirkham** [comment]
In case you are unfamiliar, the process is [outlined here]( https://github.com/conda-forge/staged-recipes#getting-started ) with links out to other documentation for more details

**Comment by ocefpaf** [comment]
BTW, try to use a more descriptive title. We get tons of PRs adding packages and it would make our life much easier to check things in the notifications list instead of opening the PR.

**Comment by albertojulian** [comment]
Before going on, I will check with the developer of the python wrapper. Thanks for your support, and sorry @ocefpaf  for the title, I'll do better next time.

**Pull request closed without merging**
