### PR TITLE
feat: use GHA for service feedstocks and copy in alt arch .txt files

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by jakirkham** [comment]
Are we still able to re-render here or does that not work with these changes?

**Comment by beckermr** [comment]
We can rerender locally. Happy to revert ofc. This feedstock doesn't need rerendering all that much so I assumed it'd be ok.

**Comment by jakirkham** [comment]
Probably the better thing to do is for use to figure out how to use GHA as CI and enable bot-based re-rendering since we may need to move more things to GHA in the future (not less). That's a separate discussion though

**Comment by beckermr** [comment]
Yeah I have a plan for that but it involves some level of refactoring the rendering code for security hardening.

**Comment by jakirkham** [comment]
Look forward to reading more details on your plan 🙂

**Comment by Tobias-Fischer** [comment]
I think this PR broke CI on the main branch

/cc @hmaarrfk

**Comment by beckermr** [comment]
I think this is the heroku server.

**Comment by beckermr** [comment]
Yeah this job ran fine: https://github.com/conda-forge/conda-forge-pinning-feedstock/actions/runs/10536529046

**Comment by hmaarrfk** [comment]
I guess the symptom is that this package is no longer getting published:
https://github.com/conda-forge/conda-forge-pinning-feedstock/actions/runs/10550981930/job/29227764795

fails

**Comment by beckermr** [comment]
Ahhhh sorry. I forgot to reset the token and add to gha.

**Comment by hmaarrfk** [comment]
Thanks for the quick fix!

**Pull request merged**
