### PR TITLE
skip python 3.6, 3.7 for osx-arm64

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
We should all get in the habit of leaving a short explanation for these things. 

Why are we skipping these pythons?

**Comment by isuruf** [comment]
Because I don't want to support these old versions for a new platform.

**Comment by beckermr** [comment]
Given that you are doing the vast majority of the work for that, I completely think that is great and reasonable. Others can add them if they want. 

LGTM!

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
