### PR TITLE
Use Quay.io

### PR DESCRIPTION
**Pull request by jakirkham**
As DockerHub is implementing consumption limits for downloading images, which would impact our usage if these are enforced for conda-forge, this makes the switch to using Quay.io for all of our images. As we push our images to both container registries, this should be seamless. Though would require feedstock maintainers to re-render after this is merged to get this change.

https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/
https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/
https://www.docker.com/pricing/resource-consumption-updates

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

xref: https://github.com/conda-forge/conda-smithy/pull/1418

### CODE REVIEW

**Comment by jakirkham** [comment]
I don't think we need to do this yet, but am just putting this up here early to make sure we have it (and make any fixes to it that we might need). That way if on November 1st (Sunday) there are issues with container downloads, we can push this fix in.

**Review by isuruf — APPROVED** [review]
@conda-forge/core, need to merge this to avoid errors on drone due to dockerhub limits

**Comment by jakirkham** [comment]
Is this only happening on Drone or does it happen on other providers like Azure? AIUI the pull limits should no longer apply to us, but it's possible something is messed up on DockerHub's end.

**Review by beckermr — APPROVED** [review]

**Comment by jakirkham** [comment]
FWIW I ran a Linux build on Azure just a few minutes ago and didn't see an issue. Not to say there couldn't be issues lurking elsewhere.

**Comment by isuruf** [comment]
See  https://cloud.drone.io/conda-forge/ncurses-feedstock/31/1/2
It doesn't happen on azure. Azure might be caching the docker images though

**Comment by jakirkham** [comment]
Thanks I'll try emailing DockerHub and see what happens. Though happy for us to proceed with this in the interim.

**Comment by mbargull** [comment]
Do we even use tokens when pulling images?

**Comment by isuruf** [comment]
No. docker image is pulled by drone.io, not us

**Comment by mbargull** [comment]
Okay, then "it's working as intended", I guess. We don't say we are "conda-forge" and hence don't get extended limits for "conda-forge" :shrug:.
IMHO, easiest thing would be to merge this PR. Is anyone opposed?

**Comment by beckermr** [comment]
> Okay, then "it's working as intended", I guess. We don't say we are "conda-forge" and hence don't get extended limits for "conda-forge"

I didn't think this is the case. I thought they were exempting our images from the anonymous pull limit, but I guess not? We'll have to ask.

**Comment by jakirkham** [comment]
Sent them an email.

FWIW on Docker's [page about rate-limiting on third party platforms]( https://docs.docker.com/docker-hub/download-rate-limit/#third-party-platforms ), they link out to [Drone's pulling private images doc]( https://docs.drone.io/pipeline/docker/syntax/images/#pulling-private-images ). I'm a little unclear as to whether we need to do this though or if the image itself should be fine to pull repeatedly.

Anyways still happy to go ahead with this PR in the interim.

**Comment by mbargull** [comment]
@beckermr, ah, I think you are right and I just read the forwarded e-mail wrong the first time.

@jakirkham, I'd be fine even without the "interim" part ;). Quay.io is solid, so there shouldn't be any disadvantage, I think.

**Pull request merged**
