### PR TITLE
add python-eccodes to osx-arm64 migration

### PR DESCRIPTION
**Pull request by iainrussell**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)

Adding python-eccodes to arm64 migration.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Thanks, it is useful for conflict purposes to not have the addition at the bottom.

All the best!

**Comment by iainrussell** [comment]
Thank you @hmaarrfk! So, is there is a preferred place to put the additions, or just 'not at the bottom'? I will likely add a couple more over time, so it's good to know what makes things easier.

**Comment by hmaarrfk** [comment]
everybody chooses the bottom! choose something more creative ;)

**Comment by hmaarrfk** [comment]
thats all!

**Pull request merged**
