### PR TITLE
Add pandoc to linux-aarch64

### PR DESCRIPTION
**Pull request by Ethyling**
Add pandoc to linux-aarch64

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Already part of the list.

**Comment by Ethyling** [comment]
I can't find it on https://conda-forge.org/status/ and the package is not available for `aarch64` on https://anaconda.org/conda-forge/pandoc
What am I missing?

**Comment by Ethyling** [comment]
Ok so PR is closed: https://github.com/conda-forge/pandoc-feedstock/pull/51

**Comment by xhochy** [comment]
The PR should not have been closed but kept open. Still, we need a build for aarch64 and we currently only do binary repackaging. Can you have a look at whether aarch64 builds exist and then add them on the feedstock?

**Pull request closed without merging**
