### PR TITLE
Fix gdal migration

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
cc @CJ-Wright, @beckermr

**Comment by CJ-Wright** [comment]
I'm not certain this will fix the bot since gdal and libgdal are in the same feedstock and should have been picked up, but I'm happy to merge.

**Comment by isuruf** [comment]
How is conda-smithy going to know that it needs to bump `libgdal` too?

**Comment by beckermr** [comment]
@CJ-Wright is saying that the bot knows about outputs etc. However, smithy needs the keys to actually bump the local pinnings as @isuruf says.

**Comment by CJ-Wright** [comment]
@isuruf sounds like that should get zipped togehter

**Pull request merged**
