### PR TITLE
Allow easier switching to cos7

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Alternative to https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1230

### CODE REVIEW

**Comment by isuruf** [comment]
cc @beckermr, @leofang

**Comment by beckermr** [comment]
I want to work through the thing I found in smithy before merging this.

**Comment by isuruf** [comment]
This is exactly what I said in gitter.

**Comment by beckermr** [comment]
Sorry! I am not saying never. I just think there might be an actual bug in smithy that might make this not needed.

**Comment by isuruf** [comment]
making it easier to switch to cos7 is not needed?

**Comment by beckermr** [comment]
And yes this is exactly the change you mentioned in gitter.

**Comment by beckermr** [comment]
I think this way of doing things would force whole feedstocks into cos7 when we could be preserving per build configuration. I could be wrong about that ofc.

**Comment by isuruf** [comment]
Which feedstock would need a centos version per build configuration? All use cases we have is to forcing the whole feedstocks

**Comment by beckermr** [comment]
I thought we built some cuda versions on cos6 (pre 11) and some on cos7 (11 and up)

**Comment by beckermr** [comment]
That is what is in our default pinning at least.

**Comment by isuruf** [comment]
That is not changed in this PR at all. Please read the PR. What this PR introduces is to optionally move all builds to centos 7 which is what is needed for cudnn, cutensor, etc.

**Comment by beckermr** [comment]
Sure. However there are things here that don't make sense. For example, smithy appears to be ignoring the ordering key for version bump migrators. So the changes we are making there don't actually do anything for any feedstock. 

These are symptoms of actual bugs that in smithy and how we are using the migrators.

**Comment by isuruf** [comment]
That's a whole different can of bugs. IMO, we should remove variant algebra which is unmaintainable and only have `key_add`, `key_remove` and a new option `key_override`.

**Comment by beckermr** [comment]
Ok. As long as this pr doesn't preclude the fixes in smithy that we need then I'm ok merging it.

**Comment by leofang** [comment]
LGTM. So can anyone confirm my understanding that `ordering` needs to be *the superset* covering all versions that CF is currently supporting?

**Comment by beckermr** [comment]
The ordering in that migrator does nothing as far as I can tell. I have some fixes locally that I went to push tomorrow.

**Comment by leofang** [comment]
I feel the `ordering` in the migrators is to make sure all the zip keys below it are recognized, so it has to be a superset?

btw I will push a smithy fix in 5 mins.

**Comment by beckermr** [comment]
I went through the code. That ordering is only for the key add operations. Otherwise it is ignored.

**Comment by isuruf** [comment]
> I went through the code. That ordering is only for the key add operations. Otherwise it is ignored.

This is not true. It is used when figuring out which key to keep.

**Comment by beckermr** [comment]
I swear that is not what I read in the code, but looking at it now, you are right. Sorry for the confusion @leofang @isuruf!

**Comment by jaimergp** [comment]
This version of the `cuda110` migrator is not working in on the feedstocks I maintain:

* PR: https://github.com/conda-forge/openmm-torch-feedstock/pull/2
* Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=289854&view=logs&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=350df31b-3291-5209-0bb7-031395f0baa1&l=156


Looks like CUDA 11 is trying to use GCC 7?

**Pull request merged**
