### PR TITLE
Pin libssh2 to major, remove max_pin

### PR DESCRIPTION
**Pull request by xhochy**
Also stops the migration.

I'll add a repodata patch once this is merged.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by beckermr** [comment]
Do we need to stop any migrations?

**Comment by xhochy** [comment]
> Do we need to stop any migrations?

Yes, the `libssh219` one. Not sure in which state the bot will be but this removes the migration file.

**Comment by beckermr** [comment]
Removing the file is fine. The currently built PRs should be ok due to the ABI compat.

**Comment by xhochy** [comment]
> Removing the file is fine. The currently built PRs should be ok due to the ABI compat.

Not merging them will make the repodata patch simpler.

**Comment by jjhelmus** [comment]
Thanks @xhochy

**Pull request merged**
