### PR TITLE
Pin s2geography and s2geometry

### PR DESCRIPTION
**Pull request by benbovy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Can you add the appropriate "run_export" to https://github.com/conda-forge/s2geometry-feedstock/blob/main/recipe/meta.yaml#L16

https://github.com/conda-forge/s2geography-feedstock/blob/main/recipe/meta.yaml#L13

before we start this  migration

**Comment by benbovy** [comment]
As far as I can tell, no package depends on s2geography yet (only this PR https://github.com/conda-forge/staged-recipes/pull/27348) and two packages depend on s2geometry: s2geography and pys2index where only the latter would require a migration.

Added `run_exports` in the s2geometry feedstock here: https://github.com/conda-forge/s2geometry-feedstock/pull/20.

**Comment by hmaarrfk** [comment]
It also went without saying that you should also add a run_export to:
https://github.com/conda-forge/s2geography-feedstock/blob/main/recipe/meta.yaml#L13

In the PR, you should be able to delete the entire "run" section since they should be "exported" automatically.


Finally xhochy is suggesting that instead of creating a migrator, you simply add your packages to the file
https://github.com/benbovy/conda-forge-pinning-feedstock/blob/add-s2geography-s2geometry/recipe/conda_build_config.yaml
in the appropriate location

**Comment by benbovy** [comment]
OK thanks @hmaarrfk. I added run_exports for s2geography as well (and deleted the run section) in https://github.com/conda-forge/s2geography-feedstock/pull/6.

I removed the migration for s2geography in [ebb8793](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6379/commits/ebb8793fef44b3e8ff3568e75a5d0ae219f0d242).

I left the migration for s2geometry so that it triggers rebuilding https://github.com/conda-forge/pys2index-feedstock. Should I also add s2geometry in `conda_build_config.yaml` or will be added automatically after merging this PR?

**Comment by xhochy** [comment]
> Should I also add s2geometry in conda_build_config.yaml or will be added automatically after merging this PR?

Please also add it. The automatic update only works if it already is in there.

**Pull request merged**
