### PR TITLE
Make sure compiler versions are different for different arches

### PR DESCRIPTION
**Pull request by isuruf**
This makes the hashes different for different arches which enables
cross-compiling

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
Can you provide more details or link to a buggy run here? I am not sure everyone understands what is going on here. I am sure I don't.

**Comment by isuruf** [comment]
This PR prevents hash collisions mentioned in https://github.com/conda/conda-build/issues/3155.

**Comment by beckermr** [comment]
Ahhhh. It is a hack until conda fixes that. Got it. LGTM!

**Review by beckermr — APPROVED** [review]

**Comment by isuruf** [comment]
Thanks for the review

**Pull request merged**
