### PR TITLE
Include `nspr` in global pinnings

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/53

ref: https://abi-laboratory.pro/?view=timeline&l=nspr

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by scopatz** [comment]
LGTM @jakirkham - can you update the version number please?

**Comment by jakirkham** [comment]
Sure. For simplicity though, could we just do this in one of the `nspr`, `nss` PRs? Would arbitrarily suggest PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/168 ). IOW merging this as is.

**Comment by scopatz** [comment]
yep, that works for me!

**Pull request merged**
