### PR TITLE
clang 13

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/core, this is ready.

**Comment by beckermr** [comment]
This build 

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=495884&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b

with the new 13 failed asking for a very old version 4. Did we miss something here?

**Comment by isuruf** [comment]
Need to rebuild compilers-feedstock

**Comment by beckermr** [comment]
Ahh thank you. It'd be nice to automate this process but maybe the compilers feedstock is on the margins of support.

**Pull request merged**
