### PR TITLE
Win-arm64 migration list

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by h-vetinari — APPROVED** [review]
I assume this works like the other arch migrators. Seems like a reasonable start!

**Review by xhochy — APPROVED** [review]

**Comment by martin-g** [comment]
Is there a CI provider with Win ARM64 resources ?
I know that in Github Actions one can use self-hosted Windows ARM64 runner, but I have no idea about Azure.

**Comment by h-vetinari** [comment]
FWIW, this needs a purpose-built migrator in regro/cf-scripts like we have for `linux-{aarch64,ppc64le}` resp. `osx-arm64`. Probably easiest to create a new migrator in [this](https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/arch.py) file, which is where the former two live.

**Comment by jakirkham** [comment]
@arnabanimesh , thanks for looking into Windows ARM builds on feedstocks! 🙏

As you are looking into this, it might be easier to finish up this work on the Windows ARM migrator. That way the bot can assist in creating PRs and tracking where we are in topological sort of conda-forge dependencies

Is this something you would be willing to look into? 🙂 (also no worries if not)

**Comment by finnagin** [comment]
Hey, it looks like this might be one of the next things that needs to happen for Windows arm64 support. Is there anything I can do to help move this forward?

**Pull request merged**
