### PR TITLE
expand cuda_112_ppc64le_aarch64 migrator for cross-compilation

### PR DESCRIPTION
**Pull request by h-vetinari**
Towards work in https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/209

### CODE REVIEW

**Comment by isuruf** [comment]
Is this ready for review?

**Comment by h-vetinari** [comment]
> Is this ready for review?

Yes. The reason it's WIP is that I haven't gotten any feedback on it.

As we saw in https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/210, this is necessary but not sufficient on the way to cross-compilation with cuda 11.

**Comment by isuruf** [comment]
What else is needed?

**Comment by h-vetinari** [comment]
> What else is needed?

See https://github.com/conda-forge/nvcc-feedstock/issues/95

**Pull request merged**
