### PR TITLE
Update osx_arm64.txt: adds r-padr

### PR DESCRIPTION
**Pull request by adolfogc**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
There are some merging conflicts, as soon as they are resolved we should be ready to approve

**Comment by adolfogc** [comment]
Hi, I expect to update this tomorrow

**Comment by adolfogc** [comment]
Hi @varlackc, I have rebased and fixed the commit.

**Comment by ocefpaf** [comment]
> Hi @varlackc, I have rebased and fixed the commit.

That user is not a member of conda-forge and doesn't have commit rights in our repos. Please ping the core members next time or your request may be lost in the shuffle. Apologies for the confusion but we cannot prevent random folks to comment and confuse users sometimes.

**Comment by adolfogc** [comment]
Hi, @ocefpaf, thank you! And w.r.t the clarification, I'll keep it in mind for future PRs

**Pull request merged**
