### PR TITLE
Added cmarkgfm for osx arm64

### PR DESCRIPTION
**Pull request by seanlaw**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seanlaw** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
> @conda-forge-admin, please rerender

No need for this on this feedstock, this gets automatic rerender really often ;)

**Comment by isuruf** [comment]
Since twine is added to the migrator, this is strictly not necessary as the bot will send PRs to dependencies first.

**Comment by seanlaw** [comment]
@isuruf I just added `twine` was looking at the [conda forge status page](https://conda-forge.org/status/#armosxaddition) which showed:

Screen Shot 2021-02-05 at 2 09 05 PM

Maybe I misunderstood but since `cmarkgfm` was under "awaiting-pr" I thought that meant that I need to add it to the list as well.

**Comment by isuruf** [comment]
Nope. `awaiting-pr` means the bot has a backlog of PRs to be issued and will get to it eventually.

**Comment by seanlaw** [comment]
Thank you for the clarification (and support)!

**Pull request merged**
