### PR TITLE
add proj to migration

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Proj is in the migration, please see the dependency graph on the status page. Note that it hasn't gotten a PR because something is wrong with the package. The logs are here: https://github.com/regro/autotick-bot/actions?query=workflow%3Abot

**Comment by jakirkham** [comment]
Thanks for the info CJ. Should we be doing something here? Does this need to backed out for instance?

**Comment by CJ-Wright** [comment]
I don't think backing out out will change anything. Any help determining why proj isn't working properly would be greatly appreciated.

**Comment by wolfv** [comment]
proj was renamed from proj.4 or proj4 or something. Now the feedstock still has the old name. Could that be part of it? @CJ-Wright

**Comment by CJ-Wright** [comment]
Perhaps, but last time I looked at the logs I thought there was a hash problem.

**Comment by wolfv** [comment]
anything I can do to make this happen @CJ-Wright ?

**Comment by CJ-Wright** [comment]
Can you look at the logs and assess what the issue is? If it's the proj4 problem we may need to discuss a solution, which may be deleting the archived node.

**Comment by wolfv** [comment]
this is the logged issue:

```
2020-09-29 12:59:29,867 INFO     conda_forge_tick.auto_tick || ARCHREBUILD-aarch64 and ppc64le addition IS MIGRATING proj

2020-09-29 12:59:29,969 CRITICAL conda_forge_tick.auto_tick || GITHUB ERROR ON FEEDSTOCK: proj
404 Not Found
<Response [404]>
https://api.github.com/repos/conda-forge/proj-feedstock
```

So I guess we need to either fix the bot or the feedstock name, or migrate proj4

**Comment by CJ-Wright** [comment]
I think we should remove the proj node in that case @conda-forge-bot what do you think?

**Comment by wolfv** [comment]
I don't know what "node" in this context means?

**Comment by wolfv** [comment]
I've triggered migration by hand now: https://github.com/conda-forge/proj.4-feedstock/pull/94

**Comment by CJ-Wright** [comment]
`node` means the node in the cf-graph graph. I'm not certain if doing the migration by hand will help much, since the graph still won't progress forward.

**Comment by CJ-Wright** [comment]
I have a PR into the bot that should fix this

**Comment by wolfv** [comment]
cool!

**Pull request merged**
