### PR TITLE
redo pypy migration

### PR DESCRIPTION
**Pull request by isuruf**
Needed because of the change in https://github.com/conda-forge/pypy3.6-feedstock/pull/76

### CODE REVIEW

**Comment by isuruf** [comment]
cc @mattip

**Comment by mattip** [comment]
:+1:

**Comment by mattip** [comment]
Is there any reason to mess with conda-forge/cython-feedstock#88 before this is merged?

**Comment by beckermr** [comment]
We should leave a comment here on why we had to do this.

**Comment by h-vetinari** [comment]
Not to hold anything up, but I don't understand why we need to restart? There's been only one PR (setuptools) merged so far, couldn't we just rebuild that one and leave the rest of the migration going?

**Comment by jakirkham** [comment]
FWIW bumping the `build/number` for `setuptools` in PR ( https://github.com/conda-forge/setuptools-feedstock/pull/254 ) if that helps

**Comment by hmaarrfk** [comment]
@h-vetinari i think it is because of https://github.com/conda-forge/pypy3.6-feedstock/pull/76

**Comment by h-vetinari** [comment]
One thing that I don't understand is that the migrator is doing stuff like this:
```diff
-build_platform: {osx_arm64: osx_64}
+build_platform:
+  linux_aarch64: linux_64
+  linux_ppc64le: linux_64
+  osx_arm64: osx_64
```

IOW, actively switching feedstocks to cross-compilation. I'm not sure why this is happening (doesn't seem to be specified in the migrator in any detectable way), and interestingly, native builds seem to pass (c.f. https://github.com/conda-forge/setuptools-feedstock/pull/254 which contains https://github.com/conda-forge/setuptools-feedstock/commit/84928eff68a7f356d82cc8f648935552e30e6e32 vs. https://github.com/conda-forge/setuptools-feedstock/pull/253 which doesn't)

**Comment by h-vetinari** [comment]
> i think it is because of [conda-forge/pypy3.6-feedstock#76](https://github.com/conda-forge/pypy3.6-feedstock/pull/76)

Indeed, I see that this is the statement in the OP, but what I don't understand is how that forces a restart, if only one PR has been merged so far.

**Comment by jakirkham** [comment]
Sometimes restarting is the path of least resistance. CI will have to be restarted on downstream PRs. Recipe maintainers may have questions and ping core. Sometimes these migrations move faster than it takes to make a fix like this. So it can be easy and fairly straightforward to just restart the migration. Maybe there are other things I've missed?

Though maybe you are right this is just one package, which is easy enough to fix without redoing the migration.

**Comment by h-vetinari** [comment]
Thanks @jakirkham, that's all I wanted to double-check. I'm not against a restart, I just wanted to understand the context.

**Comment by h-vetinari** [comment]
> One thing that I don't understand is that the migrator is doing stuff like this:

@isuruf [asked](https://github.com/conda-forge/setuptools-feedstock/pull/253#issuecomment-1082471050) me to create an issue for this: https://github.com/regro/cf-scripts/issues/1518

**Comment by jakirkham** [comment]
JFYI we are pausing the migration for the moment ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2668 ). We want to get a handle on these issues before starting it back up

**Comment by h-vetinari** [comment]
Any blockers to restarting the migration? Should we figure out https://github.com/regro/cf-scripts/issues/1518 before or are we fine to have the aarch/ppc builds converted to cross-compilation?

**Comment by isuruf** [comment]
No need to restart now I think

**Comment by h-vetinari** [comment]
> No need to restart now I think

Sorry I wasn't clear; I meant unpause, i.e. revert https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2668

**Comment by jakirkham** [comment]
I think we are ok to unpause. Would you like to open a PR?

**Pull request closed without merging**
