### PR TITLE
Migrate to qt6-main 6.8

### PR DESCRIPTION
**Pull request by hmaarrfk**
Compatibility bugs:
## Under investigation

* https://github.com/jupyter/qtconsole/issues/624

## Resolved

* https://github.com/spyder-ide/qtpy/issues/494

cc: @jschueller @conda-forge/qt-main

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by jschueller — APPROVED** [review]

**Comment by hmaarrfk** [comment]
so Qt6.8 is making my whole application crash.....

**Comment by hmaarrfk** [comment]
I guess i'm on Ubuntu 24.10.....

**Comment by hmaarrfk** [comment]
hmm it doesn't seem to be related to Ubuntu 24.10. It seems to be happening on 24.04 as well.

**Comment by hmaarrfk** [comment]
Of course things like a simple widget don’t crash. 

Will have to continue to investigate. But I would appreciate if somebody else could corroborate or refute my findings with an application of theirs

**Comment by hmaarrfk** [comment]
```
python -c "from qtpy.QtCore import Qt"
Segmentation fault (core dumped
```

https://github.com/spyder-ide/qtpy/issues/494

**Comment by hmaarrfk** [comment]
In either case. This should be skipped because according to Qt

The Qt version 6.8 series is binary compatible with the 6.7.x series. Applications compiled for 6.7 will continue to run with 6.8.


https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.8.0/release-note.md

**Comment by hmaarrfk** [comment]
So i'm happy to report that my application doesn't crash anymore. 

Does anybody want to give pyside6 6.8.0 (the latest build) a try and confirm?

**Comment by hmaarrfk** [comment]
xref : https://github.com/conda-forge/pyside2-feedstock/pull/249

**Comment by hmaarrfk** [comment]
The main concerns I believe are gone. time to start the migration!

**Pull request merged**
