### PR TITLE
Drop python 3.6

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by chrisburr — APPROVED** [review]

**Review by ocefpaf — APPROVED** [review]

**Comment by beckermr** [comment]
This needs an announcement too, right?

**Review by beckermr — COMMENTED** [review]
Did you double-check the pypy migrators to ensure they won't be confused by the change in the build matrix?

**Comment by isuruf** [comment]
Yes

**Review by xhochy — APPROVED** [review]

**Review by beckermr — APPROVED** [review]

**Comment by isuruf** [comment]
Announcement at https://github.com/conda-forge/conda-forge.github.io/pull/1516

**Review by mbargull — APPROVED** [review]

**Review by jakirkham — APPROVED** [review]

**Review by chenghlee — APPROVED** [review]

**Review by bgruening — APPROVED** [review]

**Review by wolfv — APPROVED** [review]

**Review by jaimergp — APPROVED** [review]

**Review by ericdill — APPROVED** [review]

**Pull request merged**
