### PR TITLE
Request arch migration for all missing parents of perl-moose

### PR DESCRIPTION
**Pull request by martin-g**
https://conda-forge.org/status/migration/?name=aarch64andppc64leaddition shows the perl-moose depends on several other perl-** packages.

Fix a typo in `perl-storable`.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
Is this PR OK?
Or there are too many items added at once?

**Comment by xhochy** [comment]
This shouldn't be required as the packages are automatically migrated. Only packages that are not shown in the status page need to be added here.

**Comment by martin-g** [comment]
Thanks for the info, @xhochy !
Could you please help me understand how to untie the builds for those packages ? I checked several of these feedstocks and none of them has `Arch Migrator` PR, open or closed.
Which feedstock's migration stops the chain

**Comment by martin-g** [comment]
Thank you!

**Pull request closed without merging**
