### PR TITLE
Migrate NCCL to 2.8.4.1

### PR DESCRIPTION
**Pull request by leofang**
This is to fix the migration error in CuPy, see https://gitter.im/conda-forge/conda-forge.github.io?at=6037ccaecdbfc0620c2a5559.

cc: @jakirkham @kkraus14 @conda-forge/core

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by kkraus14** [comment]
I think we need to write a migrator for this and once it finishes we can bump this version: https://conda-forge.org/docs/maintainer/pinning_deps.html#update-pins

**Comment by leofang** [comment]
Thanks for the pointer, @kkraus14! Didn't know that. I just followed #846 and created a migrator.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Review by kkraus14 — APPROVED** [review]
lgtm but I don't have much experience in dealing with migrators, would appreciate if someone else from @conda-forge/core could take a look

**Comment by beckermr** [comment]
Let's go!

@conda-forge/bot any idea why the bot did not generate this PR?

**Comment by leofang** [comment]
Thanks @kkraus14 @beckermr!

**Comment by jakirkham** [comment]
cc @mike-wendt (for awareness)

**Pull request merged**
