### PR TITLE
Mark Python 3.8 migration complete

### PR DESCRIPTION
**Pull request by jakirkham**
Follow-up to PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/698 )

As we already include Python 3.8 by default and ~95% of packages have been migrated, it should be safe to close out the Python 3.8 migration.

cc @conda-forge/core

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Any thoughts here @conda-forge/core? 😉

**Comment by ocefpaf** [comment]
If we wait two more months it will an year since I wanted to do this ;-p

**Review by ocefpaf — APPROVED** [review]

**Comment by mariusvniekerk** [comment]
We should probably mark this complete before 3.9 :P

**Review by beckermr — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
