### PR TITLE
Add _cpython pinning to python

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Ready for a review now

**Comment by beckermr** [comment]
I'm confused generally since I know we just removed some of these build selections somewhere else. That being said, you know this stuff better so LGTM!

**Comment by isuruf** [comment]
> I'm confused generally since I know we just removed some of these build selections somewhere else.

We did? where?

**Comment by beckermr** [comment]
Did we muck with the python 3.8 recipe recently?

**Comment by beckermr** [comment]
ahhhh it was another thing

https://github.com/conda-forge/python-feedstock/commit/767caf9b45a805e45054f824bca2c68d4947f119

**Comment by isuruf** [comment]
Yes, it was removed until there was a new conda-build release, and now that we have a new release, it's back on.

**Comment by isuruf** [comment]
Ready for merge then?

**Pull request merged**
