### PR TITLE
Update curl pin

### PR DESCRIPTION
**Pull request by isuruf**
Note that 7.59 is not rebuilt for gcc7 label, so this was pulling in curl from defaults. I was thinking of bumping to 7.62, but since the pin was just `x`, we can keep it at 7.

### CODE REVIEW

**Comment by jakirkham** [comment]
Would prefer to go with a more precise version. Just so we can have a common lower bound across the stack.

Otherwise agree bumping the version is needed.

**Comment by isuruf** [comment]
> Would prefer to go with a more precise version. Just so we can have a common lower bound across the stack.

I remember we've had this conversation before, but can you explain this again? Can't remember the reason.

**Comment by isuruf** [comment]
Found the link https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/55/files#r185939678

**Comment by isuruf** [comment]
Is your suggestion to bump the version to 7.62 or 7.62.0?

**Comment by jakirkham** [comment]
That looks right.

7.62 is probably sufficient.

**Comment by bgruening** [comment]
@jakirkham can you please have a look. I included libcurl as well. Not sure if curl is still needed if we have libcurl.

**Comment by mariusvniekerk** [comment]
@jakirkham @isuruf can we land this?

**Pull request merged**
