### PR TITLE
partially close out python, new rerenders will give py38 but the bot should keep issuing PRs since the migrator is still there

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/conda-forge-pinning

**Comment by jakirkham** [comment]
FYI I think @conda-forge/scikit-build is working on getting a Python 3.8 release out, which should let us migrate through more of the graph

**Comment by CJ-Wright** [comment]
Scikit build already went in I think.

**Comment by jakirkham** [comment]
Late yesterday yes. ( https://github.com/conda-forge/scikit-build-feedstock/pull/25 ) They may need some time to get PRs generated for all dependents.

**Comment by jakirkham** [comment]
Apparently we still don't have conda-build on Python 3.8 yet. ( https://github.com/conda-forge/conda-build-feedstock/pull/120 ) Though IDK if that is actually a blocker.

**Comment by xhochy** [comment]
This has been done already.

**Pull request closed without merging**
