### PR TITLE
create geotiff 1.7.3 migrator

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
*  Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
*  [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* Ensured the license file is being packaged.

As with #2676, we seem to need to create a manual migrater for geotiff.

c/f conda-forge/gdal-feedstock#956

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge/geotiff, any concerns? It seems we need this before https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5998 will be useful.

**Comment by hmaarrfk** [comment]
does it make sense to migrate both at the same time?

**Comment by hmaarrfk** [comment]
> or any packages that happen to depend on both

I mean, adding a few lines to the migrator would save you time and effort IMO. but ok! here goes! 

Something to consider for next time!

**Comment by xylar** [comment]
@hmaarrfk, you have more experience tying migrations together than me.  I'm happy to defer to you in the future.  I just thought it would cause confusion.

**Comment by hmaarrfk** [comment]
i mean, it would be new to me as well, just trying to see if we can avoid churn you know!

**Pull request merged**
