### PR TITLE
Add OS X arm migration for libomm, elsi, libmbd

### PR DESCRIPTION
**Pull request by yuzie007**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yuzie007** [comment]
Hello @conda-forge/core members. Thank you so much for maintaining conda-forge.

This my request is to make DFTB+ (dftbplus) available also for Apple Silicon osx_arm64. Although dftbplus itself is in the list of osx_arm64.txt, its direct and indirect parents (libomm, elsi, libmbd) are not in the list yet. I would like to add these packages and to make them available for osx_arm64.

**Comment by xhochy** [comment]
You don't need to add dependencies to the list. The bot will take care that they also will get a rebuild PR.

**Comment by yuzie007** [comment]
Thank you @xhochy for your reply! It seems however dftbplus haven't got an automatic osx_arm64 migration pull request in its conda-feedstock. As a user (I am NOT the developer of dftbplus), what can / should I do then?

**Comment by xhochy** [comment]
Have a look at the graph at https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/status/migration_svg/armosxaddition.svg?sanitize=true This shows on which dependencies the bot is currently waiting to progress with the migration. You can find this graph and similar ones on https://conda-forge.org/status/

**Comment by yuzie007** [comment]
Thank you so much for the very helpful information! I noticed some of the grand-parents of dftbplus wait the osx_arm64 migration. I will then check what I can do for these packages.

**Pull request closed without merging**
