### PR TITLE
add buildah to arch_rebuild.txt

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Hey @ngam, not sure where the desire/need for building buildah on other arches comes from, but in any case, this is stuck on https://github.com/conda-forge/runc-feedstock/pull/4, which will need someone knowledgeable to look at it, because travis isn't playing along, so it'll most likely need to be cross-compiled, and proper [support](https://github.com/opencontainers/runc/pull/3315) for that missed the 1.0.3 release, though it should hopefully work with the upcoming 1.1.0.

CC @conda-forge/runc @conda-forge/buildah

**Comment by ngam** [comment]
> desire/need

definitely desire ~not need~ :)

The immediate motivation is this, which you could merge 😉 https://github.com/conda-forge/staged-recipes/pull/17238

If you dig deeper in this, which won't pass on aarch (due to squashfuse, etc. deps), you will see it can use buildah as... well... a builder. So I thought I would get the ball moving forward by pushing the bot to have a go --- I actually tried to do that manually --- why not?! --- and the errors I/we got were to do with only three deps (two of which I already fixed manually too) but I was like, nah, I won't do the third because it looked bad. Maybe that's where your runc deps comes in? https://github.com/conda-forge/buildah-feedstock/pull/12#issuecomment-991802785

**Comment by ngam** [comment]
Generally, I've been fascinated with the expansiveness in conda-forge and I am trying to push really hard at including a lot of non-Python stuff, just for fun. To see how far we can go. Hence, charliecloud. I am also adding multipass which need libvirt and libapparmor, and so on. Also trying openfoam (a really insane heavy weight). It doesn't actually help --- at all --- that we build on centos. Why not build on ubuntu??? I think things might be a bit easier if we build on ubuntu, but what the hell do I know lol I say that because most people seem to support "linux" by which they mean "ubuntu" and I noticed that some fundamental packages in ubuntu (apt-get, etc.) are not readily available in centos

**Comment by ngam** [comment]
If you do have merge rights, please do the world a favor and merge the containers-common. That feedstock has had a weird typo for a while (0.31.x written as 1.31.x) at least in the last merged item... have no idea how such a thing passed the tests if it did

**Comment by ngam** [comment]
Or @mbargull ... please merge lol

**Comment by ngam** [comment]
@h-vetinari why do we put the ppc and aarch together anyway? They should be separate!

**Comment by h-vetinari** [comment]
> The immediate motivation is this, which you could merge 😉 [conda-forge/staged-recipes#17238](https://github.com/conda-forge/staged-recipes/pull/17238)

I don't see how this relates to buildah or containers?

> you will see it can use buildah as... well... a builder. 

I think this might be a misunderstanding? Buildah builds OCI container images, which conda doesn't deal with. Or do you mean the end users will want to use `buildah`?

> just for fun. To see how far we can go

Nothing wrong with that 🙃 

> I am also adding multipass which needs libvirt and libapparmor, and so on.

Please think thrice about security-relevant packages. It's easy for small packaging mistakes to have an outsized impact. While conda-forge will probably never have the reach of Java, we (well, at least I) do not want a log4shell-esque scenario because someone made a simple oversight.

> Why not build on ubuntu??? I think things might be a bit easier if we build on ubuntu, but what the hell do I know lol I say that because most people seem to support "linux" by which they mean "ubuntu" and I noticed that some fundamental packages in ubuntu (through apt-get, etc.) are not readily available in centos

This is because conda-forge needs a stable baseline, and centos is much more long-lived than ubuntu (without enterprise support). Also there seems to be some confusion - apt-get is the package manager in ubuntu, on centos the equivalent is called yum. You shouldn't use it directly in recipes either. There's a `yum_requirements.txt` that you can use, but even that [should](https://conda-forge.org/docs/maintainer/knowledge_base.html#yum-deps) be used very sparingly.

> If you do have merge rights

I don't. Best to ping on that feedstock (and link it here if necessary). 

> @h-vetinari why do we put the ppc and aarch together anyway? They should be separate!

They've always been handled at the same time, but you can raise an issue to discuss if they should be handled separately.

**Comment by ngam** [comment]
> Also there seems to be some confusion - apt-get is the package manager in ubuntu, on centos the equivalent is called yum.

No no, no confusion. What I am saying is actually that there are some smaller packages that you can easily get via something like apt-get that you cannot get via yum, etc. --- that was at least my experience with some essential tools needed for building multipass/libapparmor, etc. 

> I think this might be a misunderstanding? Buildah builds OCI container images, which conda doesn't deal with. Or do you mean the end users will want to use buildah?

Yes, that's accurate --- and that's what charliecloud would use buildah to do. See this:

```
Dependencies report
===================

Below is a summary of configure's findings.

Caveats
~~~~~~~

Charliecloud's run-time dependencies are lazy; features just try to use their
dependencies and error if there's a problem. This report summarizes what
configure found on *this system*, because that's often useful, but none of the
run-time findings change what is built and installed.

Listed versions are minimums. These are a bit fuzzy. Try it even if configure
thinks a version is too old, and please report back to us.

Building Charliecloud
~~~~~~~~~~~~~~~~~~~~~

  will build and install:
    HTML documentation ... no
    man pages ... no
    test suite ... yes
    ch-image(1) ... yes

  required:
    C99 compiler ... $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc 

  bundled Lark: yes
    lark.py under source dir ... yes

  documentation: no
    sphinx-build(1) ≥ 1.2.3 ... not found
    sphinx-build(1) Python ... n/a
    "docutils" module ≥ 0.14 ... moot b/c no sphinx-build
    "sphinx-rtd-theme" module ≥ 0.2.4 ... moot b/c no sphinx-build

Building images via our wrappers
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  with Buildah: no
    Buildah ≥ 1.11.2 ... not found

  with ch-image(1): no
    enabled ... yes
    Python shebang line ... /usr/bin/env python3
    Python in shebang ≥ 3.6 ... ok (3.7.12)
    "requests" module ≥ 2.6.0 ... ok (2.26.0)
    ch-run(1) ... no

  with Docker: no
    Docker ≥ 17.03 ... not found
    mktemp(1) ... mktemp


Managing container images
~~~~~~~~~~~~~~~~~~~~~~~~~

  build from Dockerfile with ch-build(1): no
    at least one builder ... no
    access to an image repository ... assumed yes

  pack images from builder storage to tarball: no
    at least one builder ... no
    tar(1) ... tar

  pack images from builder storage to SquashFS: no
    at least one builder ... no
    mksquashfs(1) ≥ 4.2 ... not found

  Note: Pulling/pushing images from/to a repository is currently done using
  the builder directly.

```

Rest in here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=426986&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1297

**Comment by ngam** [comment]
Since you seem to be involved in this space, you should check out charliecloud. It seems like a neat solution, and they have a native "builder", `ch-image`

**Comment by ngam** [comment]
> Please think thrice about security-relevant packages. It's easy for small packaging mistakes to have an outsized impact. While conda-forge will probably never have the reach of Java, we (well, at least I) do not want a log4shell-esque scenario because someone made a simple oversight.

Also lol. I will do my best. But three things (a la your thrice): 1) I would be pretty surprised if we don't _already_ have nasty things around circulating in the myriad of code; 2) conda-forge seems robust enough that we would be able to reverse things more orderly; and 3) I would worry most about the weird submodule-esque intransparent packaging that goes on and I think cond-forge/core should consider banning that practice...

**Comment by h-vetinari** [comment]
> 1) I would be pretty surprised if we don't already have nasty things around circulating in the myriad of code;

Not an argument at all to add more. The feedstock-model is IMO not nearly safe enough or security-critical packages. We cannot avoid openssl/cryptography, but there at least we can run the full test suites. The closer you get to the OS, the harder it is to truly test if you've got everything working correctly (e.g. some tests might be destructive and cannot be executed in CI). That's not to say it cannot be done, but it's no laughing matter.

> 2) conda-forge seems robust enough that we would be able to reverse things more orderly

That's not the point. Updating versions or marking builds as broken is easy - the much harder thing is a large affected install base, some of which might not even be internet-facting but _still_ vulnerable (as is [happening](https://twitter.com/Laughing_Mantis/status/1469817065850560525) with log4shell).

> 3) I would worry most about the weird submodule-esque intransparent packaging that goes on and I think cond-forge/core should consider banning that practice...

Please avoid vague & (close-to-)moralizing statements like this. Submodules are not a problem in and of themselves. Some feedstocks don't fully unvendor all components, and that can generally be improved, but I'd guess that in almost all cases, there are very good reasons for the state of things. If there's a problem you've identified, raise an issue (or better: a PR) on the feedstock, or if it concerns all of conda-forge, then [here](https://github.com/conda-forge/conda-forge.github.io/).

**Comment by ngam** [comment]
Totally agree @h-vetinari, and sorry if my statements come across as moralizing --- the intention is to add rigor and (easy-to-see) transparency, not morality :)

**Comment by ngam** [comment]
> I don't see how this relates to buildah or containers?

Did I make this clearer above? I want to make sure I am not misunderstanding things.

**Comment by h-vetinari** [comment]
> Did I make this clearer above? I want to make sure I am not misunderstanding things.

I haven't looked closely, but it sounds reasonable.

**Pull request merged**
