### PR TITLE
Add `qgis` to arch migrations

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc @conda-forge/qgis

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @gillins (for vis)

**Comment by gillins** [comment]
Thanks @jakirkham This seems to have created a bunch of PRs for the `qgis` dependencies (https://github.com/conda-forge/qtwebkit-feedstock/pull/28, https://github.com/conda-forge/qtwebkit-feedstock/pull/29, https://github.com/conda-forge/qtkeychain-feedstock/pull/19, https://github.com/conda-forge/qtkeychain-feedstock/pull/20) that don't do much apart from tidy up the `conda-forge.yml` (because they've already been migrated I guess). Is it safe to merge these ones?

**Comment by jakirkham** [comment]
We can also just close them and the migrator will treat them as completed

**Comment by jakirkham** [comment]
Went ahead and just closed them all. The migration bot should pick it up from there

**Comment by gillins** [comment]
Thanks @jakirkham !

**Pull request merged**
