### PR TITLE
OSX: Clang 14

### PR DESCRIPTION
**Pull request by ax3l**
Bump to LLVM/Clang 14 to fix incompatibilities with `strip`/`llvm-strip` for Apple M1/M2 (ARM/aarch64/arm64) systems.

cc @isuruf @xhochy

X-ref: https://github.com/AMReX-Codes/pyamrex/issues/35

- `llvm-strip` 13 fixed part of this:
  - https://github.com/llvm/llvm-project/commit/151990dd94e5
  - https://github.com/llvm/llvm-project/commit/0e319bd0be26c3a11ab1876da4bbb9259d3f6107
- LLVM 14 should fix it for good:
  - https://github.com/llvm/llvm-project/commit/8fbe1e760224
  - https://github.com/llvm/llvm-project/commit/a299b24712

Current work-around: Pass `-DCMAKE_STRIP=$(which strip)` to all CMake configure steps when building for M1/M2 targets. This is needed if binary stripping is used, e.g., used by default with pybind11's CMake logic.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by isuruf — APPROVED** [review]

**Comment by jakirkham** [comment]
Is a migration needed for this?

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
> Is a migration needed for this?

No, binaries built with the new compilers should be compatible with ones build by the old one. If we would run a migration here, we would rebuild all packages with C/C++ code (which would be massive).

**Comment by ax3l** [comment]
Thanks a lot for merging!

16hrs after merge, I wanted to test this now via:
```console
mamba create -n test-dev -c conda-forge compilers
```

but still get:
```
  Package                            Version  Build               Channel                     Size
────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────────────

...
  + clang                             13.0.1  hce30654_0          conda-forge/osx-arm64     Cached
  + clang-13                          13.0.1  default_h2cfa9b4_0  conda-forge/osx-arm64     Cached
  + clang_osx-arm64                   13.0.1  hc97ff27_2          conda-forge/osx-arm64       17kB
  + clangxx                           13.0.1  default_hf584372_0  conda-forge/osx-arm64     Cached
  + clangxx_osx-arm64                 13.0.1  h15d2725_2          conda-forge/osx-arm64       16kB
  + compiler-rt                       13.0.1  h94c6b0c_0          conda-forge/osx-arm64     Cached
  + compiler-rt_osx-arm64             13.0.1  h44bac85_0          conda-forge/noarch        Cached
  + compilers                          1.4.2  hce30654_0          conda-forge/osx-arm64     Cached
  + cxx-compiler                       1.4.2  hf86a087_0          conda-forge/osx-arm64     Cached
  + fortran-compiler                   1.4.2  h2cbcb21_0          conda-forge/osx-arm64     Cached
  + gfortran                     11.0.1.dev0  h40eb566_15         conda-forge/osx-arm64     Cached
  + gfortran_impl_osx-arm64      11.0.1.dev0  hbce66ab_23         conda-forge/osx-arm64     Cached
  + gfortran_osx-arm64           11.0.1.dev0  h57527a5_15         conda-forge/osx-arm64     Cached
  + gmp                                6.2.1  h9f76cd9_0          conda-forge/osx-arm64     Cached
  + isl                               0.22.1  hb904e53_2          conda-forge/osx-arm64     Cached
  + ld64                                 609  h954701c_10         conda-forge/osx-arm64       16kB
  + ld64_osx-arm64                       609  h6ce2ded_10         conda-forge/osx-arm64        1MB
  + libclang-cpp13                    13.0.1  default_h2cfa9b4_0  conda-forge/osx-arm64     Cached
  + libcxx                            14.0.6  h04bba0f_0          conda-forge/osx-arm64     Cached
  + libgfortran                   5.0.0.dev0  11_0_1_hf114ba7_23  conda-forge/osx-arm64     Cached
  + libgfortran-devel_osx-arm64  11.0.1.dev0  hf114ba7_23         conda-forge/noarch        Cached
  + libgfortran5                 11.0.1.dev0  hf114ba7_23         conda-forge/osx-arm64     Cached
  + libiconv                            1.16  h642e427_0          conda-forge/osx-arm64     Cached
  + libllvm13                         13.0.1  hfd59cb2_2          conda-forge/osx-arm64     Cached
  + libzlib                           1.2.12  ha287fd2_2          conda-forge/osx-arm64     Cached
  + llvm-openmp                       14.0.4  hd125106_0          conda-forge/osx-arm64      304kB
  + llvm-tools                        13.0.1  hfd59cb2_2          conda-forge/osx-arm64     Cached
...
```

Did we miss something we need to bump up?

**Comment by ax3l** [comment]
If I do:
```console
mamba create -n warpx-dev -c conda-forge compilers "clang==14*"
```

I get
```
Encountered problems while solving:
  - package c-compiler-1.1.2-h27ca646_0 requires clang_osx-arm64 11.*, but none of the providers can be installed
```

The install of `clang==14` alone works. Do we need to update `c-compiler`/`cxx-compiler`/`fortran-compiler` now?

**Comment by ax3l** [comment]
Checked again today, still the same issue.

@xhochy @isuruf any idea what's missing to update this? :)

**Comment by isuruf** [comment]
See https://github.com/conda-forge/compilers-feedstock/pull/50

**Comment by ax3l** [comment]
Thanks a lot! 🎉

**Comment by ax3l** [comment]
Just tested: Apple M1 usage of `llvm-strip` with Clang/LLVM 14 works like a charm, thanks a lot! :tada:

**Pull request merged**
