### PR TITLE
Finish boost 1.74 migration

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by beckermr — COMMENTED** [review]
I'm ok with this but there are still 7 feedstocks that have not gotten a PR. Many of them are ROS packages. cc @wolfv

**Comment by isuruf** [comment]
We agreed on this in the last core meeting.

**Comment by beckermr** [comment]
Yup. I remember! I am simply bumping @wolfv so he knows. :)

**Review by beckermr — APPROVED** [review]

**Comment by beckermr** [comment]
Alright. It's been a week. Let's merge this one.

**Pull request merged**
