### PR TITLE
Request arch migration for `databricks-cli`

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
I'm still not too sure how this works, is this how I'd go about requesting `linux-aarch64` support for the `databricks-cli` feedstock?

**Comment by dhirschfeld** [comment]
***xref:*** https://github.com/conda-forge/databricks-cli-feedstock/issues/32

**Comment by martin-g** [comment]
Now you need to merge https://github.com/conda-forge/databricks-cli-feedstock/pull/39 and the task will be fully finished!

**Comment by dhirschfeld** [comment]
Amazing! Thanks Martin! :heart:

**Pull request merged**
