### PR TITLE
Pin openturns 1.12*

### PR DESCRIPTION
**Pull request by jschueller**
xref https://github.com/conda-forge/openturns-feedstock/pull/60

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
Good to go @conda-forge/conda-forge-pinning ?

**Comment by ocefpaf** [comment]
@jschueller I don't know the first thing about `openturns`, do we have an ABI compatibility URL to guide this decision?

**Comment by jschueller** [comment]
basically there is no binary compatibility, I handle all the openturns children packages updating here, and I want to rebuild them now that openturns 1.12rc1 is published.

**Pull request merged**
