### PR TITLE
close out libtiff, geos, and netcdf-fortran

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@dopplershift did you ask that I leave one of these open? I thought you had asked for one migration to be open, but I've forgotten which one.

**Comment by dopplershift** [comment]
I don't recall requesting it...maybe @ocefpaf?

**Comment by ocefpaf** [comment]
> I don't recall requesting it...maybe @ocefpaf?

Nope. I was not me :smile:

**Comment by ocefpaf** [comment]
All the PRs in those mogrations were issued. This is good to merge.

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
