### PR TITLE
Resume python 3.13

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
cc @hmaarrfk @jakirkham

**Comment by beckermr** [comment]
There was a suggestion to wait for numpy which is blocked on cython not yet getting a PR. I don't care but I did want to raise the issue.

**Review by hmaarrfk — APPROVED** [review]
numpy and cython are part of the standard migration process.

The problem for me was that https://github.com/conda-forge/cross-python-feedstock/pull/79 was held up

happy to resume!

**Review by beckermr — COMMENTED** [review]
Lgtm from me too. The bot did fail on cython before for reasons I did not figure out.

**Review by beckermr — APPROVED** [review]

**Comment by isuruf** [comment]
> The bot did fail on cython before for reasons I did not figure out.

The cycle is gone now with the intel-compile-repack PR

**Comment by beckermr** [comment]
Yes @isuruf, but the cython failure was unrelated though I think. The bot had marked the cython graph node as "bad" so it was being skipped. I do not know why it did that. I added extra debugging output to get more information when it happens next.

**Review by h-vetinari — DISMISSED** [review]
We should decide what we want to do with [numpy](https://github.com/conda-forge/numpy-feedstock/pull/329#issuecomment-2322343868)

**Comment by isuruf** [comment]
That doesn't matter. The migration can stop at numpy for its children.

**Comment by h-vetinari** [comment]
> That doesn't matter. The migration can stop at numpy for its children.

numpy itself doesn't matter (aside from its size), but the choice around cython has potentially migration-wide impact

**Comment by h-vetinari** [comment]
> We can wait at cython migration too.

Cython is migrated. The point is we might need to use a cython development version for numpy (and possibly elsewhere), and using that potentially has ABI implications. Please just read my comment there. Making a choice on this is not a huge roadblock.

**Comment by beckermr** [comment]
Maybe we poke the numpy folks for a bug fix? It seems odd to do all dev against an unreleased dependency.

**Comment by isuruf** [comment]
> Cython is migrated. 

No, it's not. It's marked as awaiting PR. (After the cycle was eliminated). Numyp PR got issued prematurely because of the cycle, but that's gone.

**Comment by h-vetinari** [comment]
> Maybe we poke the numpy folks for a bug fix? It seems odd to do all dev against an unreleased dependency.

All the links are in the comment I xref'd

> No, it's not. It's marked as awaiting PR. (After the cycle was eliminated). Numyp PR got issued prematurely because of the cycle, but that's gone.

I'm very aware of all that, but cython _is_ migrated, because I did it [manually](https://github.com/conda-forge/cython-feedstock/pull/143). Otherwise I wouldn't be able to talk about the numpy build situation.

**Comment by beckermr** [comment]
The repo could be migrated but the status page be wrong. The bot won't catch something being migrated by hand if a migration is paused.

**Comment by isuruf** [comment]
We can revert the manual PR and let the bot make a PR and stop there.

**Comment by h-vetinari** [comment]
> We can revert the manual PR and let the bot make a PR and stop there.

I feel we're talking past each other. Yes, the loop is gone, the migration can proceed from the POV of the DAG. Nothing needs to be reverted though, cython 3.0.11 is 3.13 compatible, so publishing builds for that is fine.

The issue is that numpy doesn't build 100% successfully with 3.0.11 due to bugs. We can skip those test failures (easiest IMO), or we can consider using a development cython version (more proper, but potentially bigger blast radius on the whole migration).

All that discussion should be had elsewhere though. In the time we've gone back and forth here we could have already come to a decision there. Let's continue this in https://github.com/conda-forge/numpy-feedstock/pull/329.

**Comment by isuruf** [comment]
All that matters for this PR is the following question

- Is Cython 3.0.11 broken on python 3.13?

If the answer is no

- We merge this PR

If the answer is yes

- We revert the cython PR, stop the migration for cython in the bot PR and we merge this PR.

**Comment by beckermr** [comment]
Yeah I had read that issue @h-vetinari but I didn't really follow that it was pointing out this was an issue with numpy. The solution to depend on a dev release of cython seems odd.

**Comment by beckermr** [comment]
I left my comments on the numpy issue. Let's merge this.

**Comment by h-vetinari** [comment]
> Is Cython 3.0.11 broken on python 3.13?

The world is not so black and white. It can be 99% functional (as appears to be the case, because 99.9% numpy tests pass on osx, and 100% everywhere else). 

> [in either case] we merge this PR

If you're so keen on that, go ahead. My point is that cython/numpy are two of the most fundamental deps in the python migration, and figuring out the path we want to take there is worthwhile.

**Comment by isuruf** [comment]
Thanks for the reviews.

**Pull request merged**
